const path="/menu/"
const MenuCn=[
    { id: "0", name: "炸面包", price: 1.00, imageLink: `${path}0.jpg`, description: "", category: "前餐" },
    { id: "0A", name: "蒸面包", price: 1.00, imageLink: `${path}0A.jpg`, description: "", category: "前餐" },
    { id: "1", name: "春卷", price: 1.50, imageLink: `${path}1.jpg`, description: "", category: "前餐" },
    { id: "1A", name: "海鲜春卷", price: 1.80, imageLink: `${path}1A.jpg`, description: "", category: "前餐" },
    { id: "2", name: "炸云吞", price: 1.60, imageLink: `${path}2.jpg`, description: "", category: "前餐" },
    { id: "3", name: "虾片", price: 1.50, imageLink: `${path}3.jpg`, description: "", category: "前餐" },
    { id: "4", name: "炸海菜", price: 3.00, imageLink: `${path}4.jpg`, description: "", category: "前餐" },
    { id: "5", name: "土豆饼", price: 2.00, imageLink: `${path}5.jpg`, description: "", category: "前餐" },
    { id: "5A", name: "番茄面包", price: 2.60, imageLink: `${path}5A.jpg`, description: "", category: "前餐" },
    { id: "6", name: "炸薯条", price: 2.50, imageLink: `${path}6.jpg`, description: "", category: "前餐" },
    { id: "7", name: "土司", price: 2.50, imageLink: `${path}7.jpg`, description: "", category: "前餐" },
    { id: "8", name: "葱油饼", price: 3.00, imageLink: `${path}8.jpg`, description: "", category: "前餐" },
    { id: "9", name: "肉饺", price: 3.20, imageLink: `${path}9.jpg`, description: "", category: "前餐" },
    { id: "10", name: "菜饺", price: 3.40, imageLink: `${path}10.jpg`, description: "", category: "前餐" },
    { id: "11", name: "锅贴", price: 3.60, imageLink: `${path}11.jpg`, description: "", category: "前餐" },
    { id: "12", name: "烧卖", price: 3.80, imageLink: `${path}12.jpg`, description: "", category: "前餐" },
    { id: "12A", name: "水晶饺", price: 3.80, imageLink: `${path}12A.jpg`, description: "", category: "前餐" },
    { id: "12B", name: "什锦饺子 (请看 9,10,12号)", price: 3.80, imageLink: `${path}12B.jpg`, description: "", category: "前餐" },
    { id: "12C", name: "悦来饺", price: 3.80, imageLink: `${path}12C.jpg`, description: "", category: "前餐" },
    { id: "13", name: "什锦热盘 (请看 1,2,3,5,7 号)", price: 4.00, imageLink: `${path}13.jpg`, description: "", category: "前餐" },
    { id: "14", name: "炸蔬菜", price: 3.00, imageLink: `${path}14.jpg`, description: "", category: "前餐" },
    { id: "14A", name: "芝麻球", price: 3.50, imageLink: `${path}14A.jpg`, description: "", category: "前餐" },
    { id: "14B", name: "炸洋葱圈", price: 3.00, imageLink: `${path}14B.jpg`, description: "", category: "前餐" },
    { id: "14C", name: "毛豆夹", price: 3.50, imageLink: `${path}14C.jpg`, description: "", category: "前餐" },
    { id: "15", name: "海带沙拉", price: 3.00, imageLink: `${path}15.jpg`, description: "", category: "沙拉菜" },
    { id: "16", name: "鸡肉肉沙拉", price: 3.50, imageLink: `${path}16.jpg`, description: "", category: "沙拉菜" },
    { id: "17", name: "虾沙拉", price: 3.50, imageLink: `${path}17.jpg`, description: "", category: "沙拉菜" },
    { id: "17A", name: "蟹肉沙拉", price: 3.50, imageLink: `${path}17A.jpg`, description: "", category: "沙拉菜" },
    { id: "17B", name: "什锦沙拉", price: 3.00, imageLink: `${path}17B.jpg`, description: "", category: "沙拉菜" },
    { id: "17C", name: "特酱沙拉", price: 4.00, imageLink: `${path}17C.jpg`, description: "", category: "沙拉菜" },
    { id: "17D", name: "海鲜沙拉", price: 6.00, imageLink: `${path}17D.jpg`, description: "", category: "沙拉菜" },
    { id: "17E", name: "半虾蟹沙拉", price: 4.00, imageLink: `${path}17E.jpg`, description: "", category: "沙拉菜" },
    { id: "18", name: "幸运汤", price: 3.00, imageLink: `${path}18.jpg`, description: "", category: "汤" },
    { id: "19", name: "云吞汤", price: 3.00, imageLink: `${path}19.jpg`, description: "", category: "汤" },
    { id: "19A", name: "悦来汤", price: 3.50, imageLink: `${path}19A.jpg`, description: "", category: "汤" },
    { id: "20", name: "双冬鸡汤", price: 3.00, imageLink: `${path}20.jpg`, description: "", category: "汤" },
    { id: "21", name: "酸辣汤", price: 3.00, imageLink: `${path}21.jpg`, description: "", category: "汤" },
    { id: "22", name: "榨菜粉丝汤", price: 3.00, imageLink: `${path}22.jpg`, description: "", category: "汤" },
    { id: "23", name: "鸡肉肉玉米汤", price: 3.00, imageLink: `${path}23.jpg`, description: "", category: "汤" },
    { id: "24", name: "蟹肉芦笋汤", price: 3.50, imageLink: `${path}24.jpg`, description: "", category: "汤" },
    { id: "25A", name: "蔬菜汤", price: 3.00, imageLink: `${path}25A.jpg`, description: "", category: "汤" },
    { id: "25B", name: "味噌汤", price: 3.00, imageLink: `${path}25B.jpg`, description: "", category: "汤" },
    { id: "25C", name: "海鲜汤", price: 3.80, imageLink: `${path}25C.jpg`, description: "", category: "汤" },
    { id: "25D", name: "泰式虾汤", price: 3.80, imageLink: `${path}25D.jpg`, description: "", category: "汤" },
    { id: "25E", name: "泰式鸡汤", price: 3.80, imageLink: `${path}25E.jpg`, description: "", category: "汤" },
    { id: "26", name: "素菜炒面", price: 3.50, imageLink: `${path}26.jpg`, description: "", category: "饭面" },
    { id: "26A", name: "素炒乌冬", price: 4.00, imageLink: `${path}26A.jpg`, description: "", category: "饭面" },
    { id: "26B", name: "海炒乌冬", price: 5.50, imageLink: `${path}26B.jpg`, description: "", category: "饭面" },
    { id: "26C", name: "海鲜汤面", price: 6.00, imageLink: `${path}26C.jpg`, description: "", category: "饭面" },
    { id: "26D", name: "肉汤面", price: 6.00, imageLink: `${path}26D.jpg`, description: "", category: "饭面" },
    { id: "27", name: "虾仁炒面", price: 4.20, imageLink: `${path}27.jpg`, description: "", category: "饭面" },
    { id: "28", name: "铁板素面", price: 4.00, imageLink: `${path}28.jpg`, description: "", category: "饭面" },
    { id: "28A", name: "担担面", price: 4.00, imageLink: `${path}28A.jpg`, description: "", category: "饭面" },
    { id: "28B", name: "铁板肉面", price: 4.50, imageLink: `${path}28B.jpg`, description: "", category: "饭面" },
    { id: "28C", name: "担担饭", price: 4.00, imageLink: `${path}28C.jpg`, description: "", category: "饭面" },
    { id: "29", name: "海鲜面", price: 4.90, imageLink: `${path}29.jpg`, description: "", category: "饭面" },
    { id: "29A", name: "海鲜粉丝", price: 4.90, imageLink: `${path}29A.jpg`, description: "", category: "饭面" },
    { id: "29B", name: "海鲜粉干", price: 4.90, imageLink: `${path}29B.jpg`, description: "", category: "饭面" },
    { id: "30", name: "素菜炸面", price: 3.50, imageLink: `${path}30.jpg`, description: "", category: "饭面" },
    { id: "30A", name: "海鲜炸面", price: 4.90, imageLink: `${path}30A.jpg`, description: "", category: "饭面" },
    { id: "31", name: "素菜粉干", price: 3.50, imageLink: `${path}31.jpg`, description: "", category: "饭面" },
    { id: "31A", name: "海鲜炒粉干", price: 4.90, imageLink: `${path}31A.jpg`, description: "", category: "饭面" },
    { id: "31B", name: "虾仁粉干", price: 4.20, imageLink: `${path}31B.jpg`, description: "", category: "饭面" },
    { id: "32", name: "肉粉干", price: 4.00, imageLink: `${path}32.jpg`, description: "", category: "饭面" },
    { id: "33", name: "咖喱粉干", price: 3.50, imageLink: `${path}33.jpg`, description: "", category: "饭面" },
    { id: "34", name: "肉末粉丝", price: 4.00, imageLink: `${path}34.jpg`, description: "", category: "饭面" },
    { id: "35", name: "素菜粉丝", price: 3.50, imageLink: `${path}35.jpg`, description: "", category: "饭面" },
    { id: "35A", name: "虾仁粉丝", price: 4.20, imageLink: `${path}35A.jpg`, description: "", category: "饭面" },
    { id: "36", name: "素菜年糕", price: 3.80, imageLink: `${path}36.jpg`, description: "", category: "饭面" },
    { id: "36A", name: "海鲜年糕", price: 5.00, imageLink: `${path}36A.jpg`, description: "", category: "饭面" },
    { id: "36B", name: "肉年糕", price: 4.30, imageLink: `${path}36B.jpg`, description: "", category: "饭面" },
    { id: "37", name: "虾仁炒饭", price: 4.20, imageLink: `${path}37.jpg`, description: "", category: "饭面" },
    { id: "38", name: "素菜炒饭", price: 3.50, imageLink: `${path}38.jpg`, description: "", category: "饭面" },
    { id: "39", name: "广东饭", price: 3.50, imageLink: `${path}39.jpg`, description: "", category: "饭面" },
    { id: "39A", name: "鸡肉饭", price: 3.50, imageLink: `${path}39A.jpg`, description: "", category: "饭面" },
    { id: "40", name: "咖喱饭", price: 3.50, imageLink: `${path}40.jpg`, description: "", category: "饭面" },
    { id: "41", name: "菠萝炒饭", price: 4.00, imageLink: `${path}41.jpg`, description: "", category: "饭面" },
    { id: "42", name: "白饭", price: 1.50, imageLink: `${path}42.jpg`, description: "", category: "饭面" },
    { id: "42A", name: "什锦肉锅巴", price: 4.50, imageLink: `${path}42A.jpg`, description: "", category: "饭面" },
    { id: "42B", name: "海鲜锅巴", price: 4.90, imageLink: `${path}42B.jpg`, description: "", category: "饭面" },
    { id: "42C", name: "番茄面", price: 3.50, imageLink: `${path}42C.jpg`, description: "", category: "饭面" },
    { id: "42D", name: "Ragù面", price: 3.50, imageLink: `${path}42D.jpg`, description: "", category: "饭面" },
    { id: "42E", name: "海鲜饭", price: 4.90, imageLink: `${path}42E.jpg`, description: "", category: "饭面" },
    { id: "42F", name: "炒饭", price: 5.00, imageLink: `${path}42F.jpg`, description: "", category: "饭面" },
    { id: "42G", name: "炒面", price: 5.00, imageLink: `${path}42G.jpg`, description: "", category: "饭面" },
    { id: "42H", name: "泰式炒面", price: 4.50, imageLink: `${path}42H.jpg`, description: "", category: "饭面" },
    { id: "42L", name: "泰式炒饭", price: 4.50, imageLink: `${path}42L.jpg`, description: "", category: "饭面" },
    { id: "43", name: "双冬虾仁", price: 6.00, imageLink: `${path}43.jpg`, description: "", category: "海鲜" },
    { id: "44", name: "五彩虾仁", price: 6.00, imageLink: `${path}44.jpg`, description: "", category: "海鲜" },
    { id: "45", name: "青豆虾仁", price: 6.00, imageLink: `${path}45.jpg`, description: "", category: "海鲜" },
    { id: "45A", name: "腰果虾仁", price: 6.00, imageLink: `${path}45A.jpg`, description: "", category: "海鲜" },
    { id: "46", name: "咖喱虾仁", price: 6.00, imageLink: `${path}46.jpg`, description: "", category: "海鲜" },
    { id: "47", name: "辣子虾仁", price: 6.00, imageLink: `${path}47.jpg`, description: "", category: "海鲜" },
    { id: "47A", name: "宫爆虾仁", price: 6.00, imageLink: `${path}47A.jpg`, description: "", category: "海鲜" },
    { id: "48", name: "糖醋虾仁", price: 6.00, imageLink: `${path}48.jpg`, description: "", category: "海鲜" },
    { id: "48A", name: "糖醋虾仁 (不炸)", price: 6.00, imageLink: `${path}48A.jpg`, description: "", category: "海鲜" },
    { id: "49", name: "苹果虾仁", price: 6.00, imageLink: `${path}49.jpg`, description: "", category: "海鲜" },
    { id: "49A", name: "桔子虾仁", price: 6.00, imageLink: `${path}49A.jpg`, description: "", category: "海鲜" },
    { id: "49B", name: "柠檬虾仁", price: 6.00, imageLink: `${path}49B.jpg`, description: "", category: "海鲜" },
    { id: "49C", name: "菠萝虾仁", price: 6.00, imageLink: `${path}49C.jpg`, description: "", category: "海鲜" },
    { id: "50", name: "炸虾仁", price: 6.00, imageLink: `${path}50.jpg`, description: "", category: "海鲜" },
    { id: "50A", name: "芝麻炸虾仁", price: 6.50, imageLink: `${path}50A.jpg`, description: "", category: "海鲜" },
    { id: "51", name: "椒盐虾仁", price: 6.50, imageLink: `${path}51.jpg`, description: "", category: "海鲜" },
    { id: "52", name: "铁板虾仁", price: 6.50, imageLink: `${path}52.jpg`, description: "", category: "海鲜" },
    { id: "53A", name: "虾巢", price: 6.50, imageLink: `${path}53A.jpg`, description: "", category: "海鲜" },
    { id: "53B", name: "海鲜巢", price: 6.50, imageLink: `${path}53B.jpg`, description: "", category: "海鲜" },
    { id: "53C", name: "串海鲜", price: 7.00, imageLink: `${path}53C.jpg`, description: "", category: "海鲜" },
    { id: "53D", name: "串虾", price: 7.00, imageLink: `${path}53D.jpg`, description: "", category: "海鲜" },
    { id: "53E", name: "串鱿鱼", price: 7.00, imageLink: `${path}53E.jpg`, description: "", category: "海鲜" },
    { id: "53F", name: "泰式海鲜", price: 7.00, imageLink: `${path}53F.jpg`, description: "", category: "海鲜" },
    { id: "53G", name: "沙茶海鲜", price: 7.00, imageLink: `${path}53G.jpg`, description: "", category: "海鲜" },
    { id: "54", name: "辣子大虾", price: 6.50, imageLink: `${path}54.jpg`, description: "", category: "海鲜" },
    { id: "55", name: "清蒸大虾", price: 6.50, imageLink: `${path}55.jpg`, description: "", category: "海鲜" },
    { id: "56", name: "红烧大虾", price: 6.50, imageLink: `${path}56.jpg`, description: "", category: "海鲜" },
    { id: "57", name: "芝麻大虾", price: 6.50, imageLink: `${path}57.jpg`, description: "", category: "海鲜" },
    { id: "57A", name: "凤尾虾", price: 7.00, imageLink: `${path}57A.jpg`, description: "", category: "海鲜" },
    { id: "58", name: "烤大虾 (6 只)", price: 9.00, imageLink: `${path}58.jpg`, description: "", category: "海鲜" },
    { id: "59", name: "铁板大虾", price: 9.00, imageLink: `${path}59.jpg`, description: "", category: "海鲜" },
    { id: "59A", name: "椒盐大虾", price: 9.00, imageLink: `${path}59A.jpg`, description: "", category: "海鲜" },
    { id: "59B", name: "火烧大虾", price: 9.00, imageLink: `${path}59B.jpg`, description: "", category: "海鲜" },
    { id: "60", name: "铁板海鲜", price: 7.00, imageLink: `${path}60.jpg`, description: "", category: "海鲜" },
    { id: "61", name: "柠檬鱼片", price: 6.00, imageLink: `${path}61.jpg`, description: "", category: "海鲜" },
    { id: "62", name: "清蒸鱼片", price: 6.00, imageLink: `${path}62.jpg`, description: "", category: "海鲜" },
    { id: "63", name: "烤全鱼", price: 10.00, imageLink: `${path}63.jpg`, description: "", category: "海鲜" },
    { id: "64", name: "清蒸全鱼", price: 10.00, imageLink: `${path}64.jpg`, description: "", category: "海鲜" },
    { id: "65", name: "红烧全鱼", price: 10.00, imageLink: `${path}65.jpg`, description: "", category: "海鲜" },
    { id: "66", name: "辣子鱿鱼", price: 6.00, imageLink: `${path}66.jpg`, description: "", category: "海鲜" },
    { id: "67", name: "糖醋鱿鱼", price: 6.00, imageLink: `${path}67.jpg`, description: "", category: "海鲜" },
    { id: "67A", name: "糖醋鱿鱼 (不炸)", price: 6.00, imageLink: `${path}67A.jpg`, description: "", category: "海鲜" },
    { id: "68", name: "什锦鱿鱼", price: 6.00, imageLink: `${path}68.jpg`, description: "", category: "海鲜" },
    { id: "68A", name: "铁板鱿鱼", price: 6.50, imageLink: `${path}68A.jpg`, description: "", category: "海鲜" },
    { id: "69", name: "炸田鸡", price: 7.50, imageLink: `${path}69.jpg`, description: "", category: "海鲜" },
    { id: "70", name: "铁板田鸡", price: 7.50, imageLink: `${path}70.jpg`, description: "", category: "海鲜" },
    { id: "71", name: "炸蟹钳 (5 只)", price: 6.50, imageLink: `${path}71.jpg`, description: "", category: "海鲜" },
    { id: "71A", name: "清蒸螃蟹", price: 9.00, imageLink: `${path}71A.jpg`, description: "", category: "海鲜" },
    { id: "71B", name: "红烧螃蟹", price: 9.00, imageLink: `${path}71B.jpg`, description: "", category: "海鲜" },
    { id: "71C", name: "椒盐螃蟹", price: 9.00, imageLink: `${path}71C.jpg`, description: "", category: "海鲜" },
    { id: "72", name: "炸海鲜", price: 6.00, imageLink: `${path}72.jpg`, description: "", category: "海鲜" },
    { id: "73", name: "海鲜砂锅", price: 7.00, imageLink: `${path}73.jpg`, description: "", category: "海鲜" },
    { id: "74", name: "糖醋鸡", price: 5.00, imageLink: `${path}74.jpg`, description: "", category: "鸡肉" },
    { id: "74A", name: "青椒鸡片", price: 5.00, imageLink: `${path}74A.jpg`, description: "", category: "鸡肉" },
    { id: "74B", name: "糖醋鸡 (不炸)", price: 5.00, imageLink: `${path}74B.jpg`, description: "", category: "鸡肉" },
    { id: "75", name: "柠檬鸡", price: 5.00, imageLink: `${path}75.jpg`, description: "", category: "鸡肉" },
    { id: "75A", name: "柠檬鸡(不炸)", price: 5.00, imageLink: `${path}75A.jpg`, description: "", category: "鸡肉" },
    { id: "75B", name: "芦笋鸡片", price: 5.00, imageLink: `${path}75B.jpg`, description: "", category: "鸡肉" },
    { id: "75C", name: "芹菜鸡片", price: 5.00, imageLink: `${path}75C.jpg`, description: "", category: "鸡肉" },
    { id: "76", name: "桔子鸡", price: 5.00, imageLink: `${path}76.jpg`, description: "", category: "鸡肉" },
    { id: "76A", name: "桔子鸡 (不炸)", price: 5.00, imageLink: `${path}76A.jpg`, description: "", category: "鸡肉" },
    { id: "77", name: "豆芽鸡片", price: 5.00, imageLink: `${path}77.jpg`, description: "", category: "鸡肉" },
    { id: "78", name: "杏仁鸡丁", price: 5.00, imageLink: `${path}78.jpg`, description: "", category: "鸡肉" },
    { id: "78A", name: "腰果鸡丁", price: 5.00, imageLink: `${path}78A.jpg`, description: "", category: "鸡肉" },
    { id: "79", name: "宫爆鸡丁", price: 5.00, imageLink: `${path}79.jpg`, description: "", category: "鸡肉" },
    { id: "80", name: "香酥鸡", price: 5.50, imageLink: `${path}80.jpg`, description: "", category: "鸡肉" },
    { id: "81", name: "酱汁鸡", price: 5.50, imageLink: `${path}81.jpg`, description: "", category: "鸡肉" },
    { id: "82", name: "双冬鸡片", price: 5.00, imageLink: `${path}82.jpg`, description: "", category: "鸡肉" },
    { id: "83", name: "菠萝鸡片", price: 5.00, imageLink: `${path}83.jpg`, description: "", category: "鸡肉" },
    { id: "84", name: "咖喱鸡片", price: 5.00, imageLink: `${path}84.jpg`, description: "", category: "鸡肉" },
    { id: "85", name: "炸鸡丁", price: 5.00, imageLink: `${path}85.jpg`, description: "", category: "鸡肉" },
    { id: "85A", name: "面包鸡", price: 5.50, imageLink: `${path}85A.jpg`, description: "", category: "鸡肉" },
    { id: "85B", name: "芝麻鸡", price: 6.00, imageLink: `${path}85B.jpg`, description: "", category: "鸡肉" },
    { id: "86", name: "炒三丁", price: 6.00, imageLink: `${path}86.jpg`, description: "", category: "鸡肉" },
    { id: "87", name: "松子鸡巢", price: 5.50, imageLink: `${path}87.jpg`, description: "", category: "鸡肉" },
    { id: "88", name: "铁板鸡片", price: 5.50, imageLink: `${path}88.jpg`, description: "", category: "鸡肉" },
    { id: "88A", name: "铁土豆鸡", price: 5.50, imageLink: `${path}88A.jpg`, description: "", category: "鸡肉" },
    { id: "88B", name: "串肉 (牛肉 & 鸡肉)", price: 6.00, imageLink: `${path}88B.jpg`, description: "", category: "鸡肉" },
    { id: "88C", name: "串牛肉", price: 6.00, imageLink: `${path}88C.jpg`, description: "", category: "鸡肉" },
    { id: "88D", name: "串鸡肉", price: 6.00, imageLink: `${path}88D.jpg`, description: "", category: "鸡肉" },
    { id: "88E", name: "泰式肉", price: 6.00, imageLink: `${path}88E.jpg`, description: "", category: "鸡肉" },
    { id: "88F", name: "沙茶肉", price: 6.00, imageLink: `${path}88F.jpg`, description: "", category: "鸡肉" },
    { id: "88G", name: "肉堡", price: 6.00, imageLink: `${path}88G.jpg`, description: "", category: "鸡肉" },
    { id: "89", name: "菠萝鸭", price: 6.50, imageLink: `${path}89.jpg`, description: "", category: "鸭肉" },
    { id: "89A", name: "柠檬鸭", price: 6.50, imageLink: `${path}89A.jpg`, description: "", category: "鸭肉" },
    { id: "89B", name: "桔子鸭", price: 6.50, imageLink: `${path}89B.jpg`, description: "", category: "鸭肉" },
    { id: "90", name: "香酥鸭", price: 6.50, imageLink: `${path}90.jpg`, description: "", category: "鸭肉" },
    { id: "91", name: "双冬鸭", price: 6.50, imageLink: `${path}91.jpg`, description: "", category: "鸭肉" },
    { id: "91A", name: "糖醋鸭", price: 6.50, imageLink: `${path}91A.jpg`, description: "", category: "鸭肉" },
    { id: "91B", name: "辣子鸭", price: 6.50, imageLink: `${path}91B.jpg`, description: "", category: "鸭肉" },
    { id: "92", name: "北京鸭", price: 9.00, imageLink: `${path}92.jpg`, description: "", category: "鸭肉" },
    { id: "92A", name: "北京全鸭", price: 40.00, imageLink: `${path}92A.jpg`, description: "", category: "鸭肉" },
    { id: "92B", name: "铁板鸭", price: 7.00, imageLink: `${path}92B.jpg`, description: "", category: "鸭肉" },
    { id: "93", name: "咕唠肉", price: 5.00, imageLink: `${path}93.jpg`, description: "", category: "猪肉" },
    { id: "94", name: "双冬猪肉", price: 5.00, imageLink: `${path}94.jpg`, description: "", category: "猪肉" },
    { id: "95", name: "豆芽猪肉", price: 5.00, imageLink: `${path}95.jpg`, description: "", category: "猪肉" },
    { id: "96", name: "辣子猪肉", price: 5.00, imageLink: `${path}96.jpg`, description: "", category: "猪肉" },
    { id: "96A", name: "宫爆猪肉", price: 5.00, imageLink: `${path}96A.jpg`, description: "", category: "猪肉" },
    { id: "96B", name: "榨菜猪肉", price: 5.00, imageLink: `${path}96B.jpg`, description: "", category: "猪肉" },
    { id: "97", name: "炸排骨", price: 5.00, imageLink: `${path}97.jpg`, description: "", category: "猪肉" },
    { id: "97A", name: "铁板猪肉", price: 5.50, imageLink: `${path}97A.jpg`, description: "", category: "猪肉" },
    { id: "97B", name: "土豆猪肉", price: 5.50, imageLink: `${path}97B.jpg`, description: "", category: "猪肉" },
    { id: "97C", name: "糖醋排骨", price: 5.50, imageLink: `${path}97C.jpg`, description: "", category: "猪肉" },
    { id: "97D", name: "椒盐排骨", price: 5.50, imageLink: `${path}97D.jpg`, description: "", category: "猪肉" },
    { id: "98", name: "蚝油牛肉", price: 5.50, imageLink: `${path}98.jpg`, description: "", category: "牛肉" },
    { id: "98A", name: "糖醋牛肉", price: 5.50, imageLink: `${path}98A.jpg`, description: "", category: "牛肉" },
    { id: "99", name: "双冬牛肉", price: 5.50, imageLink: `${path}99.jpg`, description: "", category: "牛肉" },
    { id: "100", name: "姜葱牛肉", price: 5.50, imageLink: `${path}100.jpg`, description: "", category: "牛肉" },
    { id: "101", name: "咖喱牛肉", price: 5.50, imageLink: `${path}101.jpg`, description: "", category: "牛肉" },
    { id: "102", name: "什锦牛肉", price: 5.50, imageLink: `${path}102.jpg`, description: "", category: "牛肉" },
    { id: "103", name: "豆芽牛肉", price: 5.50, imageLink: `${path}103.jpg`, description: "", category: "牛肉" },
    { id: "104", name: "辣子牛肉", price: 5.50, imageLink: `${path}104.jpg`, description: "", category: "牛肉" },
    { id: "105", name: "干烧牛肉", price: 5.50, imageLink: `${path}105.jpg`, description: "", category: "牛肉" },
    { id: "106", name: "铁板牛肉", price: 6.00, imageLink: `${path}106.jpg`, description: "", category: "牛肉" },
    { id: "107", name: "八宝巢", price: 6.50, imageLink: `${path}107.jpg`, description: "", category: "牛肉" },
    { id: "107A", name: "土豆牛肉", price: 6.00, imageLink: `${path}107A.jpg`, description: "", category: "牛肉" },
    { id: "107B", name: "铁板什肉", price: 6.00, imageLink: `${path}107B.jpg`, description: "", category: "牛肉" },
    { id: "108", name: "炒双冬", price: 3.50, imageLink: `${path}108.jpg`, description: "", category: "蔬菜" },
    { id: "109", name: "炒素菜", price: 3.50, imageLink: `${path}109.jpg`, description: "", category: "蔬菜" },
    { id: "109A", name: "炒辣菜", price: 3.50, imageLink: `${path}109A.jpg`, description: "", category: "蔬菜" },
    { id: "109B", name: "贴菜", price: 3.50, imageLink: `${path}109B.jpg`, description: "", category: "蔬菜" },
    { id: "110", name: "炒豆芽", price: 3.50, imageLink: `${path}110.jpg`, description: "", category: "蔬菜" },
    { id: "111", name: "辣子茄", price: 3.50, imageLink: `${path}111.jpg`, description: "", category: "蔬菜" },
    { id: "111A", name: "铁板土豆", price: 4.00, imageLink: `${path}111A.jpg`, description: "", category: "蔬菜" },
    { id: "111B", name: "烤土豆", price: 4.00, imageLink: `${path}111B.jpg`, description: "", category: "蔬菜" },
    { id: "112", name: "蟹肉炒蛋", price: 3.50, imageLink: `${path}112.jpg`, description: "", category: "蛋" },
    { id: "113", name: "虾仁炒蛋", price: 3.50, imageLink: `${path}113.jpg`, description: "", category: "蛋" },
    { id: "114", name: "火腿炒蛋", price: 3.50, imageLink: `${path}114.jpg`, description: "", category: "蛋" },
    { id: "114A", name: "葱炒蛋", price: 3.50, imageLink: `${path}114A.jpg`, description: "", category: "蛋" },
    { id: "115", name: "双冬豆腐", price: 4.00, imageLink: `${path}115.jpg`, description: "", category: "豆腐" },
    { id: "116", name: "辣子豆腐", price: 4.00, imageLink: `${path}116.jpg`, description: "", category: "豆腐" },
    { id: "117", name: "铁板豆腐", price: 4.00, imageLink: `${path}117.jpg`, description: "", category: "豆腐" },
    { id: "118", name: "虾仁豆腐", price: 5.50, imageLink: `${path}118.jpg`, description: "", category: "豆腐" },
    { id: "118A", name: "牛肉豆腐", price: 5.50, imageLink: `${path}118A.jpg`, description: "", category: "豆腐" },
    { id: "118C", name: "糖醋豆腐", price: 3.50, imageLink: `${path}118C.jpg`, description: "", category: "豆腐" },
    { id: "118D", name: "豆腐堡", price: 6.00, imageLink: `${path}118D.jpg`, description: "", category: "豆腐" },
    { id: "119", name: "炸水果", price: 3.00, imageLink: `${path}119.jpg`, description: "", category: "甜点" },
    { id: "119A", name: "炸香蕉", price: 3.00, imageLink: `${path}119A.jpg`, description: "", category: "甜点" },
    { id: "119B", name: "炸苹果", price: 3.00, imageLink: `${path}119B.jpg`, description: "", category: "甜点" },
    { id: "119C", name: "炸菠萝", price: 3.00, imageLink: `${path}119C.jpg`, description: "", category: "甜点" },
    { id: "120", name: "炸水果加冰", price: 4.00, imageLink: `${path}120.jpg`, description: "", category: "甜点" },
    { id: "121", name: "水果拔丝", price: 3.50, imageLink: `${path}121.jpg`, description: "", category: "甜点" },
    { id: "122", name: "水果拔丝加冰", price: 4.50, imageLink: `${path}122.jpg`, description: "", category: "甜点" },
    { id: "123", name: "炸椰子", price: 3.00, imageLink: `${path}123.jpg`, description: "", category: "甜点" },
    { id: "123A", name: "蒸椰子", price: 3.00, imageLink: `${path}123A.jpg`, description: "", category: "甜点" },
    { id: "123B", name: "蒸椰子加冰", price: 4.00, imageLink: `${path}123B.jpg`, description: "", category: "甜点" },
    { id: "124", name: "炸椰子加冰", price: 4.00, imageLink: `${path}124.jpg`, description: "", category: "甜点" },
    { id: "125", name: "炸Nutella", price: 3.00, imageLink: `${path}125.jpg`, description: "", category: "甜点" },
    { id: "125A", name: "炸Nutella 加冰", price: 4.00, imageLink: `${path}125A.jpg`, description: "", category: "甜点" },
    { id: "125B", name: "蒸Nutella", price: 3.00, imageLink: `${path}125B.jpg`, description: "", category: "甜点" },
    { id: "125C", name: "蒸Nutella 加冰", price: 4.00, imageLink: `${path}125C.jpg`, description: "", category: "甜点" },
    { id: "126", name: "中国水果", price: 3.00, imageLink: `${path}126.jpg`, description: "", category: "甜点" },
    { id: "127", name: "中国水果加冰", price: 4.00, imageLink: `${path}127.jpg`, description: "", category: "甜点" },
    { id: "128", name: "炸白冰", price: 3.00, imageLink: `${path}128.jpg`, description: "", category: "甜点" },
    { id: "128A", name: "炸巧克力冰", price: 3.00, imageLink: `${path}128A.jpg`, description: "", category: "甜点" },
    { id: "129", name: "什锦冰", price: 3.00, imageLink: `${path}129.jpg`, description: "", category: "甜点" },
    { id: "130", name: "白Tartufo", price: 3.50, imageLink: `${path}130.jpg`, description: "", category: "甜点" },
    { id: "130A", name: "黑Tartufo", price: 3.50, imageLink: `${path}130A.jpg`, description: "", category: "甜点" },
    { id: "130B", name: "Tartufo 加咖啡", price: 4.50, imageLink: `${path}130B.jpg`, description: "", category: "甜点" },
    { id: "130C", name: "Tartufo 加威士忌", price: 4.50, imageLink: `${path}130C.jpg`, description: "", category: "甜点" },
    { id: "130D", name: "Tiramisù", price: 3.50, imageLink: `${path}130D.jpg`, description: "", category: "甜点" },
    { id: "131", name: "柠檬冰", price: 4.50, imageLink: `${path}131.jpg`, description: "", category: "甜点" },
    { id: "131A", name: "椰子冰", price: 4.50, imageLink: `${path}131A.jpg`, description: "", category: "甜点" },
    { id: "132", name: "蛋糕", price: 3.80, imageLink: `${path}132.jpg`, description: "", category: "甜点" },
    { id: "133", name: "炸牛奶", price: 3.00, imageLink: `${path}133.jpg`, description: "", category: "甜点" },
    { id: "133A", name: "炸牛奶加冰", price: 4.00, imageLink: `${path}133A.jpg`, description: "", category: "甜点" },
    { id: "133B", name: "牛奶拔丝", price: 3.50, imageLink: `${path}133B.jpg`, description: "", category: "甜点" },
    { id: "134", name: "鲜菠萝", price: 3.50, imageLink: `${path}134.jpg`, description: "", category: "甜点" },
    { id: "135", name: "草莓加奶油", price: 3.50, imageLink: `${path}135.jpg`, description: "", category: "甜点" },
    { id: "137", name: "Sushi 甜点", price: 4.00, imageLink: `${path}137.jpg`, description: "", category: "甜点" },
    { id: "139", name: "块状甜点", price: 4.00, imageLink: `${path}139.jpg`, description: "", category: "甜点" },
    { id: "140", name: "泡泡冰", price: 3.50, imageLink: `${path}140.jpg`, description: "", category: "甜点" },
    { id: "141", name: "熟奶油", price: 3.50, imageLink: `${path}141.jpg`, description: "", category: "甜点" },  
    { id: "pinot_grigio", name: 'Pinot grigio', price: 7.90, imageLink: `${path}pinot_grigio.jpg`, description:"", category:"酒水" },
    { id: "chardonnay", name: 'Chardonnay', price: 7.90, imageLink: `${path}chardonnay.jpg`, description:"", category:"酒水" },
    { id: "verdicchio", name: 'Verdicchio', price: 8.90, imageLink: `${path}verdicchio.jpg`, description:"", category:"酒水" },
    { id: "vernaccia_di_san_gimignano", name: 'Vernaccia di san gimignano', price: 8.90, imageLink: `${path}vernaccia_di_san_gimignano.jpg`, description:"", category:"酒水" },
    { id: "mateus_rose", name: 'Mateus rose', price: 7.90, imageLink: `${path}mateus_rose.jpg`, description:"", category:"酒水" },
    { id: "lancers_rose", name: 'Lancers rose', price: 7.90, imageLink: `${path}lancers_rose.jpg`, description:"", category:"酒水" },
    { id: "santa_cristina", name: 'Santa cristina', price: 12.90, imageLink: `${path}santa_cristina.jpg`, description:"", category:"酒水" },
    { id: "chianti_rosso", name: 'Chianti rosso', price: 7.90, imageLink: `${path}chianti_rosso.jpg`, description:"", category:"酒水" },
    { id: "vino_della_casa_1l", name: 'Vino della casa 1l (Bianco/Rosso)', price: 6.00, imageLink: `${path}vino_della_casa_1l.jpg`, description:"", category:"酒水" },
    { id: "vino_della_casa_0.5l", name: 'Vino della casa 0.5l (Bianco/Rosso)', price: 3.50, imageLink: `${path}vino_della_casa_0.5l.jpg`, description:"", category:"酒水" },
    { id: "vino_della_casa_0.25L", name: 'Vino della casa 0.25L (Bianco/Rosso)', price: 2.00, imageLink: `${path}vino_della_casa_0.25L.jpg`, description:"", category:"酒水" },
    { id: "birra_moretti_66cl", name: 'Birra Moretti 66cl', price: 3.50, imageLink: `${path}birra_moretti_66cl.jpg`, description:"", category:"酒水" },
    { id: "birra_cinese_media", name: 'Birra cinese media', price: 4.00, imageLink: `${path}birra_cinese_media.jpg`, description:"", category:"酒水" },
    { id: "birra_tennents", name: 'Birra Tennent’s', price: 3.50, imageLink: `${path}birra_tennents.jpg`, description:"", category:"酒水" },
    { id: "birra_becks_33cl", name: 'Birra Becks 33cl', price: 2.50, imageLink: `${path}birra_becks_33cl.jpg`, description:"", category:"酒水" },
    { id: "coca_cola_33cl", name: 'Coca cola 33 cl /o Coca cola zero 33cl', price: 2.00, imageLink: `${path}coca_cola_33cl.jpg`, description:"", category:"酒水" },
    { id: "fanta_33cl", name: 'Fanta 33cl', price: 2.00, imageLink: `${path}fanta_33cl.jpg`, description:"", category:"酒水" },
    { id: "sprite_33cl", name: 'Sprite 33cl', price: 2.00, imageLink: `${path}sprite_33cl.jpg`, description:"", category:"酒水" },
    { id: "coca_cola_grande", name: 'Coca cola grande', price: 4.50, imageLink: `${path}coca_cola_grande.jpg`, description:"", category:"酒水" },
    { id: "the_freddo_limone_pesca_33cl", name: 'The freddo limone / pesca 33cl', price: 2.00, imageLink: `${path}the_freddo_limone_pesca_33cl.jpg`, description:"", category:"酒水" },
    { id: "the_caldo_gelsomino_verde", name: 'The caldo gelsomino / verde', price: 2.00, imageLink: `${path}the_caldo_gelsomino_verde.jpg`, description:"", category:"酒水" },
    { id: "acqua_minerale_1l", name: 'Acqua minerale 1l', price: 2.00, imageLink: `${path}acqua_minerale_1l.jpg`, description:"", category:"酒水" },
    { id: "acqua_minerale_0.5l", name: 'Acqua minerale 0.5l', price: 1.00, imageLink: `${path}acqua_minerale_0.5l.jpg`, description:"", category:"酒水" },
    { id: "liquore_di_fragola", name: 'Liquore di fragola / mela verde / Baileys', price: 2.10, imageLink: `${path}liquore_di_fragola.jpg`, description:"", category:"酒水" },
    { id: "limoncello_amaro_sambuca", name: 'Limoncello / amaro / sambuca', price: 2.10, imageLink: `${path}limoncello_amaro_sambuca.jpg`, description:"", category:"酒水" },
    { id: "grappa_italiana_whiskey", name: 'Grappa italiana, whiskey', price: 2.10, imageLink: `${path}grappa_italiana_whiskey.jpg`, description:"", category:"酒水" },
    { id: "ponce_livornese", name: 'Ponce Livornese', price: 3.50, imageLink: `${path}ponce_livornese.jpg`, description:"", category:"酒水" },
    { id: "liquore_cinese", name: 'Liquore cinese (bambù, riso, rosa, ginseng, prugna)', price: 1.50, imageLink: `${path}liquore_cinese.jpg`, description:"", category:"酒水" },
    { id: "amaro_cinese_alle_cinque_erbe", name: 'Amaro cinese alle cinque erbe', price: 1.50, imageLink: `${path}amaro_cinese_alle_cinque_erbe.jpg`, description:"", category:"酒水" },
    { id: "sake", name: 'Sake', price: 2.00, imageLink: `${path}sake.jpg`, description:"", category:"酒水" },
    { id: "caffe", name: 'Caffè', price: 1.20, imageLink: `${path}caffe.jpg`, description:"", category:"酒水" },
    { id: "caffe_macchiato", name: 'Caffè macchiato', price: 1.40, imageLink: `${path}caffe_macchiato.jpg`, description:"", category:"酒水" },
    { id: "caffe_corretto", name: 'Caffè corretto', price: 1.60, imageLink: `${path}caffe_corretto.jpg`, description:"", category:"酒水" },
    { id: "caffe_d_orzo", name: 'Caffè d’orzo', price: 1.60, imageLink: `${path}caffe_d_orzo.jpg`, description:"", category:"酒水" },
    { id: "caffe_decaffeinato", name: 'Caffè decaffeinato', price: 1.60, imageLink: `${path}caffe_decaffeinato.jpg`, description:"", category:"酒水" },
    { id: "caffe_ginseng", name: 'Caffè GinSeng', price: 1.60, imageLink: `${path}caffe_ginseng.jpg`, description:"", category:"酒水" },
    { id: "cappuccino", name: 'Cappuccino', price: 1.80, imageLink: `${path}cappuccino.jpg`, description:"", category:"酒水" },
                
]

export default MenuCn;