const MenuCn=[
    { id: "0", name: "炸面包", price: 1.00, imageLink: "src/assets/menu/0.jpg", description: "", category: "前餐" },
    { id: "0A", name: "蒸面包", price: 1.00, imageLink: "src/assets/menu/0A.jpg", description: "", category: "前餐" },
    { id: "1", name: "春卷", price: 1.50, imageLink: "src/assets/menu/1.jpg", description: "", category: "前餐" },
    { id: "1A", name: "海鲜春卷", price: 1.80, imageLink: "src/assets/menu/1A.jpg", description: "", category: "前餐" },
    { id: "2", name: "炸云吞", price: 1.60, imageLink: "src/assets/menu/2.jpg", description: "", category: "前餐" },
    { id: "3", name: "虾片", price: 1.50, imageLink: "src/assets/menu/3.jpg", description: "", category: "前餐" },
    { id: "4", name: "炸海菜", price: 3.00, imageLink: "src/assets/menu/4.jpg", description: "", category: "前餐" },
    { id: "5", name: "土豆饼", price: 2.00, imageLink: "src/assets/menu/5.jpg", description: "", category: "前餐" },
    { id: "5A", name: "番茄面包", price: 2.60, imageLink: "src/assets/menu/5A.jpg", description: "", category: "前餐" },
    { id: "6", name: "炸薯条", price: 2.50, imageLink: "src/assets/menu/6.jpg", description: "", category: "前餐" },
    { id: "7", name: "土司", price: 2.50, imageLink: "src/assets/menu/7.jpg", description: "", category: "前餐" },
    { id: "8", name: "葱油饼", price: 3.00, imageLink: "src/assets/menu/8.jpg", description: "", category: "前餐" },
    { id: "9", name: "肉饺", price: 3.20, imageLink: "src/assets/menu/9.jpg", description: "", category: "前餐" },
    { id: "10", name: "菜饺", price: 3.40, imageLink: "src/assets/menu/10.jpg", description: "", category: "前餐" },
    { id: "11", name: "锅贴", price: 3.60, imageLink: "src/assets/menu/11.jpg", description: "", category: "前餐" },
    { id: "12", name: "烧卖", price: 3.80, imageLink: "src/assets/menu/12.jpg", description: "", category: "前餐" },
    { id: "12A", name: "水晶饺", price: 3.80, imageLink: "src/assets/menu/12A.jpg", description: "", category: "前餐" },
    { id: "12B", name: "什锦饺子 (请看 9,10,12号)", price: 3.80, imageLink: "src/assets/menu/12B.jpg", description: "", category: "前餐" },
    { id: "12C", name: "悦来饺", price: 3.80, imageLink: "src/assets/menu/12C.jpg", description: "", category: "前餐" },
    { id: "13", name: "什锦热盘 (请看 1,2,3,5,7 号)", price: 4.00, imageLink: "src/assets/menu/13.jpg", description: "", category: "前餐" },
    { id: "14", name: "炸蔬菜", price: 3.00, imageLink: "src/assets/menu/14.jpg", description: "", category: "前餐" },
    { id: "14A", name: "芝麻球", price: 3.50, imageLink: "src/assets/menu/14A.jpg", description: "", category: "前餐" },
    { id: "14B", name: "炸洋葱圈", price: 3.00, imageLink: "src/assets/menu/14B.jpg", description: "", category: "前餐" },
    { id: "14C", name: "毛豆夹", price: 3.50, imageLink: "src/assets/menu/14C.jpg", description: "", category: "前餐" },
    { id: "15", name: "海带沙拉", price: 3.00, imageLink: "src/assets/menu/15.jpg", description: "", category: "沙拉菜" },
    { id: "16", name: "鸡肉肉沙拉", price: 3.50, imageLink: "src/assets/menu/16.jpg", description: "", category: "沙拉菜" },
    { id: "17", name: "虾沙拉", price: 3.50, imageLink: "src/assets/menu/17.jpg", description: "", category: "沙拉菜" },
    { id: "17A", name: "蟹肉沙拉", price: 3.50, imageLink: "src/assets/menu/17A.jpg", description: "", category: "沙拉菜" },
    { id: "17B", name: "什锦沙拉", price: 3.00, imageLink: "src/assets/menu/17B.jpg", description: "", category: "沙拉菜" },
    { id: "17C", name: "特酱沙拉", price: 4.00, imageLink: "src/assets/menu/17C.jpg", description: "", category: "沙拉菜" },
    { id: "17D", name: "海鲜沙拉", price: 6.00, imageLink: "src/assets/menu/17D.jpg", description: "", category: "沙拉菜" },
    { id: "17E", name: "半虾蟹沙拉", price: 4.00, imageLink: "src/assets/menu/17E.jpg", description: "", category: "沙拉菜" },
    { id: "18", name: "幸运汤", price: 3.00, imageLink: "src/assets/menu/18.jpg", description: "", category: "汤" },
    { id: "19", name: "云吞汤", price: 3.00, imageLink: "src/assets/menu/19.jpg", description: "", category: "汤" },
    { id: "19A", name: "悦来汤", price: 3.50, imageLink: "src/assets/menu/19A.jpg", description: "", category: "汤" },
    { id: "20", name: "双冬鸡汤", price: 3.00, imageLink: "src/assets/menu/20.jpg", description: "", category: "汤" },
    { id: "21", name: "酸辣汤", price: 3.00, imageLink: "src/assets/menu/21.jpg", description: "", category: "汤" },
    { id: "22", name: "榨菜粉丝汤", price: 3.00, imageLink: "src/assets/menu/22.jpg", description: "", category: "汤" },
    { id: "23", name: "鸡肉肉玉米汤", price: 3.00, imageLink: "src/assets/menu/23.jpg", description: "", category: "汤" },
    { id: "24", name: "蟹肉芦笋汤", price: 3.50, imageLink: "src/assets/menu/24.jpg", description: "", category: "汤" },
    { id: "25A", name: "蔬菜汤", price: 3.00, imageLink: "src/assets/menu/25A.jpg", description: "", category: "汤" },
    { id: "25B", name: "味噌汤", price: 3.00, imageLink: "src/assets/menu/25B.jpg", description: "", category: "汤" },
    { id: "25C", name: "海鲜汤", price: 3.80, imageLink: "src/assets/menu/25C.jpg", description: "", category: "汤" },
    { id: "25D", name: "泰式虾汤", price: 3.80, imageLink: "src/assets/menu/25D.jpg", description: "", category: "汤" },
    { id: "25E", name: "泰式鸡汤", price: 3.80, imageLink: "src/assets/menu/25E.jpg", description: "", category: "汤" },
    { id: "26", name: "素菜炒面", price: 3.50, imageLink: "src/assets/menu/26.jpg", description: "", category: "饭面" },
    { id: "26A", name: "素炒乌冬", price: 4.00, imageLink: "src/assets/menu/26A.jpg", description: "", category: "饭面" },
    { id: "26B", name: "海炒乌冬", price: 5.50, imageLink: "src/assets/menu/26B.jpg", description: "", category: "饭面" },
    { id: "26C", name: "海鲜汤面", price: 6.00, imageLink: "src/assets/menu/26C.jpg", description: "", category: "饭面" },
    { id: "26D", name: "肉汤面", price: 6.00, imageLink: "src/assets/menu/26D.jpg", description: "", category: "饭面" },
    { id: "27", name: "虾仁炒面", price: 4.20, imageLink: "src/assets/menu/27.jpg", description: "", category: "饭面" },
    { id: "28", name: "铁板素面", price: 4.00, imageLink: "src/assets/menu/28.jpg", description: "", category: "饭面" },
    { id: "28A", name: "担担面", price: 4.00, imageLink: "src/assets/menu/28A.jpg", description: "", category: "饭面" },
    { id: "28B", name: "铁板肉面", price: 4.50, imageLink: "src/assets/menu/28B.jpg", description: "", category: "饭面" },
    { id: "28C", name: "担担饭", price: 4.00, imageLink: "src/assets/menu/28C.jpg", description: "", category: "饭面" },
    { id: "29", name: "海鲜面", price: 4.90, imageLink: "src/assets/menu/29.jpg", description: "", category: "饭面" },
    { id: "29A", name: "海鲜粉丝", price: 4.90, imageLink: "src/assets/menu/29A.jpg", description: "", category: "饭面" },
    { id: "29B", name: "海鲜粉干", price: 4.90, imageLink: "src/assets/menu/29B.jpg", description: "", category: "饭面" },
    { id: "30", name: "素菜炸面", price: 3.50, imageLink: "src/assets/menu/30.jpg", description: "", category: "饭面" },
    { id: "30A", name: "海鲜炸面", price: 4.90, imageLink: "src/assets/menu/30A.jpg", description: "", category: "饭面" },
    { id: "31", name: "素菜粉干", price: 3.50, imageLink: "src/assets/menu/31.jpg", description: "", category: "饭面" },
    { id: "31A", name: "海鲜炒粉干", price: 4.90, imageLink: "src/assets/menu/31A.jpg", description: "", category: "饭面" },
    { id: "31B", name: "虾仁粉干", price: 4.20, imageLink: "src/assets/menu/31B.jpg", description: "", category: "饭面" },
    { id: "32", name: "肉粉干", price: 4.00, imageLink: "src/assets/menu/32.jpg", description: "", category: "饭面" },
    { id: "33", name: "咖喱粉干", price: 3.50, imageLink: "src/assets/menu/33.jpg", description: "", category: "饭面" },
    { id: "34", name: "肉末粉丝", price: 4.00, imageLink: "src/assets/menu/34.jpg", description: "", category: "饭面" },
    { id: "35", name: "素菜粉丝", price: 3.50, imageLink: "src/assets/menu/35.jpg", description: "", category: "饭面" },
    { id: "35A", name: "虾仁粉丝", price: 4.20, imageLink: "src/assets/menu/35A.jpg", description: "", category: "饭面" },
    { id: "36", name: "素菜年糕", price: 3.80, imageLink: "src/assets/menu/36.jpg", description: "", category: "饭面" },
    { id: "36A", name: "海鲜年糕", price: 5.00, imageLink: "src/assets/menu/36A.jpg", description: "", category: "饭面" },
    { id: "36B", name: "肉年糕", price: 4.30, imageLink: "src/assets/menu/36B.jpg", description: "", category: "饭面" },
    { id: "37", name: "虾仁炒饭", price: 4.20, imageLink: "src/assets/menu/37.jpg", description: "", category: "饭面" },
    { id: "38", name: "素菜炒饭", price: 3.50, imageLink: "src/assets/menu/38.jpg", description: "", category: "饭面" },
    { id: "39", name: "广东饭", price: 3.50, imageLink: "src/assets/menu/39.jpg", description: "", category: "饭面" },
    { id: "39A", name: "鸡肉饭", price: 3.50, imageLink: "src/assets/menu/39A.jpg", description: "", category: "饭面" },
    { id: "40", name: "咖喱饭", price: 3.50, imageLink: "src/assets/menu/40.jpg", description: "", category: "饭面" },
    { id: "41", name: "菠萝炒饭", price: 4.00, imageLink: "src/assets/menu/41.jpg", description: "", category: "饭面" },
    { id: "42", name: "白饭", price: 1.50, imageLink: "src/assets/menu/42.jpg", description: "", category: "饭面" },
    { id: "42A", name: "什锦肉锅巴", price: 4.50, imageLink: "src/assets/menu/42A.jpg", description: "", category: "饭面" },
    { id: "42B", name: "海鲜锅巴", price: 4.90, imageLink: "src/assets/menu/42B.jpg", description: "", category: "饭面" },
    { id: "42C", name: "番茄面", price: 3.50, imageLink: "src/assets/menu/42C.jpg", description: "", category: "饭面" },
    { id: "42D", name: "Ragù面", price: 3.50, imageLink: "src/assets/menu/42D.jpg", description: "", category: "饭面" },
    { id: "42E", name: "海鲜饭", price: 4.90, imageLink: "src/assets/menu/42E.jpg", description: "", category: "饭面" },
    { id: "42F", name: "炒饭", price: 5.00, imageLink: "src/assets/menu/42F.jpg", description: "", category: "饭面" },
    { id: "42G", name: "炒面", price: 5.00, imageLink: "src/assets/menu/42G.jpg", description: "", category: "饭面" },
    { id: "42H", name: "泰式炒面", price: 4.50, imageLink: "src/assets/menu/42H.jpg", description: "", category: "饭面" },
    { id: "42L", name: "泰式炒饭", price: 4.50, imageLink: "src/assets/menu/42L.jpg", description: "", category: "饭面" },
    { id: "43", name: "双冬虾仁", price: 6.00, imageLink: "src/assets/menu/43.jpg", description: "", category: "海鲜" },
    { id: "44", name: "五彩虾仁", price: 6.00, imageLink: "src/assets/menu/44.jpg", description: "", category: "海鲜" },
    { id: "45", name: "青豆虾仁", price: 6.00, imageLink: "src/assets/menu/45.jpg", description: "", category: "海鲜" },
    { id: "45A", name: "腰果虾仁", price: 6.00, imageLink: "src/assets/menu/45A.jpg", description: "", category: "海鲜" },
    { id: "46", name: "咖喱虾仁", price: 6.00, imageLink: "src/assets/menu/46.jpg", description: "", category: "海鲜" },
    { id: "47", name: "辣子虾仁", price: 6.00, imageLink: "src/assets/menu/47.jpg", description: "", category: "海鲜" },
    { id: "47A", name: "宫爆虾仁", price: 6.00, imageLink: "src/assets/menu/47A.jpg", description: "", category: "海鲜" },
    { id: "48", name: "糖醋虾仁", price: 6.00, imageLink: "src/assets/menu/48.jpg", description: "", category: "海鲜" },
    { id: "48A", name: "糖醋虾仁 (不炸)", price: 6.00, imageLink: "src/assets/menu/48A.jpg", description: "", category: "海鲜" },
    { id: "49", name: "苹果虾仁", price: 6.00, imageLink: "src/assets/menu/49.jpg", description: "", category: "海鲜" },
    { id: "49A", name: "桔子虾仁", price: 6.00, imageLink: "src/assets/menu/49A.jpg", description: "", category: "海鲜" },
    { id: "49B", name: "柠檬虾仁", price: 6.00, imageLink: "src/assets/menu/49B.jpg", description: "", category: "海鲜" },
    { id: "49C", name: "菠萝虾仁", price: 6.00, imageLink: "src/assets/menu/49C.jpg", description: "", category: "海鲜" },
    { id: "50", name: "炸虾仁", price: 6.00, imageLink: "src/assets/menu/50.jpg", description: "", category: "海鲜" },
    { id: "50A", name: "芝麻炸虾仁", price: 6.50, imageLink: "src/assets/menu/50A.jpg", description: "", category: "海鲜" },
    { id: "51", name: "椒盐虾仁", price: 6.50, imageLink: "src/assets/menu/51.jpg", description: "", category: "海鲜" },
    { id: "52", name: "铁板虾仁", price: 6.50, imageLink: "src/assets/menu/52.jpg", description: "", category: "海鲜" },
    { id: "53A", name: "虾巢", price: 6.50, imageLink: "src/assets/menu/53A.jpg", description: "", category: "海鲜" },
    { id: "53B", name: "海鲜巢", price: 6.50, imageLink: "src/assets/menu/53B.jpg", description: "", category: "海鲜" },
    { id: "53C", name: "串海鲜", price: 7.00, imageLink: "src/assets/menu/53C.jpg", description: "", category: "海鲜" },
    { id: "53D", name: "串虾", price: 7.00, imageLink: "src/assets/menu/53D.jpg", description: "", category: "海鲜" },
    { id: "53E", name: "串鱿鱼", price: 7.00, imageLink: "src/assets/menu/53E.jpg", description: "", category: "海鲜" },
    { id: "53F", name: "泰式海鲜", price: 7.00, imageLink: "src/assets/menu/53F.jpg", description: "", category: "海鲜" },
    { id: "53G", name: "沙茶海鲜", price: 7.00, imageLink: "src/assets/menu/53G.jpg", description: "", category: "海鲜" },
    { id: "54", name: "辣子大虾", price: 6.50, imageLink: "src/assets/menu/54.jpg", description: "", category: "海鲜" },
    { id: "55", name: "清蒸大虾", price: 6.50, imageLink: "src/assets/menu/55.jpg", description: "", category: "海鲜" },
    { id: "56", name: "红烧大虾", price: 6.50, imageLink: "src/assets/menu/56.jpg", description: "", category: "海鲜" },
    { id: "57", name: "芝麻大虾", price: 6.50, imageLink: "src/assets/menu/57.jpg", description: "", category: "海鲜" },
    { id: "57A", name: "凤尾虾", price: 7.00, imageLink: "src/assets/menu/57A.jpg", description: "", category: "海鲜" },
    { id: "58", name: "烤大虾 (6 只)", price: 9.00, imageLink: "src/assets/menu/58.jpg", description: "", category: "海鲜" },
    { id: "59", name: "铁板大虾", price: 9.00, imageLink: "src/assets/menu/59.jpg", description: "", category: "海鲜" },
    { id: "59A", name: "椒盐大虾", price: 9.00, imageLink: "src/assets/menu/59A.jpg", description: "", category: "海鲜" },
    { id: "59B", name: "火烧大虾", price: 9.00, imageLink: "src/assets/menu/59B.jpg", description: "", category: "海鲜" },
    { id: "60", name: "铁板海鲜", price: 7.00, imageLink: "src/assets/menu/60.jpg", description: "", category: "海鲜" },
    { id: "61", name: "柠檬鱼片", price: 6.00, imageLink: "src/assets/menu/61.jpg", description: "", category: "海鲜" },
    { id: "62", name: "清蒸鱼片", price: 6.00, imageLink: "src/assets/menu/62.jpg", description: "", category: "海鲜" },
    { id: "63", name: "烤全鱼", price: 10.00, imageLink: "src/assets/menu/63.jpg", description: "", category: "海鲜" },
    { id: "64", name: "清蒸全鱼", price: 10.00, imageLink: "src/assets/menu/64.jpg", description: "", category: "海鲜" },
    { id: "65", name: "红烧全鱼", price: 10.00, imageLink: "src/assets/menu/65.jpg", description: "", category: "海鲜" },
    { id: "66", name: "辣子鱿鱼", price: 6.00, imageLink: "src/assets/menu/66.jpg", description: "", category: "海鲜" },
    { id: "67", name: "糖醋鱿鱼", price: 6.00, imageLink: "src/assets/menu/67.jpg", description: "", category: "海鲜" },
    { id: "67A", name: "糖醋鱿鱼 (不炸)", price: 6.00, imageLink: "src/assets/menu/67A.jpg", description: "", category: "海鲜" },
    { id: "68", name: "什锦鱿鱼", price: 6.00, imageLink: "src/assets/menu/68.jpg", description: "", category: "海鲜" },
    { id: "68A", name: "铁板鱿鱼", price: 6.50, imageLink: "src/assets/menu/68A.jpg", description: "", category: "海鲜" },
    { id: "69", name: "炸田鸡", price: 7.50, imageLink: "src/assets/menu/69.jpg", description: "", category: "海鲜" },
    { id: "70", name: "铁板田鸡", price: 7.50, imageLink: "src/assets/menu/70.jpg", description: "", category: "海鲜" },
    { id: "71", name: "炸蟹钳 (5 只)", price: 6.50, imageLink: "src/assets/menu/71.jpg", description: "", category: "海鲜" },
    { id: "71A", name: "清蒸螃蟹", price: 9.00, imageLink: "src/assets/menu/71A.jpg", description: "", category: "海鲜" },
    { id: "71B", name: "红烧螃蟹", price: 9.00, imageLink: "src/assets/menu/71B.jpg", description: "", category: "海鲜" },
    { id: "71C", name: "椒盐螃蟹", price: 9.00, imageLink: "src/assets/menu/71C.jpg", description: "", category: "海鲜" },
    { id: "72", name: "炸海鲜", price: 6.00, imageLink: "src/assets/menu/72.jpg", description: "", category: "海鲜" },
    { id: "73", name: "海鲜砂锅", price: 7.00, imageLink: "src/assets/menu/73.jpg", description: "", category: "海鲜" },
    { id: "74", name: "糖醋鸡", price: 5.00, imageLink: "src/assets/menu/74.jpg", description: "", category: "鸡肉" },
    { id: "74A", name: "青椒鸡片", price: 5.00, imageLink: "src/assets/menu/74A.jpg", description: "", category: "鸡肉" },
    { id: "74B", name: "糖醋鸡 (不炸)", price: 5.00, imageLink: "src/assets/menu/74B.jpg", description: "", category: "鸡肉" },
    { id: "75", name: "柠檬鸡", price: 5.00, imageLink: "src/assets/menu/75.jpg", description: "", category: "鸡肉" },
    { id: "75A", name: "柠檬鸡(不炸)", price: 5.00, imageLink: "src/assets/menu/75A.jpg", description: "", category: "鸡肉" },
    { id: "75B", name: "芦笋鸡片", price: 5.00, imageLink: "src/assets/menu/75B.jpg", description: "", category: "鸡肉" },
    { id: "75C", name: "芹菜鸡片", price: 5.00, imageLink: "src/assets/menu/75C.jpg", description: "", category: "鸡肉" },
    { id: "76", name: "桔子鸡", price: 5.00, imageLink: "src/assets/menu/76.jpg", description: "", category: "鸡肉" },
    { id: "76A", name: "桔子鸡 (不炸)", price: 5.00, imageLink: "src/assets/menu/76A.jpg", description: "", category: "鸡肉" },
    { id: "77", name: "豆芽鸡片", price: 5.00, imageLink: "src/assets/menu/77.jpg", description: "", category: "鸡肉" },
    { id: "78", name: "杏仁鸡丁", price: 5.00, imageLink: "src/assets/menu/78.jpg", description: "", category: "鸡肉" },
    { id: "78A", name: "腰果鸡丁", price: 5.00, imageLink: "src/assets/menu/78A.jpg", description: "", category: "鸡肉" },
    { id: "79", name: "宫爆鸡丁", price: 5.00, imageLink: "src/assets/menu/79.jpg", description: "", category: "鸡肉" },
    { id: "80", name: "香酥鸡", price: 5.50, imageLink: "src/assets/menu/80.jpg", description: "", category: "鸡肉" },
    { id: "81", name: "酱汁鸡", price: 5.50, imageLink: "src/assets/menu/81.jpg", description: "", category: "鸡肉" },
    { id: "82", name: "双冬鸡片", price: 5.00, imageLink: "src/assets/menu/82.jpg", description: "", category: "鸡肉" },
    { id: "83", name: "菠萝鸡片", price: 5.00, imageLink: "src/assets/menu/83.jpg", description: "", category: "鸡肉" },
    { id: "84", name: "咖喱鸡片", price: 5.00, imageLink: "src/assets/menu/84.jpg", description: "", category: "鸡肉" },
    { id: "85", name: "炸鸡丁", price: 5.00, imageLink: "src/assets/menu/85.jpg", description: "", category: "鸡肉" },
    { id: "85A", name: "面包鸡", price: 5.50, imageLink: "src/assets/menu/85A.jpg", description: "", category: "鸡肉" },
    { id: "85B", name: "芝麻鸡", price: 6.00, imageLink: "src/assets/menu/85B.jpg", description: "", category: "鸡肉" },
    { id: "86", name: "炒三丁", price: 6.00, imageLink: "src/assets/menu/86.jpg", description: "", category: "鸡肉" },
    { id: "87", name: "松子鸡巢", price: 5.50, imageLink: "src/assets/menu/87.jpg", description: "", category: "鸡肉" },
    { id: "88", name: "铁板鸡片", price: 5.50, imageLink: "src/assets/menu/88.jpg", description: "", category: "鸡肉" },
    { id: "88A", name: "铁土豆鸡", price: 5.50, imageLink: "src/assets/menu/88A.jpg", description: "", category: "鸡肉" },
    { id: "88B", name: "串肉 (牛肉 & 鸡肉)", price: 6.00, imageLink: "src/assets/menu/88B.jpg", description: "", category: "鸡肉" },
    { id: "88C", name: "串牛肉", price: 6.00, imageLink: "src/assets/menu/88C.jpg", description: "", category: "鸡肉" },
    { id: "88D", name: "串鸡肉", price: 6.00, imageLink: "src/assets/menu/88D.jpg", description: "", category: "鸡肉" },
    { id: "88E", name: "泰式肉", price: 6.00, imageLink: "src/assets/menu/88E.jpg", description: "", category: "鸡肉" },
    { id: "88F", name: "沙茶肉", price: 6.00, imageLink: "src/assets/menu/88F.jpg", description: "", category: "鸡肉" },
    { id: "88G", name: "肉堡", price: 6.00, imageLink: "src/assets/menu/88G.jpg", description: "", category: "鸡肉" },
    { id: "89", name: "菠萝鸭", price: 6.50, imageLink: "src/assets/menu/89.jpg", description: "", category: "鸭肉" },
    { id: "89A", name: "柠檬鸭", price: 6.50, imageLink: "src/assets/menu/89A.jpg", description: "", category: "鸭肉" },
    { id: "89B", name: "桔子鸭", price: 6.50, imageLink: "src/assets/menu/89B.jpg", description: "", category: "鸭肉" },
    { id: "90", name: "香酥鸭", price: 6.50, imageLink: "src/assets/menu/90.jpg", description: "", category: "鸭肉" },
    { id: "91", name: "双冬鸭", price: 6.50, imageLink: "src/assets/menu/91.jpg", description: "", category: "鸭肉" },
    { id: "91A", name: "糖醋鸭", price: 6.50, imageLink: "src/assets/menu/91A.jpg", description: "", category: "鸭肉" },
    { id: "91B", name: "辣子鸭", price: 6.50, imageLink: "src/assets/menu/91B.jpg", description: "", category: "鸭肉" },
    { id: "92", name: "北京鸭", price: 9.00, imageLink: "src/assets/menu/92.jpg", description: "", category: "鸭肉" },
    { id: "92A", name: "北京全鸭", price: 40.00, imageLink: "src/assets/menu/92A.jpg", description: "", category: "鸭肉" },
    { id: "92B", name: "铁板鸭", price: 7.00, imageLink: "src/assets/menu/92B.jpg", description: "", category: "鸭肉" },
    { id: "93", name: "咕唠肉", price: 5.00, imageLink: "src/assets/menu/93.jpg", description: "", category: "猪肉" },
    { id: "94", name: "双冬猪肉", price: 5.00, imageLink: "src/assets/menu/94.jpg", description: "", category: "猪肉" },
    { id: "95", name: "豆芽猪肉", price: 5.00, imageLink: "src/assets/menu/95.jpg", description: "", category: "猪肉" },
    { id: "96", name: "辣子猪肉", price: 5.00, imageLink: "src/assets/menu/96.jpg", description: "", category: "猪肉" },
    { id: "96A", name: "宫爆猪肉", price: 5.00, imageLink: "src/assets/menu/96A.jpg", description: "", category: "猪肉" },
    { id: "96B", name: "榨菜猪肉", price: 5.00, imageLink: "src/assets/menu/96B.jpg", description: "", category: "猪肉" },
    { id: "97", name: "炸排骨", price: 5.00, imageLink: "src/assets/menu/97.jpg", description: "", category: "猪肉" },
    { id: "97A", name: "铁板猪肉", price: 5.50, imageLink: "src/assets/menu/97A.jpg", description: "", category: "猪肉" },
    { id: "97B", name: "土豆猪肉", price: 5.50, imageLink: "src/assets/menu/97B.jpg", description: "", category: "猪肉" },
    { id: "97C", name: "糖醋排骨", price: 5.50, imageLink: "src/assets/menu/97C.jpg", description: "", category: "猪肉" },
    { id: "97D", name: "椒盐排骨", price: 5.50, imageLink: "src/assets/menu/97D.jpg", description: "", category: "猪肉" },
    { id: "98", name: "蚝油牛肉", price: 5.50, imageLink: "src/assets/menu/98.jpg", description: "", category: "牛肉" },
    { id: "98A", name: "糖醋牛肉", price: 5.50, imageLink: "src/assets/menu/98A.jpg", description: "", category: "牛肉" },
    { id: "99", name: "双冬牛肉", price: 5.50, imageLink: "src/assets/menu/99.jpg", description: "", category: "牛肉" },
    { id: "100", name: "姜葱牛肉", price: 5.50, imageLink: "src/assets/menu/100.jpg", description: "", category: "牛肉" },
    { id: "101", name: "咖喱牛肉", price: 5.50, imageLink: "src/assets/menu/101.jpg", description: "", category: "牛肉" },
    { id: "102", name: "什锦牛肉", price: 5.50, imageLink: "src/assets/menu/102.jpg", description: "", category: "牛肉" },
    { id: "103", name: "豆芽牛肉", price: 5.50, imageLink: "src/assets/menu/103.jpg", description: "", category: "牛肉" },
    { id: "104", name: "辣子牛肉", price: 5.50, imageLink: "src/assets/menu/104.jpg", description: "", category: "牛肉" },
    { id: "105", name: "干烧牛肉", price: 5.50, imageLink: "src/assets/menu/105.jpg", description: "", category: "牛肉" },
    { id: "106", name: "铁板牛肉", price: 6.00, imageLink: "src/assets/menu/106.jpg", description: "", category: "牛肉" },
    { id: "107", name: "八宝巢", price: 6.50, imageLink: "src/assets/menu/107.jpg", description: "", category: "牛肉" },
    { id: "107A", name: "土豆牛肉", price: 6.00, imageLink: "src/assets/menu/107A.jpg", description: "", category: "牛肉" },
    { id: "107B", name: "铁板什肉", price: 6.00, imageLink: "src/assets/menu/107B.jpg", description: "", category: "牛肉" },
    { id: "108", name: "炒双冬", price: 3.50, imageLink: "src/assets/menu/108.jpg", description: "", category: "蔬菜" },
    { id: "109", name: "炒素菜", price: 3.50, imageLink: "src/assets/menu/109.jpg", description: "", category: "蔬菜" },
    { id: "109A", name: "炒辣菜", price: 3.50, imageLink: "src/assets/menu/109A.jpg", description: "", category: "蔬菜" },
    { id: "109B", name: "贴菜", price: 3.50, imageLink: "src/assets/menu/109B.jpg", description: "", category: "蔬菜" },
    { id: "110", name: "炒豆芽", price: 3.50, imageLink: "src/assets/menu/110.jpg", description: "", category: "蔬菜" },
    { id: "111", name: "辣子茄", price: 3.50, imageLink: "src/assets/menu/111.jpg", description: "", category: "蔬菜" },
    { id: "111A", name: "铁板土豆", price: 4.00, imageLink: "src/assets/menu/111A.jpg", description: "", category: "蔬菜" },
    { id: "111B", name: "烤土豆", price: 4.00, imageLink: "src/assets/menu/111B.jpg", description: "", category: "蔬菜" },
    { id: "112", name: "蟹肉炒蛋", price: 3.50, imageLink: "src/assets/menu/112.jpg", description: "", category: "蛋" },
    { id: "113", name: "虾仁炒蛋", price: 3.50, imageLink: "src/assets/menu/113.jpg", description: "", category: "蛋" },
    { id: "114", name: "火腿炒蛋", price: 3.50, imageLink: "src/assets/menu/114.jpg", description: "", category: "蛋" },
    { id: "114A", name: "葱炒蛋", price: 3.50, imageLink: "src/assets/menu/114A.jpg", description: "", category: "蛋" },
    { id: "115", name: "双冬豆腐", price: 4.00, imageLink: "src/assets/menu/115.jpg", description: "", category: "豆腐" },
    { id: "116", name: "辣子豆腐", price: 4.00, imageLink: "src/assets/menu/116.jpg", description: "", category: "豆腐" },
    { id: "117", name: "铁板豆腐", price: 4.00, imageLink: "src/assets/menu/117.jpg", description: "", category: "豆腐" },
    { id: "118", name: "虾仁豆腐", price: 5.50, imageLink: "src/assets/menu/118.jpg", description: "", category: "豆腐" },
    { id: "118A", name: "牛肉豆腐", price: 5.50, imageLink: "src/assets/menu/118A.jpg", description: "", category: "豆腐" },
    { id: "118C", name: "糖醋豆腐", price: 3.50, imageLink: "src/assets/menu/118C.jpg", description: "", category: "豆腐" },
    { id: "118D", name: "豆腐堡", price: 6.00, imageLink: "src/assets/menu/118D.jpg", description: "", category: "豆腐" },
    { id: "119", name: "炸水果", price: 3.00, imageLink: "src/assets/menu/119.jpg", description: "", category: "甜点" },
    { id: "119A", name: "炸香蕉", price: 3.00, imageLink: "src/assets/menu/119A.jpg", description: "", category: "甜点" },
    { id: "119B", name: "炸苹果", price: 3.00, imageLink: "src/assets/menu/119B.jpg", description: "", category: "甜点" },
    { id: "119C", name: "炸菠萝", price: 3.00, imageLink: "src/assets/menu/119C.jpg", description: "", category: "甜点" },
    { id: "120", name: "炸水果加冰", price: 4.00, imageLink: "src/assets/menu/120.jpg", description: "", category: "甜点" },
    { id: "121", name: "水果拔丝", price: 3.50, imageLink: "src/assets/menu/121.jpg", description: "", category: "甜点" },
    { id: "122", name: "水果拔丝加冰", price: 4.50, imageLink: "src/assets/menu/122.jpg", description: "", category: "甜点" },
    { id: "123", name: "炸椰子", price: 3.00, imageLink: "src/assets/menu/123.jpg", description: "", category: "甜点" },
    { id: "123A", name: "蒸椰子", price: 3.00, imageLink: "src/assets/menu/123A.jpg", description: "", category: "甜点" },
    { id: "123B", name: "蒸椰子加冰", price: 4.00, imageLink: "src/assets/menu/123B.jpg", description: "", category: "甜点" },
    { id: "124", name: "炸椰子加冰", price: 4.00, imageLink: "src/assets/menu/124.jpg", description: "", category: "甜点" },
    { id: "125", name: "炸Nutella", price: 3.00, imageLink: "src/assets/menu/125.jpg", description: "", category: "甜点" },
    { id: "125A", name: "炸Nutella 加冰", price: 4.00, imageLink: "src/assets/menu/125A.jpg", description: "", category: "甜点" },
    { id: "125B", name: "蒸Nutella", price: 3.00, imageLink: "src/assets/menu/125B.jpg", description: "", category: "甜点" },
    { id: "125C", name: "蒸Nutella 加冰", price: 4.00, imageLink: "src/assets/menu/125C.jpg", description: "", category: "甜点" },
    { id: "126", name: "中国水果", price: 3.00, imageLink: "src/assets/menu/126.jpg", description: "", category: "甜点" },
    { id: "127", name: "中国水果加冰", price: 4.00, imageLink: "src/assets/menu/127.jpg", description: "", category: "甜点" },
    { id: "128", name: "炸白冰", price: 3.00, imageLink: "src/assets/menu/128.jpg", description: "", category: "甜点" },
    { id: "128A", name: "炸巧克力冰", price: 3.00, imageLink: "src/assets/menu/128A.jpg", description: "", category: "甜点" },
    { id: "129", name: "什锦冰", price: 3.00, imageLink: "src/assets/menu/129.jpg", description: "", category: "甜点" },
    { id: "130", name: "白Tartufo", price: 3.50, imageLink: "src/assets/menu/130.jpg", description: "", category: "甜点" },
    { id: "130A", name: "黑Tartufo", price: 3.50, imageLink: "src/assets/menu/130A.jpg", description: "", category: "甜点" },
    { id: "130B", name: "Tartufo 加咖啡", price: 4.50, imageLink: "src/assets/menu/130B.jpg", description: "", category: "甜点" },
    { id: "130C", name: "Tartufo 加威士忌", price: 4.50, imageLink: "src/assets/menu/130C.jpg", description: "", category: "甜点" },
    { id: "130D", name: "Tiramisù", price: 3.50, imageLink: "src/assets/menu/130D.jpg", description: "", category: "甜点" },
    { id: "131", name: "柠檬冰", price: 4.50, imageLink: "src/assets/menu/131.jpg", description: "", category: "甜点" },
    { id: "131A", name: "椰子冰", price: 4.50, imageLink: "src/assets/menu/131A.jpg", description: "", category: "甜点" },
    { id: "132", name: "蛋糕", price: 3.80, imageLink: "src/assets/menu/132.jpg", description: "", category: "甜点" },
    { id: "133", name: "炸牛奶", price: 3.00, imageLink: "src/assets/menu/133.jpg", description: "", category: "甜点" },
    { id: "133A", name: "炸牛奶加冰", price: 4.00, imageLink: "src/assets/menu/133A.jpg", description: "", category: "甜点" },
    { id: "133B", name: "牛奶拔丝", price: 3.50, imageLink: "src/assets/menu/133B.jpg", description: "", category: "甜点" },
    { id: "134", name: "鲜菠萝", price: 3.50, imageLink: "src/assets/menu/134.jpg", description: "", category: "甜点" },
    { id: "135", name: "草莓加奶油", price: 3.50, imageLink: "src/assets/menu/135.jpg", description: "", category: "甜点" },
    { id: "137", name: "Sushi 甜点", price: 4.00, imageLink: "src/assets/menu/137.jpg", description: "", category: "甜点" },
    { id: "139", name: "块状甜点", price: 4.00, imageLink: "src/assets/menu/139.jpg", description: "", category: "甜点" },
    { id: "140", name: "泡泡冰", price: 3.50, imageLink: "src/assets/menu/140.jpg", description: "", category: "甜点" },
    { id: "141", name: "熟奶油", price: 3.50, imageLink: "src/assets/menu/141.jpg", description: "", category: "甜点" },  
    { id: "pinot_grigio", name: 'Pinot grigio', price: 7.90, imageLink: 'src/assets/menu/pinot_grigio.jpg', description:"", category:"酒水" },
    { id: "chardonnay", name: 'Chardonnay', price: 7.90, imageLink: 'src/assets/menu/chardonnay.jpg', description:"", category:"酒水" },
    { id: "verdicchio", name: 'Verdicchio', price: 8.90, imageLink: 'src/assets/menu/verdicchio.jpg', description:"", category:"酒水" },
    { id: "vernaccia_di_san_gimignano", name: 'Vernaccia di san gimignano', price: 8.90, imageLink: 'src/assets/menu/vernaccia_di_san_gimignano.jpg', description:"", category:"酒水" },
    { id: "mateus_rose", name: 'Mateus rose', price: 7.90, imageLink: 'src/assets/menu/mateus_rose.jpg', description:"", category:"酒水" },
    { id: "lancers_rose", name: 'Lancers rose', price: 7.90, imageLink: 'src/assets/menu/lancers_rose.jpg', description:"", category:"酒水" },
    { id: "santa_cristina", name: 'Santa cristina', price: 12.90, imageLink: 'src/assets/menu/santa_cristina.jpg', description:"", category:"酒水" },
    { id: "chianti_rosso", name: 'Chianti rosso', price: 7.90, imageLink: 'src/assets/menu/chianti_rosso.jpg', description:"", category:"酒水" },
    { id: "vino_della_casa_1l", name: 'Vino della casa 1l (Bianco/Rosso)', price: 6.00, imageLink: 'src/assets/menu/vino_della_casa_1l.jpg', description:"", category:"酒水" },
    { id: "vino_della_casa_0.5l", name: 'Vino della casa 0.5l (Bianco/Rosso)', price: 3.50, imageLink: 'src/assets/menu/vino_della_casa_0.5l.jpg', description:"", category:"酒水" },
    { id: "vino_della_casa_0.25L", name: 'Vino della casa 0.25L (Bianco/Rosso)', price: 2.00, imageLink: 'src/assets/menu/vino_della_casa_0.25L.jpg', description:"", category:"酒水" },
    { id: "birra_moretti_66cl", name: 'Birra Moretti 66cl', price: 3.50, imageLink: 'src/assets/menu/birra_moretti_66cl.jpg', description:"", category:"酒水" },
    { id: "birra_cinese_media", name: 'Birra cinese media', price: 4.00, imageLink: 'src/assets/menu/birra_cinese_media.jpg', description:"", category:"酒水" },
    { id: "birra_tennents", name: 'Birra Tennent’s', price: 3.50, imageLink: 'src/assets/menu/birra_tennents.jpg', description:"", category:"酒水" },
    { id: "birra_becks_33cl", name: 'Birra Becks 33cl', price: 2.50, imageLink: 'src/assets/menu/birra_becks_33cl.jpg', description:"", category:"酒水" },
    { id: "coca_cola_33cl", name: 'Coca cola 33 cl /o Coca cola zero 33cl', price: 2.00, imageLink: 'src/assets/menu/coca_cola_33cl.jpg', description:"", category:"酒水" },
    { id: "fanta_33cl", name: 'Fanta 33cl', price: 2.00, imageLink: 'src/assets/menu/fanta_33cl.jpg', description:"", category:"酒水" },
    { id: "sprite_33cl", name: 'Sprite 33cl', price: 2.00, imageLink: 'src/assets/menu/sprite_33cl.jpg', description:"", category:"酒水" },
    { id: "coca_cola_grande", name: 'Coca cola grande', price: 4.50, imageLink: 'src/assets/menu/coca_cola_grande.jpg', description:"", category:"酒水" },
    { id: "the_freddo_limone_pesca_33cl", name: 'The freddo limone / pesca 33cl', price: 2.00, imageLink: 'src/assets/menu/the_freddo_limone_pesca_33cl.jpg', description:"", category:"酒水" },
    { id: "the_caldo_gelsomino_verde", name: 'The caldo gelsomino / verde', price: 2.00, imageLink: 'src/assets/menu/the_caldo_gelsomino_verde.jpg', description:"", category:"酒水" },
    { id: "acqua_minerale_1l", name: 'Acqua minerale 1l', price: 2.00, imageLink: 'src/assets/menu/acqua_minerale_1l.jpg', description:"", category:"酒水" },
    { id: "acqua_minerale_0.5l", name: 'Acqua minerale 0.5l', price: 1.00, imageLink: 'src/assets/menu/acqua_minerale_0.5l.jpg', description:"", category:"酒水" },
    { id: "liquore_di_fragola", name: 'Liquore di fragola / mela verde / Baileys', price: 2.10, imageLink: 'src/assets/menu/liquore_di_fragola.jpg', description:"", category:"酒水" },
    { id: "limoncello_amaro_sambuca", name: 'Limoncello / amaro / sambuca', price: 2.10, imageLink: 'src/assets/menu/limoncello_amaro_sambuca.jpg', description:"", category:"酒水" },
    { id: "grappa_italiana_whiskey", name: 'Grappa italiana, whiskey', price: 2.10, imageLink: 'src/assets/menu/grappa_italiana_whiskey.jpg', description:"", category:"酒水" },
    { id: "ponce_livornese", name: 'Ponce Livornese', price: 3.50, imageLink: 'src/assets/menu/ponce_livornese.jpg', description:"", category:"酒水" },
    { id: "liquore_cinese", name: 'Liquore cinese (bambù, riso, rosa, ginseng, prugna)', price: 1.50, imageLink: 'src/assets/menu/liquore_cinese.jpg', description:"", category:"酒水" },
    { id: "amaro_cinese_alle_cinque_erbe", name: 'Amaro cinese alle cinque erbe', price: 1.50, imageLink: 'src/assets/menu/amaro_cinese_alle_cinque_erbe.jpg', description:"", category:"酒水" },
    { id: "sake", name: 'Sake', price: 2.00, imageLink: 'src/assets/menu/sake.jpg', description:"", category:"酒水" },
    { id: "caffe", name: 'Caffè', price: 1.20, imageLink: 'src/assets/menu/caffe.jpg', description:"", category:"酒水" },
    { id: "caffe_macchiato", name: 'Caffè macchiato', price: 1.40, imageLink: 'src/assets/menu/caffe_macchiato.jpg', description:"", category:"酒水" },
    { id: "caffe_corretto", name: 'Caffè corretto', price: 1.60, imageLink: 'src/assets/menu/caffe_corretto.jpg', description:"", category:"酒水" },
    { id: "caffe_d_orzo", name: 'Caffè d’orzo', price: 1.60, imageLink: 'src/assets/menu/caffe_d_orzo.jpg', description:"", category:"酒水" },
    { id: "caffe_decaffeinato", name: 'Caffè decaffeinato', price: 1.60, imageLink: 'src/assets/menu/caffe_decaffeinato.jpg', description:"", category:"酒水" },
    { id: "caffe_ginseng", name: 'Caffè GinSeng', price: 1.60, imageLink: 'src/assets/menu/caffe_ginseng.jpg', description:"", category:"酒水" },
    { id: "cappuccino", name: 'Cappuccino', price: 1.80, imageLink: 'src/assets/menu/cappuccino.jpg', description:"", category:"酒水" },
                
]

export default MenuCn;