const MenuEn=[
    { id: "0", name: 'Fried Chinese bread', price: 1.00, imageLink: 'src/assets/menu/0.jpg', description:"", category:"STARTERS" },
    { id: "0A", name: 'Steamed Chinese bread', price: 1.00, imageLink: 'src/assets/menu/0A.jpg', description:"", category:"STARTERS" },
    { id: "1", name: 'Spring rolls', price: 1.50, imageLink: 'src/assets/menu/1.jpg', description:"", category:"STARTERS" },
    { id: "1A", name: 'Special rolls', price: 1.80, imageLink: 'src/assets/menu/1A.jpg', description:"", category:"STARTERS" },
    { id: "2", name: 'Fried wanton', price: 1.60, imageLink: 'src/assets/menu/2.jpg', description:"", category:"STARTERS" },
    { id: "3", name: 'Lobster slices', price: 1.50, imageLink: 'src/assets/menu/3.jpg', description:"", category:"STARTERS" },
    { id: "4", name: 'Fried seaweed', price: 3.00, imageLink: 'src/assets/menu/4.jpg', description:"", category:"STARTERS" },
    { id: "5", name: 'Potato chips', price: 2.00, imageLink: 'src/assets/menu/5.jpg', description:"", category:"STARTERS" },
    { id: "5A", name: 'Bruschetta with tomato', price: 2.60, imageLink: 'src/assets/menu/5A.jpg', description:"", category:"STARTERS" },
    { id: "6", name: 'Chips', price: 2.50, imageLink: 'src/assets/menu/6.jpg', description:"", category:"STARTERS" },
    { id: "7", name: 'Shrimp toast', price: 2.50, imageLink: 'src/assets/menu/7.jpg', description:"", category:"STARTERS" },
    { id: "8", name: 'Chinese pizza', price: 3.00, imageLink: 'src/assets/menu/8.jpg', description:"", category:"STARTERS" },
    { id: "9", name: 'Steamed meat dumplings', price: 3.20, imageLink: 'src/assets/menu/9.jpg', description:"", category:"STARTERS" },
    { id: "10", name: 'Steamed vegetable dumplings', price: 3.40, imageLink: 'src/assets/menu/10.jpg', description:"", category:"STARTERS" },
    { id: "11", name: 'Grilled meat dumplings', price: 3.60, imageLink: 'src/assets/menu/11.jpg', description:"", category:"STARTERS" },
    { id: "12", name: 'Xiao mai of shrimps', price: 3.80, imageLink: 'src/assets/menu/12.jpg', description:"", category:"STARTERS" },
    { id: "12A", name: 'Crystal dumplings', price: 3.80, imageLink: 'src/assets/menu/12A.jpg', description:"", category:"STARTERS" },
    { id: "12B", name: 'Mixed dumplings (View 9,10,12)', price: 3.80, imageLink: 'src/assets/menu/12B.jpg', description:"", category:"STARTERS" },
    { id: "12C", name: 'Felicità dumplings', price: 3.80, imageLink: 'src/assets/menu/12C.jpg', description:"", category:"STARTERS" },
    { id: "13", name: 'Mixed hot starters (View 1,2,3,5,7)', price: 4.00, imageLink: 'src/assets/menu/13.jpg', description:"", category:"STARTERS" },
    { id: "14", name: 'Fried vegetables', price: 3.00, imageLink: 'src/assets/menu/14.jpg', description:"", category:"STARTERS" },
    { id: "14A", name: 'Meatballs of shrimps with sesame', price: 3.50, imageLink: 'src/assets/menu/14A.jpg', description:"", category:"STARTERS" },
    { id: "14B", name: 'Fried onion rings', price: 3.00, imageLink: 'src/assets/menu/14B.jpg', description:"", category:"STARTERS" },
    { id: "14C", name: 'Soybeans', price: 3.50, imageLink: 'src/assets/menu/14C.jpg', description:"", category:"STARTERS" },
    { id: "15", name: 'Chinese seaweed salad', price: 3.00, imageLink: 'src/assets/menu/15.jpg', description:"", category:"SALAD" },
    { id: "16", name: 'Chicken and mayonnaise salad', price: 3.50, imageLink: 'src/assets/menu/16.jpg', description:"", category:"SALAD" },
    { id: "17", name: 'Shrimp and mayonnaise salad', price: 3.50, imageLink: 'src/assets/menu/17.jpg', description:"", category:"SALAD" },
    { id: "17A", name: 'Flesh crab meat and mayonnaise salad', price: 3.50, imageLink: 'src/assets/menu/17A.jpg', description:"", category:"SALAD" },
    { id: "17B", name: 'Mixed salad', price: 3.00, imageLink: 'src/assets/menu/17B.jpg', description:"", category:"SALAD" },
    { id: "17C", name: 'Salad with prawns and peanuts in special sauce', price: 4.00, imageLink: 'src/assets/menu/17C.jpg', description:"", category:"SALAD" },
    { id: "17D", name: 'Mixed seafood salad', price: 6.00, imageLink: 'src/assets/menu/17D.jpg', description:"", category:"SALAD" },
    { id: "17E", name: 'Salad with shrimp, crab meat and mayonnaise', price: 4.00, imageLink: 'src/assets/menu/17E.jpg', description:"", category:"SALAD" },
    { id: "18", name: 'Oriental soup', price: 3.00, imageLink: 'src/assets/menu/18.jpg', description:"", category:"SOUP" },
    { id: "19", name: 'Wanton soup', price: 3.00, imageLink: 'src/assets/menu/19.jpg', description:"", category:"SOUP" },
    { id: "19A", name: 'Felicità soup', price: 3.50, imageLink: 'src/assets/menu/19A.jpg', description:"", category:"SOUP" },
    { id: "20", name: 'Chicken soup with Chinese mushrooms and bamboo', price: 3.00, imageLink: 'src/assets/menu/20.jpg', description:"", category:"SOUP" },
    { id: "21", name: 'Hot and sour soup', price: 3.00, imageLink: 'src/assets/menu/21.jpg', description:"", category:"SOUP" },
    { id: "22", name: 'Soy noodles soup with zazai', price: 3.00, imageLink: 'src/assets/menu/22.jpg', description:"", category:"SOUP" },
    { id: "23", name: 'Corn and chicken soup', price: 3.00, imageLink: 'src/assets/menu/23.jpg', description:"", category:"SOUP" },
    { id: "24", name: 'Crab meat and asparagus soup', price: 3.50, imageLink: 'src/assets/menu/24.jpg', description:"", category:"SOUP" },
    { id: "25A", name: 'Vegetable soup with toufu', price: 3.00, imageLink: 'src/assets/menu/25A.jpg', description:"", category:"SOUP" },
    { id: "25B", name: 'Miso soup', price: 3.00, imageLink: 'src/assets/menu/25B.jpg', description:"", category:"SOUP" },
    { id: "25C", name: 'Mixed seafood soup', price: 3.80, imageLink: 'src/assets/menu/25C.jpg', description:"", category:"SOUP" },
    { id: "25D", name: 'Thai style shrimp soup', price: 3.80, imageLink: 'src/assets/menu/25D.jpg', description:"", category:"SOUP" },
    { id: "25E", name: 'Thai style chicken soup', price: 3.80, imageLink: 'src/assets/menu/25E.jpg', description:"", category:"SOUP" },
    { id: "26", name: 'Noodles with mixed vegetables', price: 3.50, imageLink: 'src/assets/menu/26.jpg', description:"", category:"NOODLES&RICE" },
    { id: "26A", name: 'Udon with vegetables', price: 4.00, imageLink: 'src/assets/menu/26A.jpg', description:"", category:"NOODLES&RICE" },
    { id: "26B", name: 'Udon with seafood', price: 5.50, imageLink: 'src/assets/menu/26B.jpg', description:"", category:"NOODLES&RICE" },
    { id: "26C", name: 'Noodles in broth with seafood', price: 6.00, imageLink: 'src/assets/menu/26C.jpg', description:"", category:"NOODLES&RICE" },
    { id: "26D", name: 'Noodles in broth with meat', price: 6.00, imageLink: 'src/assets/menu/26D.jpg', description:"", category:"NOODLES&RICE" },
    { id: "27", name: 'Noodles with shrimp', price: 4.20, imageLink: 'src/assets/menu/27.jpg', description:"", category:"NOODLES&RICE" },
    { id: "28", name: 'Noodles with vegetables on the steel', price: 4.00, imageLink: 'src/assets/menu/28.jpg', description:"", category:"NOODLES&RICE" },
    { id: "28A", name: 'Tan tan mian', price: 4.00, imageLink: 'src/assets/menu/28A.jpg', description:"", category:"NOODLES&RICE" },
    { id: "28B", name: 'Noodles with meat and vegetables on the steel', price: 4.50, imageLink: 'src/assets/menu/28B.jpg', description:"", category:"NOODLES&RICE" },
    { id: "28C", name: 'Tan tan fan', price: 4.00, imageLink: 'src/assets/menu/28C.jpg', description:"", category:"NOODLES&RICE" },
    { id: "29", name: 'Noodles with seafood on the steel', price: 4.90, imageLink: 'src/assets/menu/29.jpg', description:"", category:"NOODLES&RICE" },
    { id: "29A", name: 'Soy noodles with seafood on the steel', price: 4.90, imageLink: 'src/assets/menu/29A.jpg', description:"", category:"NOODLES&RICE" },
    { id: "29B", name: 'Rice noodles with seafood on the steel', price: 4.90, imageLink: 'src/assets/menu/29B.jpg', description:"", category:"NOODLES&RICE" },
    { id: "30", name: 'Fried noodles with vegetables', price: 3.50, imageLink: 'src/assets/menu/30.jpg', description:"", category:"NOODLES&RICE" },
    { id: "30A", name: 'Fried noodles with seafood', price: 4.90, imageLink: 'src/assets/menu/30A.jpg', description:"", category:"NOODLES&RICE" },
    { id: "31", name: 'Rice noodles with mixed vegetables', price: 3.50, imageLink: 'src/assets/menu/31.jpg', description:"", category:"NOODLES&RICE" },
    { id: "31A", name: 'Rice noodles with seafood and vegetables', price: 4.90, imageLink: 'src/assets/menu/31A.jpg', description:"", category:"NOODLES&RICE" },
    { id: "31B", name: 'Rice noodles with shrimps and vegetables', price: 4.20, imageLink: 'src/assets/menu/31B.jpg', description:"", category:"NOODLES&RICE" },
    { id: "32", name: 'Rice noodles with pork and vegetables', price: 4.00, imageLink: 'src/assets/menu/32.jpg', description:"", category:"NOODLES&RICE" },
    { id: "33", name: 'Rice noodles with curry sauce', price: 3.50, imageLink: 'src/assets/menu/33.jpg', description:"", category:"NOODLES&RICE" },
    { id: "34", name: 'Soy noodles with pork and spicy sauce', price: 4.00, imageLink: 'src/assets/menu/34.jpg', description:"", category:"NOODLES&RICE" },
    { id: "35", name: 'Soy noodles with mixed vegetables', price: 3.50, imageLink: 'src/assets/menu/35.jpg', description:"", category:"NOODLES&RICE" },
    { id: "35A", name: 'Soy noodles with shrimps and vegetables', price: 4.20, imageLink: 'src/assets/menu/35A.jpg', description:"", category:"NOODLES&RICE" },
    { id: "36", name: 'Sliced rice cake with vegetables', price: 3.80, imageLink: 'src/assets/menu/36.jpg', description:"", category:"NOODLES&RICE" },
    { id: "36A", name: 'Sliced rice cake with seafood', price: 5.00, imageLink: 'src/assets/menu/36A.jpg', description:"", category:"NOODLES&RICE" },
    { id: "36B", name: 'Sliced rice cake with pork and vegetables', price: 4.30, imageLink: 'src/assets/menu/36B.jpg', description:"", category:"NOODLES&RICE" },
    { id: "37", name: 'Rice with shrimps', price: 4.20, imageLink: 'src/assets/menu/37.jpg', description:"", category:"NOODLES&RICE" },
    { id: "38", name: 'Rice with mixed vegetables', price: 3.50, imageLink: 'src/assets/menu/38.jpg', description:"", category:"NOODLES&RICE" },
    { id: "39", name: 'Cantonese style rice', price: 3.50, imageLink: 'src/assets/menu/39.jpg', description:"", category:"NOODLES&RICE" },
    { id: "39A", name: 'Rice with chicken', price: 3.50, imageLink: 'src/assets/menu/39A.jpg', description:"", category:"NOODLES&RICE" },
    { id: "40", name: 'Rice with curry sauce', price: 3.50, imageLink: 'src/assets/menu/40.jpg', description:"", category:"NOODLES&RICE" },
    { id: "41", name: 'Rice with pineapple and pine nuts', price: 4.00, imageLink: 'src/assets/menu/41.jpg', description:"", category:"NOODLES&RICE" },
    { id: "42", name: 'White rice', price: 1.50, imageLink: 'src/assets/menu/42.jpg', description:"", category:"NOODLES&RICE" },
    { id: "42A", name: 'Crispy rice with mixed meat', price: 4.50, imageLink: 'src/assets/menu/42A.jpg', description:"", category:"NOODLES&RICE" },
    { id: "42B", name: 'Crispy rice with seafood', price: 4.90, imageLink: 'src/assets/menu/42B.jpg', description:"", category:"NOODLES&RICE" },
    { id: "42C", name: 'Pasta with tomatoes', price: 3.50, imageLink: 'src/assets/menu/42C.jpg', description:"", category:"NOODLES&RICE" },
    { id: "42D", name: 'Pasta with ragù', price: 3.50, imageLink: 'src/assets/menu/42D.jpg', description:"", category:"NOODLES&RICE" },
    { id: "42E", name: 'Rice with seafood', price: 4.90, imageLink: 'src/assets/menu/42E.jpg', description:"", category:"NOODLES&RICE" },
    { id: "42F", name: 'Ziao fan with meat and seafood', price: 5.00, imageLink: 'src/assets/menu/42F.jpg', description:"", category:"NOODLES&RICE" },
    { id: "42G", name: 'Ziao mian with meat and seafood', price: 5.00, imageLink: 'src/assets/menu/42G.jpg', description:"", category:"NOODLES&RICE" },
    { id: "42H", name: 'Thai style noodles', price: 4.50, imageLink: 'src/assets/menu/42H.jpg', description:"", category:"NOODLES&RICE" },
    { id: "42L", name: 'Thai style rice', price: 4.50, imageLink: 'src/assets/menu/42L.jpg', description:"", category:"NOODLES&RICE" },
    { id: "43", name: 'Shrimps with bamboo and Chinese mushrooms', price: 6.00, imageLink: 'src/assets/menu/43.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "44", name: 'Shrimps with mixed vegetables', price: 6.00, imageLink: 'src/assets/menu/44.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "45", name: 'Shrimps with peas', price: 6.00, imageLink: 'src/assets/menu/45.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "45A", name: 'Shrimps with cashew nuts', price: 6.00, imageLink: 'src/assets/menu/45A.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "46", name: 'Shrimps with curry sauce', price: 6.00, imageLink: 'src/assets/menu/46.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "47", name: 'Shrimps in hot sauce', price: 6.00, imageLink: 'src/assets/menu/47.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "47A", name: 'Shrimps with KongBao and spicy sauces', price: 6.00, imageLink: 'src/assets/menu/47A.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "48", name: 'Fried shrimps in sweet and sour sauce', price: 6.00, imageLink: 'src/assets/menu/48.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "48A", name: 'Unfried shrimps in sweet and sour sauce', price: 6.00, imageLink: 'src/assets/menu/48A.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "49", name: 'Shrimps with apples', price: 6.00, imageLink: 'src/assets/menu/49.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "49A", name: 'Shrimps with orange', price: 6.00, imageLink: 'src/assets/menu/49A.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "49B", name: 'Shrimps with lemons', price: 6.00, imageLink: 'src/assets/menu/49B.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "49C", name: 'Shrimps with ananas', price: 6.00, imageLink: 'src/assets/menu/49C.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "50", name: 'Fried shrimps', price: 6.00, imageLink: 'src/assets/menu/50.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "50A", name: 'Fried shrimps with sesame', price: 6.50, imageLink: 'src/assets/menu/50A.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "51", name: 'Grilled shrimps with pepper', price: 6.50, imageLink: 'src/assets/menu/51.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "52", name: 'Shrimps with leeks and carrots on the steel', price: 6.50, imageLink: 'src/assets/menu/52.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "53A", name: 'Shrimp nest with vegetables', price: 6.50, imageLink: 'src/assets/menu/53A.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "53B", name: 'Mixed seafood nest', price: 6.50, imageLink: 'src/assets/menu/53B.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "53C", name: 'Squid and shrimp skewers', price: 7.00, imageLink: 'src/assets/menu/53C.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "53D", name: 'Shrimp skewers', price: 7.00, imageLink: 'src/assets/menu/53D.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "53E", name: 'Squid skewers', price: 7.00, imageLink: 'src/assets/menu/53E.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "53F", name: 'Thai style crustaceans', price: 7.00, imageLink: 'src/assets/menu/53F.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "53G", name: 'Crustaceans with sate sauce', price: 7.00, imageLink: 'src/assets/menu/53G.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "54", name: 'Prawns in hot sauce', price: 6.50, imageLink: 'src/assets/menu/54.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "55", name: 'Steamed prawns', price: 6.50, imageLink: 'src/assets/menu/55.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "56", name: 'Prawns stewed in Chinese sauce', price: 6.50, imageLink: 'src/assets/menu/56.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "57", name: 'Fried prawns with sesame', price: 6.50, imageLink: 'src/assets/menu/57.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "57A", name: 'Imperial fried shrimps', price: 7.00, imageLink: 'src/assets/menu/57A.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "58", name: 'Grilled prawns on the steel (6 pieces)', price: 9.00, imageLink: 'src/assets/menu/58.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "59", name: 'Grilled prawns with leeks and carrots on the steel', price: 9.00, imageLink: 'src/assets/menu/59.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "59A", name: 'Salt and pepper prawns on the steel', price: 9.00, imageLink: 'src/assets/menu/59A.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "59B", name: 'Flambè prawns on the steel', price: 9.00, imageLink: 'src/assets/menu/59B.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "60", name: 'Mixed seafood with spicy sauce on the steel', price: 7.00, imageLink: 'src/assets/menu/60.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "61", name: 'Fish fillets with lemon sauce', price: 6.00, imageLink: 'src/assets/menu/61.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "62", name: 'Steamed fish fillets', price: 6.00, imageLink: 'src/assets/menu/62.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "63", name: 'Grilled fish(whole)', price: 10.00, imageLink: 'src/assets/menu/63.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "64", name: 'Steamed fish(whole)', price: 10.00, imageLink: 'src/assets/menu/64.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "65", name: 'Stewed fish with Chinese sauce (whole)', price: 10.00, imageLink: 'src/assets/menu/65.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "66", name: 'Squid in hot sauce', price: 6.00, imageLink: 'src/assets/menu/66.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "67", name: 'Fried squid in sweet and sour sauce', price: 6.00, imageLink: 'src/assets/menu/67.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "67A", name: 'Unfried squid in sweet and sour sauce', price: 6.00, imageLink: 'src/assets/menu/67A.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "68", name: 'Squid with mixed vegetables', price: 6.00, imageLink: 'src/assets/menu/68.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "68A", name: 'Squid with leeks and carrots on the steel', price: 6.50, imageLink: 'src/assets/menu/68A.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "69", name: 'Fried frog legs', price: 7.50, imageLink: 'src/assets/menu/69.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "70", name: 'Frogs legs on the steel', price: 7.50, imageLink: 'src/assets/menu/70.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "71", name: 'Fried crab claws (5 Pieces)', price: 6.50, imageLink: 'src/assets/menu/71.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "71A", name: 'Steamed crab', price: 9.00, imageLink: 'src/assets/menu/71A.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "71B", name: 'Crab stewed in Chinese sauce', price: 9.00, imageLink: 'src/assets/menu/71B.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "71C", name: 'Granchio with pepper and salt', price: 9.00, imageLink: 'src/assets/menu/71C.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "72", name: 'Fried seafood', price: 6.00, imageLink: 'src/assets/menu/72.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "73", name: 'Clay pot of seafoods', price: 7.00, imageLink: 'src/assets/menu/73.jpg', description:"", category:"CRUSTACEANS&FISH" },
    { id: "74", name: "Fried chicken in sweet and sour sauce", price: 5.00, imageLink: "src/assets/menu/74.jpg", description: "", category: "CHICKEN" },
    { id: "74A", name: "Chicken with green peppers", price: 5.00, imageLink: "src/assets/menu/74A.jpg", description: "", category: "CHICKEN" },
    { id: "74B", name: "Unfried chicken in sweet and sour sauce", price: 5.00, imageLink: "src/assets/menu/74B.jpg", description: "", category: "CHICKEN" },
    { id: "75", name: "Fried chicken with lemon sauce", price: 5.00, imageLink: "src/assets/menu/75.jpg", description: "", category: "CHICKEN" },
    { id: "75A", name: "Unfried chicken with lemon sauce", price: 5.00, imageLink: "src/assets/menu/75A.jpg", description: "", category: "CHICKEN" },
    { id: "75B", name: "Chicken with asparagus", price: 5.00, imageLink: "src/assets/menu/75B.jpg", description: "", category: "CHICKEN" },
    { id: "75C", name: "Chicken with celery", price: 5.00, imageLink: "src/assets/menu/75C.jpg", description: "", category: "CHICKEN" },
    { id: "76", name: "Fried chicken with orange sauce", price: 5.00, imageLink: "src/assets/menu/76.jpg", description: "", category: "CHICKEN" },
    { id: "76A", name: "Unfried chicken with orange sauce", price: 5.00, imageLink: "src/assets/menu/76A.jpg", description: "", category: "CHICKEN" },
    { id: "77", name: "Chicken with soy bean sprouts", price: 5.00, imageLink: "src/assets/menu/77.jpg", description: "", category: "CHICKEN" },
    { id: "78", name: "Chicken with almonds", price: 5.00, imageLink: "src/assets/menu/78.jpg", description: "", category: "CHICKEN" },
    { id: "78A", name: "Chicken with cashew nuts", price: 5.00, imageLink: "src/assets/menu/78A.jpg", description: "", category: "CHICKEN" },
    { id: "79", name: "Chicken with KongBao and spicy sauces", price: 5.00, imageLink: "src/assets/menu/79.jpg", description: "", category: "CHICKEN" },
    { id: "80", name: "Roasted chicken with Chinese aromas", price: 5.50, imageLink: "src/assets/menu/80.jpg", description: "", category: "CHICKEN" },
    { id: "81", name: "Roasted chicken in Chinese sauce", price: 5.50, imageLink: "src/assets/menu/81.jpg", description: "", category: "CHICKEN" },
    { id: "82", name: "Chicken with bamboo and Chinese mushrooms", price: 5.00, imageLink: "src/assets/menu/82.jpg", description: "", category: "CHICKEN" },
    { id: "83", name: "Chicken with pineapple", price: 5.00, imageLink: "src/assets/menu/83.jpg", description: "", category: "CHICKEN" },
    { id: "84", name: "Chicken with curry sauce", price: 5.00, imageLink: "src/assets/menu/84.jpg", description: "", category: "CHICKEN" },
    { id: "85", name: "Fried chicken morsels", price: 5.00, imageLink: "src/assets/menu/85.jpg", description: "", category: "CHICKEN" },
    { id: "85A", name: "Fried breaded chicken", price: 5.50, imageLink: "src/assets/menu/85A.jpg", description: "", category: "CHICKEN" },
    { id: "85B", name: "Fried chicken with sesame", price: 6.00, imageLink: "src/assets/menu/85B.jpg", description: "", category: "CHICKEN" },
    { id: "86", name: "Chicken with shrimps and Chinese mushrooms", price: 6.00, imageLink: "src/assets/menu/86.jpg", description: "", category: "CHICKEN" },
    { id: "87", name: "Potato basket with chicken and pine nuts", price: 5.50, imageLink: "src/assets/menu/87.jpg", description: "", category: "CHICKEN" },
    { id: "88", name: "Chicken with leeks and carrots on the steel", price: 5.50, imageLink: "src/assets/menu/88.jpg", description: "", category: "CHICKEN" },
    { id: "88A", name: "Chicken with potatoes in the steel", price: 5.50, imageLink: "src/assets/menu/88A.jpg", description: "", category: "CHICKEN" },
    { id: "88B", name: "Mixed meat skewers (beef & chicken)", price: 6.00, imageLink: "src/assets/menu/88B.jpg", description: "", category: "CHICKEN" },
    { id: "88C", name: "Beef skewers", price: 6.00, imageLink: "src/assets/menu/88C.jpg", description: "", category: "CHICKEN" },
    { id: "88D", name: "Chicken skewers", price: 6.00, imageLink: "src/assets/menu/88D.jpg", description: "", category: "CHICKEN" },
    { id: "88E", name: "Thai style meat", price: 6.00, imageLink: "src/assets/menu/88E.jpg", description: "", category: "CHICKEN" },
    { id: "88F", name: "Meat with sate sauce", price: 6.00, imageLink: "src/assets/menu/88F.jpg", description: "", category: "CHICKEN" },
    { id: "88G", name: "Clay pot of meat", price: 6.00, imageLink: "src/assets/menu/88G.jpg", description: "", category: "CHICKEN" },
    { id: "89", name: "Roasted duck with pineapple", price: 6.50, imageLink: "src/assets/menu/89.jpg", description: "", category: "DUCK" },
    { id: "89A", name: "Duck with lemon sauce", price: 6.50, imageLink: "src/assets/menu/89A.jpg", description: "", category: "DUCK" },
    { id: "89B", name: "Duck with orange sauce", price: 6.50, imageLink: "src/assets/menu/89B.jpg", description: "", category: "DUCK" },
    { id: "90", name: "Roasted duck with Chinese aromas", price: 6.50, imageLink: "src/assets/menu/90.jpg", description: "", category: "DUCK" },
    { id: "91", name: "Duck with bamboo and Chinese mushrooms", price: 6.50, imageLink: "src/assets/menu/91.jpg", description: "", category: "DUCK" },
    { id: "91A", name: "Duck in sweet and sour sauce", price: 6.50, imageLink: "src/assets/menu/91A.jpg", description: "", category: "DUCK" },
    { id: "91B", name: "Duck in the hot sauce", price: 6.50, imageLink: "src/assets/menu/91B.jpg", description: "", category: "DUCK" },
    { id: "92", name: "Peking duck", price: 9.00, imageLink: "src/assets/menu/92.jpg", description: "", category: "DUCK" },
    { id: "92A", name: "Peking lacquered duck (order a day before)", price: 40.00, imageLink: "src/assets/menu/92A.jpg", description: "", category: "DUCK" },
    { id: "92B", name: "Duck with leeks and carrots on the steel", price: 7.00, imageLink: "src/assets/menu/92B.jpg", description: "", category: "DUCK" },
    { id: "93", name: "Pork in sweet and sour sauce", price: 5.00, imageLink: "src/assets/menu/93.jpg", description: "", category: "PORK" },
    { id: "94", name: "Pork with bamboo and Chinese mushrooms", price: 5.00, imageLink: "src/assets/menu/94.jpg", description: "", category: "PORK" },
    { id: "95", name: "Pork with soy bean sprouts", price: 5.00, imageLink: "src/assets/menu/95.jpg", description: "", category: "PORK" },
    { id: "96", name: "Pork in the hot sauce", price: 5.00, imageLink: "src/assets/menu/96.jpg", description: "", category: "PORK" },
    { id: "96A", name: "Pork with KongBao and spicy sauces", price: 5.00, imageLink: "src/assets/menu/96A.jpg", description: "", category: "PORK" },
    { id: "96B", name: "Pork with za zai", price: 5.00, imageLink: "src/assets/menu/96B.jpg", description: "", category: "PORK" },
    { id: "97", name: "Fried pork’s ribs", price: 5.00, imageLink: "src/assets/menu/97.jpg", description: "", category: "PORK" },
    { id: "97A", name: "Pork with leeks and carrots on the steel", price: 5.50, imageLink: "src/assets/menu/97A.jpg", description: "", category: "PORK" },
    { id: "97B", name: "Pork with potatoes on the steel", price: 5.50, imageLink: "src/assets/menu/97B.jpg", description: "", category: "PORK" },
    { id: "97C", name: "Porks’s ribs in sweet and sour sauce", price: 5.50, imageLink: "src/assets/menu/97C.jpg", description: "", category: "PORK" },
    { id: "97D", name: "Pepper and salt ribs", price: 5.50, imageLink: "src/assets/menu/97D.jpg", description: "", category: "PORK" },
    { id: "98", name: "Beef in oyster sauce", price: 5.50, imageLink: "src/assets/menu/98.jpg", description: "", category: "BEEF" },
    { id: "98A", name: "Beef in sweet and sour sauce", price: 5.50, imageLink: "src/assets/menu/98A.jpg", description: "", category: "BEEF" },
    { id: "99", name: "Beef with bamboo and Chinese mushrooms", price: 5.50, imageLink: "src/assets/menu/99.jpg", description: "", category: "BEEF" },
    { id: "100", name: "Beef with ginger and leeks", price: 5.50, imageLink: "src/assets/menu/100.jpg", description: "", category: "BEEF" },
    { id: "101", name: "Beef with curry sauce", price: 5.50, imageLink: "src/assets/menu/101.jpg", description: "", category: "BEEF" },
    { id: "102", name: "Beef with mixed vegetables", price: 5.50, imageLink: "src/assets/menu/102.jpg", description: "", category: "BEEF" },
    { id: "103", name: "Beef with soy bean sprouts", price: 5.50, imageLink: "src/assets/menu/103.jpg", description: "", category: "BEEF" },
    { id: "104", name: "Beef in the hot sauce", price: 5.50, imageLink: "src/assets/menu/104.jpg", description: "", category: "BEEF" },
    { id: "105", name: "Crispy beef in the hot sauce", price: 5.50, imageLink: "src/assets/menu/105.jpg", description: "", category: "BEEF" },
    { id: "106", name: "Beef with leeks and carrots on the steel", price: 6.00, imageLink: "src/assets/menu/106.jpg", description: "", category: "BEEF" },
    { id: "107", name: "Mixed meat in spicy creamy sauce", price: 6.50, imageLink: "src/assets/menu/107.jpg", description: "", category: "BEEF" },
    { id: "107A", name: "Beef with potatoes on the steel", price: 6.00, imageLink: "src/assets/menu/107A.jpg", description: "", category: "BEEF" },
    { id: "107B", name: "Mixed meat with leeks and carrots on the steel", price: 6.00, imageLink: "src/assets/menu/107B.jpg", description: "", category: "BEEF" },
    { id: "108", name: "Bamboo and Chinese mushrooms", price: 3.50, imageLink: "src/assets/menu/108.jpg", description: "", category: "VEGETABLES" },
    { id: "109", name: "Mixed vegetables", price: 3.50, imageLink: "src/assets/menu/109.jpg", description: "", category: "VEGETABLES" },
    { id: "109A", name: "Si-Chuang style vegetables with hot sauce", price: 3.50, imageLink: "src/assets/menu/109A.jpg", description: "", category: "VEGETABLES" },
    { id: "109B", name: "Grilled mixed vegetables", price: 3.50, imageLink: "src/assets/menu/109B.jpg", description: "", category: "VEGETABLES" },
    { id: "110", name: "Soy bean sprouts", price: 3.50, imageLink: "src/assets/menu/110.jpg", description: "", category: "VEGETABLES" },
    { id: "111", name: "Eggplants in Chinese piccante sauce", price: 3.50, imageLink: "src/assets/menu/111.jpg", description: "", category: "VEGETABLES" },
    { id: "111A", name: "Potatoes on the steel", price: 4.00, imageLink: "src/assets/menu/111A.jpg", description: "", category: "VEGETABLES" },
    { id: "111B", name: "Roasted potato cubes", price: 4.00, imageLink: "src/assets/menu/111B.jpg", description: "", category: "VEGETABLES" },
    { id: "112", name: "Omelet with crab meat", price: 3.50, imageLink: "src/assets/menu/112.jpg", description: "", category: "OMELET" },
    { id: "113", name: "Omelets with shrimps", price: 3.50, imageLink: "src/assets/menu/113.jpg", description: "", category: "OMELET" },
    { id: "114", name: "Omelets with ham", price: 3.50, imageLink: "src/assets/menu/114.jpg", description: "", category: "OMELET" },
    { id: "114A", name: "Omelets with leeks", price: 3.50, imageLink: "src/assets/menu/114A.jpg", description: "", category: "OMELET" },
    { id: "115", name: "Tou fu with bamboo and Chinese mushrooms", price: 4.00, imageLink: "src/assets/menu/115.jpg", description: "", category: "TOUFU" },
    { id: "116", name: "Tou fu in the hot sauce", price: 4.00, imageLink: "src/assets/menu/116.jpg", description: "", category: "TOUFU" },
    { id: "117", name: "Tou fu on the steel", price: 4.00, imageLink: "src/assets/menu/117.jpg", description: "", category: "TOUFU" },
    { id: "118", name: "Tou fu with shrimps and Chinese mushrooms", price: 5.50, imageLink: "src/assets/menu/118.jpg", description: "", category: "TOUFU" },
    { id: "118A", name: "Tou fu with beef", price: 5.50, imageLink: "src/assets/menu/118A.jpg", description: "", category: "TOUFU" },
    { id: "118C", name: "Tou fu in sweet and sour sauce", price: 3.50, imageLink: "src/assets/menu/118C.jpg", description: "", category: "TOUFU" },
    { id: "118D", name: "Clay pot of tou fu with seafood", price: 6.00, imageLink: "src/assets/menu/118D.jpg", description: "", category: "TOUFU" },
    { id: "119", name: "Fried mixed fruit", price: 3.00, imageLink: "src/assets/menu/119.jpg", description: "", category: "DESSERT" },
    { id: "119A", name: "Fried banana", price: 3.00, imageLink: "src/assets/menu/119A.jpg", description: "", category: "DESSERT" },
    { id: "119B", name: "Fried apple", price: 3.00, imageLink: "src/assets/menu/119B.jpg", description: "", category: "DESSERT" },
    { id: "119C", name: "Fried pineapple", price: 3.00, imageLink: "src/assets/menu/119C.jpg", description: "", category: "DESSERT" },
    { id: "120", name: "Fried fruit with ice cream", price: 4.00, imageLink: "src/assets/menu/120.jpg", description: "", category: "DESSERT" },
    { id: "121", name: "Caramelized mixed fruit", price: 3.50, imageLink: "src/assets/menu/121.jpg", description: "", category: "DESSERT" },
    { id: "122", name: "Caramelized mixed fruit with ice cream", price: 4.50, imageLink: "src/assets/menu/122.jpg", description: "", category: "DESSERT" },
    { id: "123", name: "Fried coconut", price: 3.00, imageLink: "src/assets/menu/123.jpg", description: "", category: "DESSERT" },
    { id: "123A", name: "Steamed coconut", price: 3.00, imageLink: "src/assets/menu/123A.jpg", description: "", category: "DESSERT" },
    { id: "123B", name: "Steamed coconut with ice cream", price: 4.00, imageLink: "src/assets/menu/123B.jpg", description: "", category: "DESSERT" },
    { id: "124", name: "Fried coconut with ice cream", price: 4.00, imageLink: "src/assets/menu/124.jpg", description: "", category: "DESSERT" },
    { id: "125", name: "Fried nutella", price: 3.00, imageLink: "src/assets/menu/125.jpg", description: "", category: "DESSERT" },
    { id: "125A", name: "Fried nutella with ice cream", price: 4.00, imageLink: "src/assets/menu/125A.jpg", description: "", category: "DESSERT" },
    { id: "125B", name: "Steamed nutella", price: 3.00, imageLink: "src/assets/menu/125B.jpg", description: "", category: "DESSERT" },
    { id: "125C", name: "Steamed nutella with ice cream", price: 4.00, imageLink: "src/assets/menu/125C.jpg", description: "", category: "DESSERT" },
    { id: "126", name: "Chinese fruit", price: 3.00, imageLink: "src/assets/menu/126.jpg", description: "", category: "DESSERT" },
    { id: "127", name: "Chinese fruit with ice cream", price: 4.00, imageLink: "src/assets/menu/127.jpg", description: "", category: "DESSERT" },
    { id: "128", name: "Fried ice cream (Cream)", price: 3.00, imageLink: "src/assets/menu/128.jpg", description: "", category: "DESSERT" },
    { id: "128A", name: "Fried ice cream (Chocolate)", price: 3.00, imageLink: "src/assets/menu/128A.jpg", description: "", category: "DESSERT" },
    { id: "129", name: "Mix of ice cream", price: 3.00, imageLink: "src/assets/menu/129.jpg", description: "", category: "DESSERT" },
    { id: "130", name: "White truffle", price: 3.50, imageLink: "src/assets/menu/130.jpg", description: "", category: "DESSERT" },
    { id: "130A", name: "Black truffle", price: 3.50, imageLink: "src/assets/menu/130A.jpg", description: "", category: "DESSERT" },
    { id: "130B", name: "Truffle drowned with coffee", price: 4.50, imageLink: "src/assets/menu/130B.jpg", description: "", category: "DESSERT" },
    { id: "130C", name: "Truffle drowned with whiskey", price: 4.50, imageLink: "src/assets/menu/130C.jpg", description: "", category: "DESSERT" },
    { id: "130D", name: "Tiramisù", price: 3.50, imageLink: "src/assets/menu/130D.jpg", description: "", category: "DESSERT" },
    { id: "131", name: "Stuffed ice cream (Lemon)", price: 4.50, imageLink: "src/assets/menu/131.jpg", description: "", category: "DESSERT" },
    { id: "131A", name: "Stufed ice cream (Coconut)", price: 4.50, imageLink: "src/assets/menu/131A.jpg", description: "", category: "DESSERT" },
    { id: "132", name: "Semifreddo cake", price: 3.80, imageLink: "src/assets/menu/132.jpg", description: "", category: "DESSERT" },
    { id: "133", name: "Fried milk", price: 3.00, imageLink: "src/assets/menu/133.jpg", description: "", category: "DESSERT" },
    { id: "133A", name: "Fried milk with ice cream", price: 4.00, imageLink: "src/assets/menu/133A.jpg", description: "", category: "DESSERT" },
    { id: "133B", name: "Caramelized milk", price: 3.50, imageLink: "src/assets/menu/133B.jpg", description: "", category: "DESSERT" },
    { id: "134", name: "Fresh pineapple", price: 3.50, imageLink: "src/assets/menu/134.jpg", description: "", category: "DESSERT" },
    { id: "135", name: "Strawberries with cream", price: 3.50, imageLink: "src/assets/menu/135.jpg", description: "", category: "DESSERT" },
    { id: "137", name: "Sushi dessert", price: 4.00, imageLink: "src/assets/menu/137.jpg", description: "", category: "DESSERT" },
    { id: "139", name: "Mattonella pine nuts", price: 4.00, imageLink: "src/assets/menu/139.jpg", description: "", category: "DESSERT" },
    { id: "140", name: "Sgroppino", price: 3.50, imageLink: "src/assets/menu/140.jpg", description: "", category: "DESSERT" },
    { id: "141", name: "Fresh Panna Cotta", price: 3.50, imageLink: "src/assets/menu/141.jpg", description: "", category: "DESSERT" },
    { id: "pinot_grigio", name: 'Pinot grigio', price: 7.90, imageLink: 'src/assets/menu/pinot_grigio.jpg', description:"", category:"DRINKS" },
    { id: "chardonnay", name: 'Chardonnay', price: 7.90, imageLink: 'src/assets/menu/chardonnay.jpg', description:"", category:"DRINKS" },
    { id: "verdicchio", name: 'Verdicchio', price: 8.90, imageLink: 'src/assets/menu/verdicchio.jpg', description:"", category:"DRINKS" },
    { id: "vernaccia_di_san_gimignano", name: 'Vernaccia di san gimignano', price: 8.90, imageLink: 'src/assets/menu/vernaccia_di_san_gimignano.jpg', description:"", category:"DRINKS" },
    { id: "mateus_rose", name: 'Mateus rose', price: 7.90, imageLink: 'src/assets/menu/mateus_rose.jpg', description:"", category:"DRINKS" },
    { id: "lancers_rose", name: 'Lancers rose', price: 7.90, imageLink: 'src/assets/menu/lancers_rose.jpg', description:"", category:"DRINKS" },
    { id: "santa_cristina", name: 'Santa cristina', price: 12.90, imageLink: 'src/assets/menu/santa_cristina.jpg', description:"", category:"DRINKS" },
    { id: "chianti_rosso", name: 'Chianti rosso', price: 7.90, imageLink: 'src/assets/menu/chianti_rosso.jpg', description:"", category:"DRINKS" },
    { id: "vino_della_casa_1l", name: 'Vino della casa 1l (Bianco/Rosso)', price: 6.00, imageLink: 'src/assets/menu/vino_della_casa_1l.jpg', description:"", category:"DRINKS" },
    { id: "vino_della_casa_0.5l", name: 'Vino della casa 0.5l (Bianco/Rosso)', price: 3.50, imageLink: 'src/assets/menu/vino_della_casa_0.5l.jpg', description:"", category:"DRINKS" },
    { id: "vino_della_casa_0.25L", name: 'Vino della casa 0.25L (Bianco/Rosso)', price: 2.00, imageLink: 'src/assets/menu/vino_della_casa_0.25L.jpg', description:"", category:"DRINKS" },
    { id: "birra_moretti_66cl", name: 'Birra Moretti 66cl', price: 3.50, imageLink: 'src/assets/menu/birra_moretti_66cl.jpg', description:"", category:"DRINKS" },
    { id: "birra_cinese_media", name: 'Birra cinese media', price: 4.00, imageLink: 'src/assets/menu/birra_cinese_media.jpg', description:"", category:"DRINKS" },
    { id: "birra_tennents", name: 'Birra Tennent’s', price: 3.50, imageLink: 'src/assets/menu/birra_tennents.jpg', description:"", category:"DRINKS" },
    { id: "birra_becks_33cl", name: 'Birra Becks 33cl', price: 2.50, imageLink: 'src/assets/menu/birra_becks_33cl.jpg', description:"", category:"DRINKS" },
    { id: "coca_cola_33cl", name: 'Coca cola 33 cl /o Coca cola zero 33cl', price: 2.00, imageLink: 'src/assets/menu/coca_cola_33cl.jpg', description:"", category:"DRINKS" },
    { id: "fanta_33cl", name: 'Fanta 33cl', price: 2.00, imageLink: 'src/assets/menu/fanta_33cl.jpg', description:"", category:"DRINKS" },
    { id: "sprite_33cl", name: 'Sprite 33cl', price: 2.00, imageLink: 'src/assets/menu/sprite_33cl.jpg', description:"", category:"DRINKS" },
    { id: "coca_cola_grande", name: 'Coca cola grande', price: 4.50, imageLink: 'src/assets/menu/coca_cola_grande.jpg', description:"", category:"DRINKS" },
    { id: "the_freddo_limone_pesca_33cl", name: 'The freddo limone / pesca 33cl', price: 2.00, imageLink: 'src/assets/menu/the_freddo_limone_pesca_33cl.jpg', description:"", category:"DRINKS" },
    { id: "the_caldo_gelsomino_verde", name: 'The caldo gelsomino / verde', price: 2.00, imageLink: 'src/assets/menu/the_caldo_gelsomino_verde.jpg', description:"", category:"DRINKS" },
    { id: "acqua_minerale_1l", name: 'Acqua minerale 1l', price: 2.00, imageLink: 'src/assets/menu/acqua_minerale_1l.jpg', description:"", category:"DRINKS" },
    { id: "acqua_minerale_0.5l", name: 'Acqua minerale 0.5l', price: 1.00, imageLink: 'src/assets/menu/acqua_minerale_0.5l.jpg', description:"", category:"DRINKS" },
    { id: "liquore_di_fragola", name: 'Liquore di fragola / mela verde / Baileys', price: 2.10, imageLink: 'src/assets/menu/liquore_di_fragola.jpg', description:"", category:"DRINKS" },
    { id: "limoncello_amaro_sambuca", name: 'Limoncello / amaro / sambuca', price: 2.10, imageLink: 'src/assets/menu/limoncello_amaro_sambuca.jpg', description:"", category:"DRINKS" },
    { id: "grappa_italiana_whiskey", name: 'Grappa italiana, whiskey', price: 2.10, imageLink: 'src/assets/menu/grappa_italiana_whiskey.jpg', description:"", category:"DRINKS" },
    { id: "ponce_livornese", name: 'Ponce Livornese', price: 3.50, imageLink: 'src/assets/menu/ponce_livornese.jpg', description:"", category:"DRINKS" },
    { id: "liquore_cinese", name: 'Liquore cinese (bambù, riso, rosa, ginseng, prugna)', price: 1.50, imageLink: 'src/assets/menu/liquore_cinese.jpg', description:"", category:"DRINKS" },
    { id: "amaro_cinese_alle_cinque_erbe", name: 'Amaro cinese alle cinque erbe', price: 1.50, imageLink: 'src/assets/menu/amaro_cinese_alle_cinque_erbe.jpg', description:"", category:"DRINKS" },
    { id: "sake", name: 'Sake', price: 2.00, imageLink: 'src/assets/menu/sake.jpg', description:"", category:"DRINKS" },
    { id: "caffe", name: 'Caffè', price: 1.20, imageLink: 'src/assets/menu/caffe.jpg', description:"", category:"DRINKS" },
    { id: "caffe_macchiato", name: 'Caffè macchiato', price: 1.40, imageLink: 'src/assets/menu/caffe_macchiato.jpg', description:"", category:"DRINKS" },
    { id: "caffe_corretto", name: 'Caffè corretto', price: 1.60, imageLink: 'src/assets/menu/caffe_corretto.jpg', description:"", category:"DRINKS" },
    { id: "caffe_d_orzo", name: 'Caffè d’orzo', price: 1.60, imageLink: 'src/assets/menu/caffe_d_orzo.jpg', description:"", category:"DRINKS" },
    { id: "caffe_decaffeinato", name: 'Caffè decaffeinato', price: 1.60, imageLink: 'src/assets/menu/caffe_decaffeinato.jpg', description:"", category:"DRINKS" },
    { id: "caffe_ginseng", name: 'Caffè GinSeng', price: 1.60, imageLink: 'src/assets/menu/caffe_ginseng.jpg', description:"", category:"DRINKS" },
    { id: "cappuccino", name: 'Cappuccino', price: 1.80, imageLink: 'src/assets/menu/cappuccino.jpg', description:"", category:"DRINKS" },

                                 
]

export default MenuEn;