const path="/menu/"
const MenuEn=[
    { id: "0", name: 'Fried Chinese bread', price: 1.00, imageLink: `${path}0.jpg`, description:"", category:"STARTERS" },
    { id: "0A", name: 'Steamed Chinese bread', price: 1.00, imageLink: `${path}0A.jpg`, description:"", category:"STARTERS" },
    { id: "1", name: 'Spring rolls', price: 1.50, imageLink: `${path}1.jpg`, description:"", category:"STARTERS" },
    { id: "1A", name: 'Special rolls', price: 1.80, imageLink: `${path}1A.jpg`, description:"", category:"STARTERS" },
    { id: "2", name: 'Fried wanton', price: 1.60, imageLink: `${path}2.jpg`, description:"", category:"STARTERS" },
    { id: "3", name: 'Lobster slices', price: 1.50, imageLink: `${path}3.jpg`, description:"", category:"STARTERS" },
    { id: "4", name: 'Fried seaweed', price: 3.00, imageLink: `${path}4.jpg`, description:"", category:"STARTERS" },
    { id: "5", name: 'Potato chips', price: 2.00, imageLink: `${path}5.jpg`, description:"", category:"STARTERS" },
    { id: "5A", name: 'Bruschetta with tomato', price: 2.60, imageLink: `${path}5A.jpg`, description:"", category:"STARTERS" },
    { id: "6", name: 'Chips', price: 2.50, imageLink: `${path}6.jpg`, description:"", category:"STARTERS" },
    { id: "7", name: 'Shrimp toast', price: 2.50, imageLink: `${path}7.jpg`, description:"", category:"STARTERS" },
    { id: "8", name: 'Chinese pizza', price: 3.00, imageLink: `${path}8.jpg`, description:"", category:"STARTERS" },
    { id: "9", name: 'Steamed meat dumplings', price: 3.20, imageLink: `${path}9.jpg`, description:"", category:"STARTERS" },
    { id: "10", name: 'Steamed vegetable dumplings', price: 3.40, imageLink: `${path}10.jpg`, description:"", category:"STARTERS" },
    { id: "11", name: 'Grilled meat dumplings', price: 3.60, imageLink: `${path}11.jpg`, description:"", category:"STARTERS" },
    { id: "12", name: 'Xiao mai of shrimps', price: 3.80, imageLink: `${path}12.jpg`, description:"", category:"STARTERS" },
    { id: "12A", name: 'Crystal dumplings', price: 3.80, imageLink: `${path}12A.jpg`, description:"", category:"STARTERS" },
    { id: "12B", name: 'Mixed dumplings (View 9,10,12)', price: 3.80, imageLink: `${path}12B.jpg`, description:"", category:"STARTERS" },
    { id: "12C", name: 'Felicità dumplings', price: 3.80, imageLink: `${path}12C.jpg`, description:"", category:"STARTERS" },
    { id: "13", name: 'Mixed hot starters (View 1,2,3,5,7)', price: 4.00, imageLink: `${path}13.jpg`, description:"", category:"STARTERS" },
    { id: "14", name: 'Fried vegetables', price: 3.00, imageLink: `${path}14.jpg`, description:"", category:"STARTERS" },
    { id: "14A", name: 'Meatballs of shrimps with sesame', price: 3.50, imageLink: `${path}14A.jpg`, description:"", category:"STARTERS" },
    { id: "14B", name: 'Fried onion rings', price: 3.00, imageLink: `${path}14B.jpg`, description:"", category:"STARTERS" },
    { id: "14C", name: 'Soybeans', price: 3.50, imageLink: `${path}14C.jpg`, description:"", category:"STARTERS" },
    { id: "15", name: 'Chinese seaweed salad', price: 3.00, imageLink: `${path}15.jpg`, description:"", category:"SALAD" },
    { id: "16", name: 'Chicken and mayonnaise salad', price: 3.50, imageLink: `${path}16.jpg`, description:"", category:"SALAD" },
    { id: "17", name: 'Shrimp and mayonnaise salad', price: 3.50, imageLink: `${path}17.jpg`, description:"", category:"SALAD" },
    { id: "17A", name: 'Flesh crab meat and mayonnaise salad', price: 3.50, imageLink: `${path}17A.jpg`, description:"", category:"SALAD" },
    { id: "17B", name: 'Mixed salad', price: 3.00, imageLink: `${path}17B.jpg`, description:"", category:"SALAD" },
    { id: "17C", name: 'Salad with prawns and peanuts in special sauce', price: 4.00, imageLink: `${path}17C.jpg`, description:"", category:"SALAD" },
    { id: "17D", name: 'Mixed seafood salad', price: 6.00, imageLink: `${path}17D.jpg`, description:"", category:"SALAD" },
    { id: "17E", name: 'Salad with shrimp, crab meat and mayonnaise', price: 4.00, imageLink: `${path}17E.jpg`, description:"", category:"SALAD" },
    { id: "18", name: 'Oriental soup', price: 3.00, imageLink: `${path}18.jpg`, description:"", category:"SOUP" },
    { id: "19", name: 'Wanton soup', price: 3.00, imageLink: `${path}19.jpg`, description:"", category:"SOUP" },
    { id: "19A", name: 'Felicità soup', price: 3.50, imageLink: `${path}19A.jpg`, description:"", category:"SOUP" },
    { id: "20", name: 'Chicken soup with Chinese mushrooms and bamboo', price: 3.00, imageLink: `${path}20.jpg`, description:"", category:"SOUP" },
    { id: "21", name: 'Hot and sour soup', price: 3.00, imageLink: `${path}21.jpg`, description:"", category:"SOUP" },
    { id: "22", name: 'Soy noodles soup with zazai', price: 3.00, imageLink: `${path}22.jpg`, description:"", category:"SOUP" },
    { id: "23", name: 'Corn and chicken soup', price: 3.00, imageLink: `${path}23.jpg`, description:"", category:"SOUP" },
    { id: "24", name: 'Crab meat and asparagus soup', price: 3.50, imageLink: `${path}24.jpg`, description:"", category:"SOUP" },
    { id: "25A", name: 'Vegetable soup with toufu', price: 3.00, imageLink: `${path}25A.jpg`, description:"", category:"SOUP" },
    { id: "25B", name: 'Miso soup', price: 3.00, imageLink: `${path}25B.jpg`, description:"", category:"SOUP" },
    { id: "25C", name: 'Mixed seafood soup', price: 3.80, imageLink: `${path}25C.jpg`, description:"", category:"SOUP" },
    { id: "25D", name: 'Thai style shrimp soup', price: 3.80, imageLink: `${path}25D.jpg`, description:"", category:"SOUP" },
    { id: "25E", name: 'Thai style chicken soup', price: 3.80, imageLink: `${path}25E.jpg`, description:"", category:"SOUP" },
    { id: "26", name: 'Noodles with mixed vegetables', price: 3.50, imageLink: `${path}26.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "26A", name: 'Udon with vegetables', price: 4.00, imageLink: `${path}26A.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "26B", name: 'Udon with seafood', price: 5.50, imageLink: `${path}26B.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "26C", name: 'Noodles in broth with seafood', price: 6.00, imageLink: `${path}26C.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "26D", name: 'Noodles in broth with meat', price: 6.00, imageLink: `${path}26D.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "27", name: 'Noodles with shrimp', price: 4.20, imageLink: `${path}27.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "28", name: 'Noodles with vegetables on the steel', price: 4.00, imageLink: `${path}28.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "28A", name: 'Tan tan mian', price: 4.00, imageLink: `${path}28A.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "28B", name: 'Noodles with meat and vegetables on the steel', price: 4.50, imageLink: `${path}28B.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "28C", name: 'Tan tan fan', price: 4.00, imageLink: `${path}28C.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "29", name: 'Noodles with seafood on the steel', price: 4.90, imageLink: `${path}29.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "29A", name: 'Soy noodles with seafood on the steel', price: 4.90, imageLink: `${path}29A.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "29B", name: 'Rice noodles with seafood on the steel', price: 4.90, imageLink: `${path}29B.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "30", name: 'Fried noodles with vegetables', price: 3.50, imageLink: `${path}30.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "30A", name: 'Fried noodles with seafood', price: 4.90, imageLink: `${path}30A.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "31", name: 'Rice noodles with mixed vegetables', price: 3.50, imageLink: `${path}31.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "31A", name: 'Rice noodles with seafood and vegetables', price: 4.90, imageLink: `${path}31A.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "31B", name: 'Rice noodles with shrimps and vegetables', price: 4.20, imageLink: `${path}31B.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "32", name: 'Rice noodles with pork and vegetables', price: 4.00, imageLink: `${path}32.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "33", name: 'Rice noodles with curry sauce', price: 3.50, imageLink: `${path}33.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "34", name: 'Soy noodles with pork and spicy sauce', price: 4.00, imageLink: `${path}34.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "35", name: 'Soy noodles with mixed vegetables', price: 3.50, imageLink: `${path}35.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "35A", name: 'Soy noodles with shrimps and vegetables', price: 4.20, imageLink: `${path}35A.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "36", name: 'Sliced rice cake with vegetables', price: 3.80, imageLink: `${path}36.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "36A", name: 'Sliced rice cake with seafood', price: 5.00, imageLink: `${path}36A.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "36B", name: 'Sliced rice cake with pork and vegetables', price: 4.30, imageLink: `${path}36B.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "37", name: 'Rice with shrimps', price: 4.20, imageLink: `${path}37.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "38", name: 'Rice with mixed vegetables', price: 3.50, imageLink: `${path}38.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "39", name: 'Cantonese style rice', price: 3.50, imageLink: `${path}39.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "39A", name: 'Rice with chicken', price: 3.50, imageLink: `${path}39A.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "40", name: 'Rice with curry sauce', price: 3.50, imageLink: `${path}40.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "41", name: 'Rice with pineapple and pine nuts', price: 4.00, imageLink: `${path}41.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "42", name: 'White rice', price: 1.50, imageLink: `${path}42.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "42A", name: 'Crispy rice with mixed meat', price: 4.50, imageLink: `${path}42A.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "42B", name: 'Crispy rice with seafood', price: 4.90, imageLink: `${path}42B.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "42C", name: 'Pasta with tomatoes', price: 3.50, imageLink: `${path}42C.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "42D", name: 'Pasta with ragù', price: 3.50, imageLink: `${path}42D.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "42E", name: 'Rice with seafood', price: 4.90, imageLink: `${path}42E.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "42F", name: 'Ziao fan with meat and seafood', price: 5.00, imageLink: `${path}42F.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "42G", name: 'Ziao mian with meat and seafood', price: 5.00, imageLink: `${path}42G.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "42H", name: 'Thai style noodles', price: 4.50, imageLink: `${path}42H.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "42L", name: 'Thai style rice', price: 4.50, imageLink: `${path}42L.jpg`, description:"", category:"NOODLES&RICE" },
    { id: "43", name: 'Shrimps with bamboo and Chinese mushrooms', price: 6.00, imageLink: `${path}43.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "44", name: 'Shrimps with mixed vegetables', price: 6.00, imageLink: `${path}44.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "45", name: 'Shrimps with peas', price: 6.00, imageLink: `${path}45.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "45A", name: 'Shrimps with cashew nuts', price: 6.00, imageLink: `${path}45A.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "46", name: 'Shrimps with curry sauce', price: 6.00, imageLink: `${path}46.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "47", name: 'Shrimps in hot sauce', price: 6.00, imageLink: `${path}47.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "47A", name: 'Shrimps with KongBao and spicy sauces', price: 6.00, imageLink: `${path}47A.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "48", name: 'Fried shrimps in sweet and sour sauce', price: 6.00, imageLink: `${path}48.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "48A", name: 'Unfried shrimps in sweet and sour sauce', price: 6.00, imageLink: `${path}48A.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "49", name: 'Shrimps with apples', price: 6.00, imageLink: `${path}49.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "49A", name: 'Shrimps with orange', price: 6.00, imageLink: `${path}49A.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "49B", name: 'Shrimps with lemons', price: 6.00, imageLink: `${path}49B.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "49C", name: 'Shrimps with ananas', price: 6.00, imageLink: `${path}49C.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "50", name: 'Fried shrimps', price: 6.00, imageLink: `${path}50.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "50A", name: 'Fried shrimps with sesame', price: 6.50, imageLink: `${path}50A.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "51", name: 'Grilled shrimps with pepper', price: 6.50, imageLink: `${path}51.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "52", name: 'Shrimps with leeks and carrots on the steel', price: 6.50, imageLink: `${path}52.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "53A", name: 'Shrimp nest with vegetables', price: 6.50, imageLink: `${path}53A.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "53B", name: 'Mixed seafood nest', price: 6.50, imageLink: `${path}53B.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "53C", name: 'Squid and shrimp skewers', price: 7.00, imageLink: `${path}53C.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "53D", name: 'Shrimp skewers', price: 7.00, imageLink: `${path}53D.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "53E", name: 'Squid skewers', price: 7.00, imageLink: `${path}53E.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "53F", name: 'Thai style crustaceans', price: 7.00, imageLink: `${path}53F.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "53G", name: 'Crustaceans with sate sauce', price: 7.00, imageLink: `${path}53G.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "54", name: 'Prawns in hot sauce', price: 6.50, imageLink: `${path}54.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "55", name: 'Steamed prawns', price: 6.50, imageLink: `${path}55.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "56", name: 'Prawns stewed in Chinese sauce', price: 6.50, imageLink: `${path}56.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "57", name: 'Fried prawns with sesame', price: 6.50, imageLink: `${path}57.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "57A", name: 'Imperial fried shrimps', price: 7.00, imageLink: `${path}57A.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "58", name: 'Grilled prawns on the steel (6 pieces)', price: 9.00, imageLink: `${path}58.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "59", name: 'Grilled prawns with leeks and carrots on the steel', price: 9.00, imageLink: `${path}59.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "59A", name: 'Salt and pepper prawns on the steel', price: 9.00, imageLink: `${path}59A.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "59B", name: 'Flambè prawns on the steel', price: 9.00, imageLink: `${path}59B.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "60", name: 'Mixed seafood with spicy sauce on the steel', price: 7.00, imageLink: `${path}60.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "61", name: 'Fish fillets with lemon sauce', price: 6.00, imageLink: `${path}61.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "62", name: 'Steamed fish fillets', price: 6.00, imageLink: `${path}62.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "63", name: 'Grilled fish(whole)', price: 10.00, imageLink: `${path}63.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "64", name: 'Steamed fish(whole)', price: 10.00, imageLink: `${path}64.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "65", name: 'Stewed fish with Chinese sauce (whole)', price: 10.00, imageLink: `${path}65.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "66", name: 'Squid in hot sauce', price: 6.00, imageLink: `${path}66.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "67", name: 'Fried squid in sweet and sour sauce', price: 6.00, imageLink: `${path}67.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "67A", name: 'Unfried squid in sweet and sour sauce', price: 6.00, imageLink: `${path}67A.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "68", name: 'Squid with mixed vegetables', price: 6.00, imageLink: `${path}68.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "68A", name: 'Squid with leeks and carrots on the steel', price: 6.50, imageLink: `${path}68A.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "69", name: 'Fried frog legs', price: 7.50, imageLink: `${path}69.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "70", name: 'Frogs legs on the steel', price: 7.50, imageLink: `${path}70.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "71", name: 'Fried crab claws (5 Pieces)', price: 6.50, imageLink: `${path}71.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "71A", name: 'Steamed crab', price: 9.00, imageLink: `${path}71A.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "71B", name: 'Crab stewed in Chinese sauce', price: 9.00, imageLink: `${path}71B.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "71C", name: 'Granchio with pepper and salt', price: 9.00, imageLink: `${path}71C.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "72", name: 'Fried seafood', price: 6.00, imageLink: `${path}72.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "73", name: 'Clay pot of seafoods', price: 7.00, imageLink: `${path}73.jpg`, description:"", category:"CRUSTACEANS&FISH" },
    { id: "74", name: "Fried chicken in sweet and sour sauce", price: 5.00, imageLink: `${path}74.jpg`, description: "", category: "CHICKEN" },
    { id: "74A", name: "Chicken with green peppers", price: 5.00, imageLink: `${path}74A.jpg`, description: "", category: "CHICKEN" },
    { id: "74B", name: "Unfried chicken in sweet and sour sauce", price: 5.00, imageLink: `${path}74B.jpg`, description: "", category: "CHICKEN" },
    { id: "75", name: "Fried chicken with lemon sauce", price: 5.00, imageLink: `${path}75.jpg`, description: "", category: "CHICKEN" },
    { id: "75A", name: "Unfried chicken with lemon sauce", price: 5.00, imageLink: `${path}75A.jpg`, description: "", category: "CHICKEN" },
    { id: "75B", name: "Chicken with asparagus", price: 5.00, imageLink: `${path}75B.jpg`, description: "", category: "CHICKEN" },
    { id: "75C", name: "Chicken with celery", price: 5.00, imageLink: `${path}75C.jpg`, description: "", category: "CHICKEN" },
    { id: "76", name: "Fried chicken with orange sauce", price: 5.00, imageLink: `${path}76.jpg`, description: "", category: "CHICKEN" },
    { id: "76A", name: "Unfried chicken with orange sauce", price: 5.00, imageLink: `${path}76A.jpg`, description: "", category: "CHICKEN" },
    { id: "77", name: "Chicken with soy bean sprouts", price: 5.00, imageLink: `${path}77.jpg`, description: "", category: "CHICKEN" },
    { id: "78", name: "Chicken with almonds", price: 5.00, imageLink: `${path}78.jpg`, description: "", category: "CHICKEN" },
    { id: "78A", name: "Chicken with cashew nuts", price: 5.00, imageLink: `${path}78A.jpg`, description: "", category: "CHICKEN" },
    { id: "79", name: "Chicken with KongBao and spicy sauces", price: 5.00, imageLink: `${path}79.jpg`, description: "", category: "CHICKEN" },
    { id: "80", name: "Roasted chicken with Chinese aromas", price: 5.50, imageLink: `${path}80.jpg`, description: "", category: "CHICKEN" },
    { id: "81", name: "Roasted chicken in Chinese sauce", price: 5.50, imageLink: `${path}81.jpg`, description: "", category: "CHICKEN" },
    { id: "82", name: "Chicken with bamboo and Chinese mushrooms", price: 5.00, imageLink: `${path}82.jpg`, description: "", category: "CHICKEN" },
    { id: "83", name: "Chicken with pineapple", price: 5.00, imageLink: `${path}83.jpg`, description: "", category: "CHICKEN" },
    { id: "84", name: "Chicken with curry sauce", price: 5.00, imageLink: `${path}84.jpg`, description: "", category: "CHICKEN" },
    { id: "85", name: "Fried chicken morsels", price: 5.00, imageLink: `${path}85.jpg`, description: "", category: "CHICKEN" },
    { id: "85A", name: "Fried breaded chicken", price: 5.50, imageLink: `${path}85A.jpg`, description: "", category: "CHICKEN" },
    { id: "85B", name: "Fried chicken with sesame", price: 6.00, imageLink: `${path}85B.jpg`, description: "", category: "CHICKEN" },
    { id: "86", name: "Chicken with shrimps and Chinese mushrooms", price: 6.00, imageLink: `${path}86.jpg`, description: "", category: "CHICKEN" },
    { id: "87", name: "Potato basket with chicken and pine nuts", price: 5.50, imageLink: `${path}87.jpg`, description: "", category: "CHICKEN" },
    { id: "88", name: "Chicken with leeks and carrots on the steel", price: 5.50, imageLink: `${path}88.jpg`, description: "", category: "CHICKEN" },
    { id: "88A", name: "Chicken with potatoes in the steel", price: 5.50, imageLink: `${path}88A.jpg`, description: "", category: "CHICKEN" },
    { id: "88B", name: "Mixed meat skewers (beef & chicken)", price: 6.00, imageLink: `${path}88B.jpg`, description: "", category: "CHICKEN" },
    { id: "88C", name: "Beef skewers", price: 6.00, imageLink: `${path}88C.jpg`, description: "", category: "CHICKEN" },
    { id: "88D", name: "Chicken skewers", price: 6.00, imageLink: `${path}88D.jpg`, description: "", category: "CHICKEN" },
    { id: "88E", name: "Thai style meat", price: 6.00, imageLink: `${path}88E.jpg`, description: "", category: "CHICKEN" },
    { id: "88F", name: "Meat with sate sauce", price: 6.00, imageLink: `${path}88F.jpg`, description: "", category: "CHICKEN" },
    { id: "88G", name: "Clay pot of meat", price: 6.00, imageLink: `${path}88G.jpg`, description: "", category: "CHICKEN" },
    { id: "89", name: "Roasted duck with pineapple", price: 6.50, imageLink: `${path}89.jpg`, description: "", category: "DUCK" },
    { id: "89A", name: "Duck with lemon sauce", price: 6.50, imageLink: `${path}89A.jpg`, description: "", category: "DUCK" },
    { id: "89B", name: "Duck with orange sauce", price: 6.50, imageLink: `${path}89B.jpg`, description: "", category: "DUCK" },
    { id: "90", name: "Roasted duck with Chinese aromas", price: 6.50, imageLink: `${path}90.jpg`, description: "", category: "DUCK" },
    { id: "91", name: "Duck with bamboo and Chinese mushrooms", price: 6.50, imageLink: `${path}91.jpg`, description: "", category: "DUCK" },
    { id: "91A", name: "Duck in sweet and sour sauce", price: 6.50, imageLink: `${path}91A.jpg`, description: "", category: "DUCK" },
    { id: "91B", name: "Duck in the hot sauce", price: 6.50, imageLink: `${path}91B.jpg`, description: "", category: "DUCK" },
    { id: "92", name: "Peking duck", price: 9.00, imageLink: `${path}92.jpg`, description: "", category: "DUCK" },
    { id: "92A", name: "Peking lacquered duck (order a day before)", price: 40.00, imageLink: `${path}92A.jpg`, description: "", category: "DUCK" },
    { id: "92B", name: "Duck with leeks and carrots on the steel", price: 7.00, imageLink: `${path}92B.jpg`, description: "", category: "DUCK" },
    { id: "93", name: "Pork in sweet and sour sauce", price: 5.00, imageLink: `${path}93.jpg`, description: "", category: "PORK" },
    { id: "94", name: "Pork with bamboo and Chinese mushrooms", price: 5.00, imageLink: `${path}94.jpg`, description: "", category: "PORK" },
    { id: "95", name: "Pork with soy bean sprouts", price: 5.00, imageLink: `${path}95.jpg`, description: "", category: "PORK" },
    { id: "96", name: "Pork in the hot sauce", price: 5.00, imageLink: `${path}96.jpg`, description: "", category: "PORK" },
    { id: "96A", name: "Pork with KongBao and spicy sauces", price: 5.00, imageLink: `${path}96A.jpg`, description: "", category: "PORK" },
    { id: "96B", name: "Pork with za zai", price: 5.00, imageLink: `${path}96B.jpg`, description: "", category: "PORK" },
    { id: "97", name: "Fried pork’s ribs", price: 5.00, imageLink: `${path}97.jpg`, description: "", category: "PORK" },
    { id: "97A", name: "Pork with leeks and carrots on the steel", price: 5.50, imageLink: `${path}97A.jpg`, description: "", category: "PORK" },
    { id: "97B", name: "Pork with potatoes on the steel", price: 5.50, imageLink: `${path}97B.jpg`, description: "", category: "PORK" },
    { id: "97C", name: "Porks’s ribs in sweet and sour sauce", price: 5.50, imageLink: `${path}97C.jpg`, description: "", category: "PORK" },
    { id: "97D", name: "Pepper and salt ribs", price: 5.50, imageLink: `${path}97D.jpg`, description: "", category: "PORK" },
    { id: "98", name: "Beef in oyster sauce", price: 5.50, imageLink: `${path}98.jpg`, description: "", category: "BEEF" },
    { id: "98A", name: "Beef in sweet and sour sauce", price: 5.50, imageLink: `${path}98A.jpg`, description: "", category: "BEEF" },
    { id: "99", name: "Beef with bamboo and Chinese mushrooms", price: 5.50, imageLink: `${path}99.jpg`, description: "", category: "BEEF" },
    { id: "100", name: "Beef with ginger and leeks", price: 5.50, imageLink: `${path}100.jpg`, description: "", category: "BEEF" },
    { id: "101", name: "Beef with curry sauce", price: 5.50, imageLink: `${path}101.jpg`, description: "", category: "BEEF" },
    { id: "102", name: "Beef with mixed vegetables", price: 5.50, imageLink: `${path}102.jpg`, description: "", category: "BEEF" },
    { id: "103", name: "Beef with soy bean sprouts", price: 5.50, imageLink: `${path}103.jpg`, description: "", category: "BEEF" },
    { id: "104", name: "Beef in the hot sauce", price: 5.50, imageLink: `${path}104.jpg`, description: "", category: "BEEF" },
    { id: "105", name: "Crispy beef in the hot sauce", price: 5.50, imageLink: `${path}105.jpg`, description: "", category: "BEEF" },
    { id: "106", name: "Beef with leeks and carrots on the steel", price: 6.00, imageLink: `${path}106.jpg`, description: "", category: "BEEF" },
    { id: "107", name: "Mixed meat in spicy creamy sauce", price: 6.50, imageLink: `${path}107.jpg`, description: "", category: "BEEF" },
    { id: "107A", name: "Beef with potatoes on the steel", price: 6.00, imageLink: `${path}107A.jpg`, description: "", category: "BEEF" },
    { id: "107B", name: "Mixed meat with leeks and carrots on the steel", price: 6.00, imageLink: `${path}107B.jpg`, description: "", category: "BEEF" },
    { id: "108", name: "Bamboo and Chinese mushrooms", price: 3.50, imageLink: `${path}108.jpg`, description: "", category: "VEGETABLES" },
    { id: "109", name: "Mixed vegetables", price: 3.50, imageLink: `${path}109.jpg`, description: "", category: "VEGETABLES" },
    { id: "109A", name: "Si-Chuang style vegetables with hot sauce", price: 3.50, imageLink: `${path}109A.jpg`, description: "", category: "VEGETABLES" },
    { id: "109B", name: "Grilled mixed vegetables", price: 3.50, imageLink: `${path}109B.jpg`, description: "", category: "VEGETABLES" },
    { id: "110", name: "Soy bean sprouts", price: 3.50, imageLink: `${path}110.jpg`, description: "", category: "VEGETABLES" },
    { id: "111", name: "Eggplants in Chinese piccante sauce", price: 3.50, imageLink: `${path}111.jpg`, description: "", category: "VEGETABLES" },
    { id: "111A", name: "Potatoes on the steel", price: 4.00, imageLink: `${path}111A.jpg`, description: "", category: "VEGETABLES" },
    { id: "111B", name: "Roasted potato cubes", price: 4.00, imageLink: `${path}111B.jpg`, description: "", category: "VEGETABLES" },
    { id: "112", name: "Omelet with crab meat", price: 3.50, imageLink: `${path}112.jpg`, description: "", category: "OMELET" },
    { id: "113", name: "Omelets with shrimps", price: 3.50, imageLink: `${path}113.jpg`, description: "", category: "OMELET" },
    { id: "114", name: "Omelets with ham", price: 3.50, imageLink: `${path}114.jpg`, description: "", category: "OMELET" },
    { id: "114A", name: "Omelets with leeks", price: 3.50, imageLink: `${path}114A.jpg`, description: "", category: "OMELET" },
    { id: "115", name: "Tou fu with bamboo and Chinese mushrooms", price: 4.00, imageLink: `${path}115.jpg`, description: "", category: "TOUFU" },
    { id: "116", name: "Tou fu in the hot sauce", price: 4.00, imageLink: `${path}116.jpg`, description: "", category: "TOUFU" },
    { id: "117", name: "Tou fu on the steel", price: 4.00, imageLink: `${path}117.jpg`, description: "", category: "TOUFU" },
    { id: "118", name: "Tou fu with shrimps and Chinese mushrooms", price: 5.50, imageLink: `${path}118.jpg`, description: "", category: "TOUFU" },
    { id: "118A", name: "Tou fu with beef", price: 5.50, imageLink: `${path}118A.jpg`, description: "", category: "TOUFU" },
    { id: "118C", name: "Tou fu in sweet and sour sauce", price: 3.50, imageLink: `${path}118C.jpg`, description: "", category: "TOUFU" },
    { id: "118D", name: "Clay pot of tou fu with seafood", price: 6.00, imageLink: `${path}118D.jpg`, description: "", category: "TOUFU" },
    { id: "119", name: "Fried mixed fruit", price: 3.00, imageLink: `${path}119.jpg`, description: "", category: "DESSERT" },
    { id: "119A", name: "Fried banana", price: 3.00, imageLink: `${path}119A.jpg`, description: "", category: "DESSERT" },
    { id: "119B", name: "Fried apple", price: 3.00, imageLink: `${path}119B.jpg`, description: "", category: "DESSERT" },
    { id: "119C", name: "Fried pineapple", price: 3.00, imageLink: `${path}119C.jpg`, description: "", category: "DESSERT" },
    { id: "120", name: "Fried fruit with ice cream", price: 4.00, imageLink: `${path}120.jpg`, description: "", category: "DESSERT" },
    { id: "121", name: "Caramelized mixed fruit", price: 3.50, imageLink: `${path}121.jpg`, description: "", category: "DESSERT" },
    { id: "122", name: "Caramelized mixed fruit with ice cream", price: 4.50, imageLink: `${path}122.jpg`, description: "", category: "DESSERT" },
    { id: "123", name: "Fried coconut", price: 3.00, imageLink: `${path}123.jpg`, description: "", category: "DESSERT" },
    { id: "123A", name: "Steamed coconut", price: 3.00, imageLink: `${path}123A.jpg`, description: "", category: "DESSERT" },
    { id: "123B", name: "Steamed coconut with ice cream", price: 4.00, imageLink: `${path}123B.jpg`, description: "", category: "DESSERT" },
    { id: "124", name: "Fried coconut with ice cream", price: 4.00, imageLink: `${path}124.jpg`, description: "", category: "DESSERT" },
    { id: "125", name: "Fried nutella", price: 3.00, imageLink: `${path}125.jpg`, description: "", category: "DESSERT" },
    { id: "125A", name: "Fried nutella with ice cream", price: 4.00, imageLink: `${path}125A.jpg`, description: "", category: "DESSERT" },
    { id: "125B", name: "Steamed nutella", price: 3.00, imageLink: `${path}125B.jpg`, description: "", category: "DESSERT" },
    { id: "125C", name: "Steamed nutella with ice cream", price: 4.00, imageLink: `${path}125C.jpg`, description: "", category: "DESSERT" },
    { id: "126", name: "Chinese fruit", price: 3.00, imageLink: `${path}126.jpg`, description: "", category: "DESSERT" },
    { id: "127", name: "Chinese fruit with ice cream", price: 4.00, imageLink: `${path}127.jpg`, description: "", category: "DESSERT" },
    { id: "128", name: "Fried ice cream (Cream)", price: 3.00, imageLink: `${path}128.jpg`, description: "", category: "DESSERT" },
    { id: "128A", name: "Fried ice cream (Chocolate)", price: 3.00, imageLink: `${path}128A.jpg`, description: "", category: "DESSERT" },
    { id: "129", name: "Mix of ice cream", price: 3.00, imageLink: `${path}129.jpg`, description: "", category: "DESSERT" },
    { id: "130", name: "White truffle", price: 3.50, imageLink: `${path}130.jpg`, description: "", category: "DESSERT" },
    { id: "130A", name: "Black truffle", price: 3.50, imageLink: `${path}130A.jpg`, description: "", category: "DESSERT" },
    { id: "130B", name: "Truffle drowned with coffee", price: 4.50, imageLink: `${path}130B.jpg`, description: "", category: "DESSERT" },
    { id: "130C", name: "Truffle drowned with whiskey", price: 4.50, imageLink: `${path}130C.jpg`, description: "", category: "DESSERT" },
    { id: "130D", name: "Tiramisù", price: 3.50, imageLink: `${path}130D.jpg`, description: "", category: "DESSERT" },
    { id: "131", name: "Stuffed ice cream (Lemon)", price: 4.50, imageLink: `${path}131.jpg`, description: "", category: "DESSERT" },
    { id: "131A", name: "Stufed ice cream (Coconut)", price: 4.50, imageLink: `${path}131A.jpg`, description: "", category: "DESSERT" },
    { id: "132", name: "Semifreddo cake", price: 3.80, imageLink: `${path}132.jpg`, description: "", category: "DESSERT" },
    { id: "133", name: "Fried milk", price: 3.00, imageLink: `${path}133.jpg`, description: "", category: "DESSERT" },
    { id: "133A", name: "Fried milk with ice cream", price: 4.00, imageLink: `${path}133A.jpg`, description: "", category: "DESSERT" },
    { id: "133B", name: "Caramelized milk", price: 3.50, imageLink: `${path}133B.jpg`, description: "", category: "DESSERT" },
    { id: "134", name: "Fresh pineapple", price: 3.50, imageLink: `${path}134.jpg`, description: "", category: "DESSERT" },
    { id: "135", name: "Strawberries with cream", price: 3.50, imageLink: `${path}135.jpg`, description: "", category: "DESSERT" },
    { id: "137", name: "Sushi dessert", price: 4.00, imageLink: `${path}137.jpg`, description: "", category: "DESSERT" },
    { id: "139", name: "Mattonella pine nuts", price: 4.00, imageLink: `${path}139.jpg`, description: "", category: "DESSERT" },
    { id: "140", name: "Sgroppino", price: 3.50, imageLink: `${path}140.jpg`, description: "", category: "DESSERT" },
    { id: "141", name: "Fresh Panna Cotta", price: 3.50, imageLink: `${path}141.jpg`, description: "", category: "DESSERT" },
    { id: "pinot_grigio", name: 'Pinot grigio', price: 7.90, imageLink: `${path}pinot_grigio.jpg`, description:"", category:"DRINKS" },
    { id: "chardonnay", name: 'Chardonnay', price: 7.90, imageLink: `${path}chardonnay.jpg`, description:"", category:"DRINKS" },
    { id: "verdicchio", name: 'Verdicchio', price: 8.90, imageLink: `${path}verdicchio.jpg`, description:"", category:"DRINKS" },
    { id: "vernaccia_di_san_gimignano", name: 'Vernaccia di san gimignano', price: 8.90, imageLink: `${path}vernaccia_di_san_gimignano.jpg`, description:"", category:"DRINKS" },
    { id: "mateus_rose", name: 'Mateus rose', price: 7.90, imageLink: `${path}mateus_rose.jpg`, description:"", category:"DRINKS" },
    { id: "lancers_rose", name: 'Lancers rose', price: 7.90, imageLink: `${path}lancers_rose.jpg`, description:"", category:"DRINKS" },
    { id: "santa_cristina", name: 'Santa cristina', price: 12.90, imageLink: `${path}santa_cristina.jpg`, description:"", category:"DRINKS" },
    { id: "chianti_rosso", name: 'Chianti rosso', price: 7.90, imageLink: `${path}chianti_rosso.jpg`, description:"", category:"DRINKS" },
    { id: "vino_della_casa_1l", name: 'Vino della casa 1l (Bianco/Rosso)', price: 6.00, imageLink: `${path}vino_della_casa_1l.jpg`, description:"", category:"DRINKS" },
    { id: "vino_della_casa_0.5l", name: 'Vino della casa 0.5l (Bianco/Rosso)', price: 3.50, imageLink: `${path}vino_della_casa_0.5l.jpg`, description:"", category:"DRINKS" },
    { id: "vino_della_casa_0.25L", name: 'Vino della casa 0.25L (Bianco/Rosso)', price: 2.00, imageLink: `${path}vino_della_casa_0.25L.jpg`, description:"", category:"DRINKS" },
    { id: "birra_moretti_66cl", name: 'Birra Moretti 66cl', price: 3.50, imageLink: `${path}birra_moretti_66cl.jpg`, description:"", category:"DRINKS" },
    { id: "birra_cinese_media", name: 'Birra cinese media', price: 4.00, imageLink: `${path}birra_cinese_media.jpg`, description:"", category:"DRINKS" },
    { id: "birra_tennents", name: 'Birra Tennent’s', price: 3.50, imageLink: `${path}birra_tennents.jpg`, description:"", category:"DRINKS" },
    { id: "birra_becks_33cl", name: 'Birra Becks 33cl', price: 2.50, imageLink: `${path}birra_becks_33cl.jpg`, description:"", category:"DRINKS" },
    { id: "coca_cola_33cl", name: 'Coca cola 33 cl /o Coca cola zero 33cl', price: 2.00, imageLink: `${path}coca_cola_33cl.jpg`, description:"", category:"DRINKS" },
    { id: "fanta_33cl", name: 'Fanta 33cl', price: 2.00, imageLink: `${path}fanta_33cl.jpg`, description:"", category:"DRINKS" },
    { id: "sprite_33cl", name: 'Sprite 33cl', price: 2.00, imageLink: `${path}sprite_33cl.jpg`, description:"", category:"DRINKS" },
    { id: "coca_cola_grande", name: 'Coca cola grande', price: 4.50, imageLink: `${path}coca_cola_grande.jpg`, description:"", category:"DRINKS" },
    { id: "the_freddo_limone_pesca_33cl", name: 'The freddo limone / pesca 33cl', price: 2.00, imageLink: `${path}the_freddo_limone_pesca_33cl.jpg`, description:"", category:"DRINKS" },
    { id: "the_caldo_gelsomino_verde", name: 'The caldo gelsomino / verde', price: 2.00, imageLink: `${path}the_caldo_gelsomino_verde.jpg`, description:"", category:"DRINKS" },
    { id: "acqua_minerale_1l", name: 'Acqua minerale 1l', price: 2.00, imageLink: `${path}acqua_minerale_1l.jpg`, description:"", category:"DRINKS" },
    { id: "acqua_minerale_0.5l", name: 'Acqua minerale 0.5l', price: 1.00, imageLink: `${path}acqua_minerale_0.5l.jpg`, description:"", category:"DRINKS" },
    { id: "liquore_di_fragola", name: 'Liquore di fragola / mela verde / Baileys', price: 2.10, imageLink: `${path}liquore_di_fragola.jpg`, description:"", category:"DRINKS" },
    { id: "limoncello_amaro_sambuca", name: 'Limoncello / amaro / sambuca', price: 2.10, imageLink: `${path}limoncello_amaro_sambuca.jpg`, description:"", category:"DRINKS" },
    { id: "grappa_italiana_whiskey", name: 'Grappa italiana, whiskey', price: 2.10, imageLink: `${path}grappa_italiana_whiskey.jpg`, description:"", category:"DRINKS" },
    { id: "ponce_livornese", name: 'Ponce Livornese', price: 3.50, imageLink: `${path}ponce_livornese.jpg`, description:"", category:"DRINKS" },
    { id: "liquore_cinese", name: 'Liquore cinese (bambù, riso, rosa, ginseng, prugna)', price: 1.50, imageLink: `${path}liquore_cinese.jpg`, description:"", category:"DRINKS" },
    { id: "amaro_cinese_alle_cinque_erbe", name: 'Amaro cinese alle cinque erbe', price: 1.50, imageLink: `${path}amaro_cinese_alle_cinque_erbe.jpg`, description:"", category:"DRINKS" },
    { id: "sake", name: 'Sake', price: 2.00, imageLink: `${path}sake.jpg`, description:"", category:"DRINKS" },
    { id: "caffe", name: 'Caffè', price: 1.20, imageLink: `${path}caffe.jpg`, description:"", category:"DRINKS" },
    { id: "caffe_macchiato", name: 'Caffè macchiato', price: 1.40, imageLink: `${path}caffe_macchiato.jpg`, description:"", category:"DRINKS" },
    { id: "caffe_corretto", name: 'Caffè corretto', price: 1.60, imageLink: `${path}caffe_corretto.jpg`, description:"", category:"DRINKS" },
    { id: "caffe_d_orzo", name: 'Caffè d’orzo', price: 1.60, imageLink: `${path}caffe_d_orzo.jpg`, description:"", category:"DRINKS" },
    { id: "caffe_decaffeinato", name: 'Caffè decaffeinato', price: 1.60, imageLink: `${path}caffe_decaffeinato.jpg`, description:"", category:"DRINKS" },
    { id: "caffe_ginseng", name: 'Caffè GinSeng', price: 1.60, imageLink: `${path}caffe_ginseng.jpg`, description:"", category:"DRINKS" },
    { id: "cappuccino", name: 'Cappuccino', price: 1.80, imageLink: `${path}cappuccino.jpg`, description:"", category:"DRINKS" },

                                 
]

export default MenuEn;