const MenuIt=[
    { id: "0", name: 'Pane cinese fritto', price: 1.00, imageLink: 'src/assets/menu/0.jpg', description:"", category:"Antipasti" },
  { id: "0A", name: 'Pane cinese al vapore', price: 1.00, imageLink: 'src/assets/menu/0A.jpg', description:"", category:"Antipasti" },
  { id: "1", name: 'Involtini primavera verdure', price: 1.50, imageLink: 'src/assets/menu/1.jpg', description:"", category:"Antipasti" },
  { id: "1A", name: 'Involtini speciali', price: 1.80, imageLink: 'src/assets/menu/1A.jpg', description:"", category:"Antipasti" },
  { id: "2", name: 'Wanton fritti', price: 1.60, imageLink: 'src/assets/menu/2.jpg', description:"", category:"Antipasti" },
  { id: "3", name: 'Nuvole di gamberi', price: 1.50, imageLink: 'src/assets/menu/3.jpg', description:"", category:"Antipasti" },
  { id: "4", name: 'Alghe fritte', price: 3.00, imageLink: 'src/assets/menu/4.jpg', description:"", category:"Antipasti" },
  { id: "5", name: 'Crocchette di patate', price: 2.00, imageLink: 'src/assets/menu/5.jpg', description:"", category:"Antipasti" },
  { id: "5A", name: 'Bruschetta al pomodoro', price: 2.60, imageLink: 'src/assets/menu/5A.jpg', description:"", category:"Antipasti" },
  { id: "6", name: 'Patatine fritte', price: 2.50, imageLink: 'src/assets/menu/6.jpg', description:"", category:"Antipasti" },
  { id: "7", name: 'Toast di gamberi', price: 2.50, imageLink: 'src/assets/menu/7.jpg', description:"", category:"Antipasti" },
  { id: "8", name: 'Pizza cinese', price: 3.00, imageLink: 'src/assets/menu/8.jpg', description:"", category:"Antipasti" },
  { id: "9", name: 'Ravioli di carne al vapore', price: 3.20, imageLink: 'src/assets/menu/9.jpg', description:"", category:"Antipasti" },
  { id: "10", name: 'Ravioli di verdura', price: 3.40, imageLink: 'src/assets/menu/10.jpg', description:"", category:"Antipasti" },
  { id: "11", name: 'Ravioli di carne alla griglia', price: 3.60, imageLink: 'src/assets/menu/11.jpg', description:"", category:"Antipasti" },
  { id: "12", name: 'Xiao mai di gamberi', price: 3.80, imageLink: 'src/assets/menu/12.jpg', description:"", category:"Antipasti" },
  { id: "12A", name: 'Ravioli di cristallo', price: 3.80, imageLink: 'src/assets/menu/12A.jpg', description:"", category:"Antipasti" },
  { id: "12B", name: 'Ravioli miste', price: 3.80, imageLink: 'src/assets/menu/12B.jpg', description:"", category:"Antipasti" },
  { id: "12C", name: 'Ravioli alla felicità', price: 3.80, imageLink: 'src/assets/menu/12C.jpg', description:"", category:"Antipasti" },
  { id: "13", name: 'Antipasto misto caldo', price: 4.00, imageLink: 'src/assets/menu/13.jpg', description:"", category:"Antipasti" },
  { id: "14", name: 'Verdure fritte', price: 3.00, imageLink: 'src/assets/menu/14.jpg', description:"", category:"Antipasti" },
  { id: "14A", name: 'Polpette di gamberi con sesamo', price: 3.50, imageLink: 'src/assets/menu/14A.jpg', description:"", category:"Antipasti" },
  { id: "14B", name: 'Anelli di cipolla fritti', price: 3.00, imageLink: 'src/assets/menu/14B.jpg', description:"", category:"Antipasti" },
  { id: "14C", name: 'Fagioli di soia', price: 3.50, imageLink: 'src/assets/menu/14C.jpg', description:"", category:"Antipasti" },
  { id: "15", name: 'Insalata di alghe cinesi', price: 3.00, imageLink: 'src/assets/menu/15.jpg', description:"", category:"Insalate" },
  { id: "16", name: 'Insalata di pollo e maionese', price: 3.50, imageLink: 'src/assets/menu/16.jpg', description:"", category:"Insalate" },
  { id: "17", name: 'Insalata di gamberi e maionese', price: 3.50, imageLink: 'src/assets/menu/17.jpg', description:"", category:"Insalate" },
  { id: "17A", name: 'Insalata di polpa di granchio e maionese', price: 3.50, imageLink: 'src/assets/menu/17A.jpg', description:"", category:"Insalate" },
  { id: "17B", name: 'Insalata mista', price: 3.00, imageLink: 'src/assets/menu/17B.jpg', description:"", category:"Insalate" },
  { id: "17C", name: 'Insalata con gamberi e noccioline in salsa speciale', price: 4.00, imageLink: 'src/assets/menu/17C.jpg', description:"", category:"Insalate" },
  { id: "17D", name: 'Insalata di misto mare', price: 6.00, imageLink: 'src/assets/menu/17D.jpg', description:"", category:"Insalate" },
  { id: "17E", name: 'Insalata con gamberi, granchio e maionese', price: 4.00, imageLink: 'src/assets/menu/17E.jpg', description:"", category:"Insalate" },
  { id: "18", name: 'Zuppa orientale', price: 3.00, imageLink: 'src/assets/menu/18.jpg', description:"", category:"Zuppe" },
  { id: "19", name: 'Zuppa di wanton', price: 3.00, imageLink: 'src/assets/menu/19.jpg', description:"", category:"Zuppe" },
  { id: "19A", name: 'Zuppa alla felicità', price: 3.50, imageLink: 'src/assets/menu/19A.jpg', description:"", category:"Zuppe" },
  { id: "20", name: 'Zuppa di pollo con funghi e bambù', price: 3.00, imageLink: 'src/assets/menu/20.jpg', description:"", category:"Zuppe" },
  { id: "21", name: 'Zuppa agropiccante', price: 3.00, imageLink: 'src/assets/menu/21.jpg', description:"", category:"Zuppe" },
  { id: "22", name: 'Zuppa di vermicelli di soia con zazai', price: 3.00, imageLink: 'src/assets/menu/22.jpg', description:"", category:"Zuppe" },
  { id: "23", name: 'Zuppa di mais pollo', price: 3.00, imageLink: 'src/assets/menu/23.jpg', description:"", category:"Zuppe" },
  { id: "24", name: 'Zuppa di polpa di granchio e asparagi', price: 3.50, imageLink: 'src/assets/menu/24.jpg', description:"", category:"Zuppe" },
  { id: "25A", name: 'Zuppa di vegetale con toufu', price: 3.00, imageLink: 'src/assets/menu/25A.jpg', description:"", category:"Zuppe" },
  { id: "25B", name: 'Zuppa di miso', price: 3.00, imageLink: 'src/assets/menu/25B.jpg', description:"", category:"Zuppe" },
  { id: "25C", name: 'Zuppa di misto mare', price: 3.80, imageLink: 'src/assets/menu/25C.jpg', description:"", category:"Zuppe" },
  { id: "25D", name: 'Zuppa di gamberi alla thailandese', price: 3.80, imageLink: 'src/assets/menu/25D.jpg', description:"", category:"Zuppe" },
  { id: "25E", name: 'Zuppa di pollo alla thailandese', price: 3.80, imageLink: 'src/assets/menu/25E.jpg', description:"", category:"Zuppe" },
  { id: "26", name: 'Tagliatelle saltate con verdure miste', price: 3.50, imageLink: 'src/assets/menu/26.jpg', description:"", category:"Pasta&Riso" },
  { id: "26A", name: 'Udon con verdure', price: 4.00, imageLink: 'src/assets/menu/26A.jpg', description:"", category:"Pasta&Riso" },
  { id: "26B", name: 'Udon con frutti di mare', price: 5.50, imageLink: 'src/assets/menu/26B.jpg', description:"", category:"Pasta&Riso" },
  { id: "26C", name: 'Pasta in brodo con pesce', price: 6.00, imageLink: 'src/assets/menu/26C.jpg', description:"", category:"Pasta&Riso" },
  { id: "26D", name: 'Pasta in brodo con carne', price: 6.00, imageLink: 'src/assets/menu/26D.jpg', description:"", category:"Pasta&Riso" },
  { id: "27", name: 'Tagliatelle saltate con gamberetti', price: 4.20, imageLink: 'src/assets/menu/27.jpg', description:"", category:"Pasta&Riso" },
  { id: "28", name: 'Tagliatelle alla piastra con verdure miste', price: 4.00, imageLink: 'src/assets/menu/28.jpg', description:"", category:"Pasta&Riso" },
  { id: "28A", name: 'Tan tan mian', price: 4.00, imageLink: 'src/assets/menu/28A.jpg', description:"", category:"Pasta&Riso" },
  { id: "28B", name: 'Tagliatelle alla piastra con carne e verdure', price: 4.50, imageLink: 'src/assets/menu/28B.jpg', description:"", category:"Pasta&Riso" },
  { id: "28C", name: 'Tan tan fan', price: 4.00, imageLink: 'src/assets/menu/28C.jpg', description:"", category:"Pasta&Riso" },
  { id: "29", name: 'Tagliatelle con frutti di mare alla piastra', price: 4.90, imageLink: 'src/assets/menu/29.jpg', description:"", category:"Pasta&Riso" },
  { id: "29A", name: 'Vermicelli di soia con frutti di mare alla piastra', price: 4.90, imageLink: 'src/assets/menu/29A.jpg', description:"", category:"Pasta&Riso" },
  { id: "29B", name: 'Spaghetti di riso con frutti di mare alla piastra', price: 4.90, imageLink: 'src/assets/menu/29B.jpg', description:"", category:"Pasta&Riso" },
  { id: "30", name: 'Tagliatelle fritte con verdura mista', price: 3.50, imageLink: 'src/assets/menu/30.jpg', description:"", category:"Pasta&Riso" },
  { id: "30A", name: 'Tagliatelle fritte con frutti di mare', price: 4.90, imageLink: 'src/assets/menu/30A.jpg', description:"", category:"Pasta&Riso" },
  { id: "31", name: 'Spaghetti di riso con verdure miste', price: 3.50, imageLink: 'src/assets/menu/31.jpg', description:"", category:"Pasta&Riso" },
  { id: "31A", name: 'Spaghetti di riso alla piastra con pesce e verdure', price: 4.90, imageLink: 'src/assets/menu/31A.jpg', description:"", category:"Pasta&Riso" },
  { id: "31B", name: 'Spaghetti di riso con gamberi e verdure', price: 4.20, imageLink: 'src/assets/menu/31B.jpg', description:"", category:"Pasta&Riso" },
  { id: "32", name: 'Spaghetti di riso con maiale e verdure', price: 4.00, imageLink: 'src/assets/menu/32.jpg', description:"", category:"Pasta&Riso" },
  { id: "33", name: 'Spaghetti di riso al curry', price: 3.50, imageLink: 'src/assets/menu/33.jpg', description:"", category:"Pasta&Riso" },
  { id: "34", name: 'Vermicelli di soia con maiale piccante', price: 4.00, imageLink: 'src/assets/menu/34.jpg', description:"", category:"Pasta&Riso" },
  { id: "35", name: 'Vermicelli di soia verdure miste', price: 3.50, imageLink: 'src/assets/menu/35.jpg', description:"", category:"Pasta&Riso" },
  { id: "35A", name: 'Vermicelli di soia con gamberi e verdure', price: 4.20, imageLink: 'src/assets/menu/35A.jpg', description:"", category:"Pasta&Riso" },
  { id: "36", name: 'Gnocchi di riso con verdure miste', price: 3.80, imageLink: 'src/assets/menu/36.jpg', description:"", category:"Pasta&Riso" },
  { id: "36A", name: 'Gnocchi di riso con frutti di mare', price: 5.00, imageLink: 'src/assets/menu/36A.jpg', description:"", category:"Pasta&Riso" },
  { id: "36B", name: 'Gnocchi di riso con maiale e verdure', price: 4.30, imageLink: 'src/assets/menu/36B.jpg', description:"", category:"Pasta&Riso" },
  { id: "37", name: 'Riso saltato con gamberi', price: 4.20, imageLink: 'src/assets/menu/37.jpg', description:"", category:"Pasta&Riso" },
  { id: "38", name: 'Riso saltato con le verdure miste', price: 3.50, imageLink: 'src/assets/menu/38.jpg', description:"", category:"Pasta&Riso" },
  { id: "39", name: 'Riso alla cantonese', price: 3.50, imageLink: 'src/assets/menu/39.jpg', description:"", category:"Pasta&Riso" },
  { id: "39A", name: 'Riso con pollo', price: 3.50, imageLink: 'src/assets/menu/39A.jpg', description:"", category:"Pasta&Riso" },
  { id: "40", name: 'Riso al curry', price: 3.50, imageLink: 'src/assets/menu/40.jpg', description:"", category:"Pasta&Riso" },
  { id: "41", name: 'Riso saltato all\'ananas e pinoli', price: 4.00, imageLink: 'src/assets/menu/41.jpg', description:"", category:"Pasta&Riso" },
  { id: "42", name: 'Riso bianco', price: 1.50, imageLink: 'src/assets/menu/42.jpg', description:"", category:"Pasta&Riso" },
  { id: "42A", name: 'Riso croccante con carne miste', price: 4.50, imageLink: 'src/assets/menu/42A.jpg', description:"", category:"Pasta&Riso" },
  { id: "42B", name: 'Riso croccante con frutti di mare', price: 4.90, imageLink: 'src/assets/menu/42B.jpg', description:"", category:"Pasta&Riso" },
  { id: "42C", name: 'Pasta al pomodoro', price: 3.50, imageLink: 'src/assets/menu/42C.jpg', description:"", category:"Pasta&Riso" },
  { id: "42D", name: 'Pasta al ragù', price: 3.50, imageLink: 'src/assets/menu/42D.jpg', description:"", category:"Pasta&Riso" },
  { id: "42E", name: 'Riso con frutti di mare', price: 4.90, imageLink: 'src/assets/menu/42E.jpg', description:"", category:"Pasta&Riso" },
  { id: "42F", name: 'Ziao fan di pesce e carne', price: 5.00, imageLink: 'src/assets/menu/42F.jpg', description:"", category:"Pasta&Riso" },
  { id: "42G", name: 'Ziao mian di pesce e carne', price: 5.00, imageLink: 'src/assets/menu/42G.jpg', description:"", category:"Pasta&Riso" },
  { id: "42H", name: 'Pasta al thailandese', price: 4.50, imageLink: 'src/assets/menu/42H.jpg', description:"", category:"Pasta&Riso" },
  { id: "42L", name: 'Riso alla thailandese', price: 4.50, imageLink: 'src/assets/menu/42L.jpg', description:"", category:"Pasta&Riso" },
  { id: "43", name: 'Gamberi con bambù e funghi cinesi', price: 6.00, imageLink: 'src/assets/menu/43.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "44", name: 'Gamberi con verdure miste', price: 6.00, imageLink: 'src/assets/menu/44.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "45", name: 'Gamberi con piselli', price: 6.00, imageLink: 'src/assets/menu/45.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "45A", name: 'Gamberi con anacardi', price: 6.00, imageLink: 'src/assets/menu/45A.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "46", name: 'Gamberi al curry', price: 6.00, imageLink: 'src/assets/menu/46.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "47", name: 'Gamberi in salsa piccante', price: 6.00, imageLink: 'src/assets/menu/47.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "47A", name: 'Gamberi al kongbao piccante', price: 6.00, imageLink: 'src/assets/menu/47A.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "48", name: 'Gamberi fritti in salsa agrodolce', price: 6.00, imageLink: 'src/assets/menu/48.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "48A", name: 'Gamberi non fritti in salsa agrodolce', price: 6.00, imageLink: 'src/assets/menu/48A.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "49", name: 'Gamberi saltati con mela', price: 6.00, imageLink: 'src/assets/menu/49.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "49A", name: 'Gamberi saltati con arancia', price: 6.00, imageLink: 'src/assets/menu/49A.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "49B", name: 'Gamberi saltati con limone', price: 6.00, imageLink: 'src/assets/menu/49B.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "49C", name: 'Gamberi saltati con ananas', price: 6.00, imageLink: 'src/assets/menu/49C.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "50", name: 'Gamberi fritti', price: 6.00, imageLink: 'src/assets/menu/50.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "50A", name: 'Gamberi fritti al sesamo', price: 6.50, imageLink: 'src/assets/menu/50A.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "51", name: 'Gamberi alla griglia con pepe', price: 6.50, imageLink: 'src/assets/menu/51.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "52", name: 'Gamberi con porri e carote alla piastra', price: 6.50, imageLink: 'src/assets/menu/52.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "53A", name: 'Nido di gamberi con verdure', price: 6.50, imageLink: 'src/assets/menu/53A.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "53B", name: 'Nido di pesce misto', price: 6.50, imageLink: 'src/assets/menu/53B.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "53C", name: 'Spiedini di calamari e gamberi', price: 7.00, imageLink: 'src/assets/menu/53C.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "53D", name: 'Spiedini di gamberi', price: 7.00, imageLink: 'src/assets/menu/53D.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "53E", name: 'Spiedini di calamari', price: 7.00, imageLink: 'src/assets/menu/53E.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "53F", name: 'Crostacei alla thailandese', price: 7.00, imageLink: 'src/assets/menu/53F.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "53G", name: 'Crostacei al satè', price: 7.00, imageLink: 'src/assets/menu/53G.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "54", name: 'Gamberoni in salsa piccante', price: 6.50, imageLink: 'src/assets/menu/54.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "55", name: 'Gamberoni al vapore', price: 6.50, imageLink: 'src/assets/menu/55.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "56", name: 'Gamberi stufati in salsa cinese', price: 6.50, imageLink: 'src/assets/menu/56.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "57", name: 'Gamberoni fritti con sesamo', price: 6.50, imageLink: 'src/assets/menu/57.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "57A", name: 'Gamberi fritti all\'imperiale', price: 7.00, imageLink: 'src/assets/menu/57A.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "58", name: 'Gamberoni alla griglia (6 pezzi)', price: 9.00, imageLink: 'src/assets/menu/58.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "59", name: 'Gamberoni alla piastra con porri e carote', price: 9.00, imageLink: 'src/assets/menu/59.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "59A", name: 'Gamberoni al sale e pepe', price: 9.00, imageLink: 'src/assets/menu/59A.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "59B", name: 'Gamberoni al flambè', price: 9.00, imageLink: 'src/assets/menu/59B.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "60", name: 'Fantasia di mare alla piastra piccante', price: 7.00, imageLink: 'src/assets/menu/60.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "61", name: 'Filetti di pesce al limone', price: 6.00, imageLink: 'src/assets/menu/61.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "62", name: 'Filetti di pesce al vapore', price: 6.00, imageLink: 'src/assets/menu/62.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "63", name: 'Pesce alla griglia (intero)', price: 10.00, imageLink: 'src/assets/menu/63.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "64", name: 'Pesce al vapore (intero)', price: 10.00, imageLink: 'src/assets/menu/64.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "65", name: 'Pesce stufato con salsa cinese (intero)', price: 10.00, imageLink: 'src/assets/menu/65.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "66", name: 'Calamari in salsa piccante', price: 6.00, imageLink: 'src/assets/menu/66.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "67", name: 'Calamari fritti in salsa agrodolce', price: 6.00, imageLink: 'src/assets/menu/67.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "67A", name: 'Calamari non fritti in salsa agrodolce', price: 6.00, imageLink: 'src/assets/menu/67A.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "68", name: 'Calamari con verdure miste', price: 6.00, imageLink: 'src/assets/menu/68.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "68A", name: 'Calamari alla piastra con porri e carote', price: 6.50, imageLink: 'src/assets/menu/68A.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "69", name: 'Cosce di rana fritta', price: 7.50, imageLink: 'src/assets/menu/69.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "70", name: 'Cosce di rana alla piastra', price: 7.50, imageLink: 'src/assets/menu/70.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "71", name: 'Chele di granchio fritto (5 Pezzi)', price: 6.50, imageLink: 'src/assets/menu/71.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "71A", name: 'Granchio al vapore', price: 9.00, imageLink: 'src/assets/menu/71A.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "71B", name: 'Granchio stufato in salsa cinese', price: 9.00, imageLink: 'src/assets/menu/71B.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "71C", name: 'Granchio al pepe e sale', price: 9.00, imageLink: 'src/assets/menu/71C.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "72", name: 'Frittura di pesce', price: 6.00, imageLink: 'src/assets/menu/72.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "73", name: 'Pentolino con frutti di mare', price: 7.00, imageLink: 'src/assets/menu/73.jpg', description:"", category:"Crostacei&Pesce" },
  { id: "74", name: 'Pollo fritto in salsa agrodolce', price: 5.00, imageLink: 'src/assets/menu/74.jpg', description:"", category:"Pollo" },
  { id: "74A", name: 'Pollo con peperoni', price: 5.00, imageLink: 'src/assets/menu/74A.jpg', description:"", category:"Pollo" },
  { id: "74B", name: 'Pollo non fritto in salsa agrodolce', price: 5.00, imageLink: 'src/assets/menu/74B.jpg', description:"", category:"Pollo" },
  { id: "75", name: 'Pollo fritto al limone', price: 5.00, imageLink: 'src/assets/menu/75.jpg', description:"", category:"Pollo" },
  { id: "75A", name: 'Pollo non fritto al limone', price: 5.00, imageLink: 'src/assets/menu/75A.jpg', description:"", category:"Pollo" },
  { id: "75B", name: 'Pollo con asparagi', price: 5.00, imageLink: 'src/assets/menu/75B.jpg', description:"", category:"Pollo" },
  { id: "75C", name: 'Pollo con sedano', price: 5.00, imageLink: 'src/assets/menu/75C.jpg', description:"", category:"Pollo" },
  { id: "76", name: 'Pollo fritto all\'arancia', price: 5.00, imageLink: 'src/assets/menu/76.jpg', description:"", category:"Pollo" },
  { id: "76A", name: 'Pollo non fritto all’arancia', price: 5.00, imageLink: 'src/assets/menu/76A.jpg', description:"", category:"Pollo" },
  { id: "77", name: 'Pollo con germogli di soia', price: 5.00, imageLink: 'src/assets/menu/77.jpg', description:"", category:"Pollo" },
  { id: "78", name: 'Pollo alle mandorle', price: 5.00, imageLink: 'src/assets/menu/78.jpg', description:"", category:"Pollo" },
  { id: "78A", name: 'Pollo con anacardi', price: 5.00, imageLink: 'src/assets/menu/78A.jpg', description:"", category:"Pollo" },
  { id: "79", name: 'Pollo alla kongbao piccante', price: 5.00, imageLink: 'src/assets/menu/79.jpg', description:"", category:"Pollo" },
  { id: "80", name: 'Pollo arrosto con aromi cinesi', price: 5.50, imageLink: 'src/assets/menu/80.jpg', description:"", category:"Pollo" },
  { id: "81", name: 'Pollo arrosto in salsa cinese', price: 5.50, imageLink: 'src/assets/menu/81.jpg', description:"", category:"Pollo" },
  { id: "82", name: 'Pollo con bambù e funghi cinesi', price: 5.00, imageLink: 'src/assets/menu/82.jpg', description:"", category:"Pollo" },
  { id: "83", name: 'Pollo all\'ananas', price: 5.00, imageLink: 'src/assets/menu/83.jpg', description:"", category:"Pollo" },
  { id: "84", name: 'Pollo al curry', price: 5.00, imageLink: 'src/assets/menu/84.jpg', description:"", category:"Pollo" },
  { id: "85", name: 'Bocconcini di pollo fritto', price: 5.00, imageLink: 'src/assets/menu/85.jpg', description:"", category:"Pollo" },
  { id: "85A", name: 'Pollo impanato fritto', price: 5.50, imageLink: 'src/assets/menu/85A.jpg', description:"", category:"Pollo" },
  { id: "85B", name: 'Pollo fritto al sesamo', price: 6.00, imageLink: 'src/assets/menu/85B.jpg', description:"", category:"Pollo" },
  { id: "86", name: 'Pollo con gamberi e funghi', price: 6.00, imageLink: 'src/assets/menu/86.jpg', description:"", category:"Pollo" },
  { id: "87", name: 'Cestino di patate con pollo e pinoli', price: 5.50, imageLink: 'src/assets/menu/87.jpg', description:"", category:"Pollo" },
  { id: "88", name: 'Pollo alla piastra con porri e carote', price: 5.50, imageLink: 'src/assets/menu/88.jpg', description:"", category:"Pollo" },
  { id: "88A", name: 'Pollo con patate alla piastra', price: 5.50, imageLink: 'src/assets/menu/88A.jpg', description:"", category:"Pollo" },
  { id: "88B", name: 'Spiedini di carne miste (manzo & pollo)', price: 6.00, imageLink: 'src/assets/menu/88B.jpg', description:"", category:"Pollo" },
  { id: "88C", name: 'Spiedini di manzo', price: 6.00, imageLink: 'src/assets/menu/88C.jpg', description:"", category:"Pollo" },
  { id: "88D", name: 'Spiedini di pollo', price: 6.00, imageLink: 'src/assets/menu/88D.jpg', description:"", category:"Pollo" },
  { id: "88E", name: 'Carne al thailandese', price: 6.00, imageLink: 'src/assets/menu/88E.jpg', description:"", category:"Pollo" },
  { id: "88F", name: 'Carne al satè', price: 6.00, imageLink: 'src/assets/menu/88F.jpg', description:"", category:"Pollo" },
  { id: "88G", name: 'Pentolino di carne', price: 6.00, imageLink: 'src/assets/menu/88G.jpg', description:"", category:"Pollo" },
  { id: "89", name: 'Anatra arrosto all\'ananas', price: 6.50, imageLink: 'src/assets/menu/89.jpg', description:"", category:"Anatra" },
  { id: "89A", name: 'Anatra al limone', price: 6.50, imageLink: 'src/assets/menu/89A.jpg', description:"", category:"Anatra" },
  { id: "89B", name: 'Anatra all’arancia', price: 6.50, imageLink: 'src/assets/menu/89B.jpg', description:"", category:"Anatra" },
  { id: "90", name: 'Anatra arrosto con aromi cinesi', price: 6.50, imageLink: 'src/assets/menu/90.jpg', description:"", category:"Anatra" },
  { id: "91", name: 'Anatra con bambù e funghi cinesi', price: 6.50, imageLink: 'src/assets/menu/91.jpg', description:"", category:"Anatra" },
  { id: "91A", name: 'Anatra in salsa agrodolce', price: 6.50, imageLink: 'src/assets/menu/91A.jpg', description:"", category:"Anatra" },
  { id: "91B", name: 'Anatra in salsa piccante', price: 6.50, imageLink: 'src/assets/menu/91B.jpg', description:"", category:"Anatra" },
  { id: "92", name: 'Anatra pechinese', price: 9.00, imageLink: 'src/assets/menu/92.jpg', description:"", category:"Anatra" },
  { id: "92A", name: 'Anatra laccata alla pechinese (ordinare un giorno prima)', price: 40.00, imageLink: 'src/assets/menu/92A.jpg', description:"", category:"Anatra" },
  { id: "92B", name: 'Anatra alla piastra con porri e carote', price: 7.00, imageLink: 'src/assets/menu/92B.jpg', description:"", category:"Anatra" },
  { id: "93", name: 'Maiale in salsa agrodolce', price: 5.00, imageLink: 'src/assets/menu/93.jpg', description:"", category:"Maiale" },
  { id: "94", name: 'Maiale con bambù e funghi cinesi', price: 5.00, imageLink: 'src/assets/menu/94.jpg', description:"", category:"Maiale" },
  { id: "95", name: 'Maiale con germogli di soia', price: 5.00, imageLink: 'src/assets/menu/95.jpg', description:"", category:"Maiale" },
  { id: "96", name: 'Maiale in salsa piccante', price: 5.00, imageLink: 'src/assets/menu/96.jpg', description:"", category:"Maiale" },
  { id: "96A", name: 'Maiale al kongbao piccante', price: 5.00, imageLink: 'src/assets/menu/96A.jpg', description:"", category:"Maiale" },
  { id: "96B", name: 'Maiale con za zai', price: 5.00, imageLink: 'src/assets/menu/96B.jpg', description:"", category:"Maiale" },
  { id: "97", name: 'Puntine di maiale fritto', price: 5.00, imageLink: 'src/assets/menu/97.jpg', description:"", category:"Maiale" },
  { id: "97A", name: 'Maiale alla piastra con porri e carote', price: 5.50, imageLink: 'src/assets/menu/97A.jpg', description:"", category:"Maiale" },
  { id: "97B", name: 'Maiale con patate alla piastra', price: 5.50, imageLink: 'src/assets/menu/97B.jpg', description:"", category:"Maiale" },
  { id: "97C", name: 'Costolette in salsa agrodolce', price: 5.50, imageLink: 'src/assets/menu/97C.jpg', description:"", category:"Maiale" },
  { id: "97D", name: 'Costolette al pepe e sale', price: 5.50, imageLink: 'src/assets/menu/97D.jpg', description:"", category:"Maiale" },
  { id: "98", name: 'Manzo in salsa d\'ostrica', price: 5.50, imageLink: 'src/assets/menu/98.jpg', description:"", category:"Manzo" },
  { id: "98A", name: 'Manzo in salsa agrodolce', price: 5.50, imageLink: 'src/assets/menu/98A.jpg', description:"", category:"Manzo" },
  { id: "99", name: 'Manzo con bambù e funghi cinesi', price: 5.50, imageLink: 'src/assets/menu/99.jpg', description:"", category:"Manzo" },
  { id: "100", name: 'Manzo con zenzero e porri', price: 5.50, imageLink: 'src/assets/menu/100.jpg', description:"", category:"Manzo" },
  { id: "101", name: 'Manzo al curry', price: 5.50, imageLink: 'src/assets/menu/101.jpg', description:"", category:"Manzo" },
  { id: "102", name: 'Manzo con verdure miste', price: 5.50, imageLink: 'src/assets/menu/102.jpg', description:"", category:"Manzo" },
  { id: "103", name: 'Manzo con germogli di soia', price: 5.50, imageLink: 'src/assets/menu/103.jpg', description:"", category:"Manzo" },
  { id: "104", name: 'Manzo in salsa piccante', price: 5.50, imageLink: 'src/assets/menu/104.jpg', description:"", category:"Manzo" },
  { id: "105", name: 'Manzo croccante in salsa piccante', price: 5.50, imageLink: 'src/assets/menu/105.jpg', description:"", category:"Manzo" },
  { id: "106", name: 'Manzo con porri e carote alla piastra', price: 6.00, imageLink: 'src/assets/menu/106.jpg', description:"", category:"Manzo" },
  { id: "107", name: 'Carne mista in salsa cremosa piccante', price: 6.50, imageLink: 'src/assets/menu/107.jpg', description:"", category:"Manzo" },
  { id: "107A", name: 'Manzo con patate alla piastra', price: 6.00, imageLink: 'src/assets/menu/107A.jpg', description:"", category:"Manzo" },
  { id: "107B", name: 'Carne mista alla piastra con porri e carote', price: 6.00, imageLink: 'src/assets/menu/107B.jpg', description:"", category:"Manzo" },
  { id: "108", name: 'Bambù e funghi cinesi saltati', price: 3.50, imageLink: 'src/assets/menu/108.jpg', description:"", category:"Verdure" },
  { id: "109", name: 'Verdure miste saltate', price: 3.50, imageLink: 'src/assets/menu/109.jpg', description:"", category:"Verdure" },
  { id: "109A", name: 'Verdure saltate al Si-Chuang piccante', price: 3.50, imageLink: 'src/assets/menu/109A.jpg', description:"", category:"Verdure" },
  { id: "109B", name: 'Verdure miste grigliate', price: 3.50, imageLink: 'src/assets/menu/109B.jpg', description:"", category:"Verdure" },
  { id: "110", name: 'Germogli di soia saltati', price: 3.50, imageLink: 'src/assets/menu/110.jpg', description:"", category:"Verdure" },
  { id: "111", name: 'Melanzane in salsa cinese piccante', price: 3.50, imageLink: 'src/assets/menu/111.jpg', description:"", category:"Verdure" },
  { id: "111A", name: 'Patate alla piastra', price: 4.00, imageLink: 'src/assets/menu/111A.jpg', description:"", category:"Verdure" },
  { id: "111B", name: 'Cubetti di patate arrostiti', price: 4.00, imageLink: 'src/assets/menu/111B.jpg', description:"", category:"Verdure" },
  { id: "112", name: 'Omelette con granchio', price: 3.50, imageLink: 'src/assets/menu/112.jpg', description:"", category:"Omelette" },
  { id: "113", name: 'Omelette con gamberi', price: 3.50, imageLink: 'src/assets/menu/113.jpg', description:"", category:"Omelette" },
  { id: "114", name: 'Omelette con prosciutto', price: 3.50, imageLink: 'src/assets/menu/114.jpg', description:"", category:"Omelette" },
  { id: "114A", name: 'Omelette con porri', price: 3.50, imageLink: 'src/assets/menu/114A.jpg', description:"", category:"Omelette" },
  { id: "115", name: 'Tou fu con bambù e funghi cinesi', price: 4.00, imageLink: 'src/assets/menu/115.jpg', description:"", category:"TouFu" },
  { id: "116", name: 'Tou fu in salsa piccante', price: 4.00, imageLink: 'src/assets/menu/116.jpg', description:"", category:"TouFu" },
  { id: "117", name: 'Tou fu alla piastra', price: 4.00, imageLink: 'src/assets/menu/117.jpg', description:"", category:"TouFu" },
  { id: "118", name: 'Tou fu con gamberi e funghi', price: 5.50, imageLink: 'src/assets/menu/118.jpg', description:"", category:"TouFu" },
  { id: "118A", name: 'Tou fu con manzo', price: 5.50, imageLink: 'src/assets/menu/118A.jpg', description:"", category:"TouFu" },
  { id: "118C", name: 'Tou fu in salsa agrodolce', price: 3.50, imageLink: 'src/assets/menu/118C.jpg', description:"", category:"TouFu" },
  { id: "118D", name: 'Pentolino di tou fu con pesce', price: 6.00, imageLink: 'src/assets/menu/118D.jpg', description:"", category:"TouFu" },
  { id: "119", name: 'Frutta mista fritta', price: 3.00, imageLink: 'src/assets/menu/119.jpg', description:"", category:"Dolci" },
  { id: "119A", name: 'Banana fritta', price: 3.00, imageLink: 'src/assets/menu/119A.jpg', description:"", category:"Dolci" },
  { id: "119B", name: 'Mela fritta', price: 3.00, imageLink: 'src/assets/menu/119B.jpg', description:"", category:"Dolci" },
  { id: "119C", name: 'Ananas fritto', price: 3.00, imageLink: 'src/assets/menu/119C.jpg', description:"", category:"Dolci" },
  { id: "120", name: 'Frutta fritta con gelato', price: 4.00, imageLink: 'src/assets/menu/120.jpg', description:"", category:"Dolci" },
  { id: "121", name: 'Frutta mista caramellata', price: 3.50, imageLink: 'src/assets/menu/121.jpg', description:"", category:"Dolci" },
  { id: "122", name: 'Frutta mista caramellata con gelato', price: 4.50, imageLink: 'src/assets/menu/122.jpg', description:"", category:"Dolci" },
  { id: "123", name: 'Cocco fritto', price: 3.00, imageLink: 'src/assets/menu/123.jpg', description:"", category:"Dolci" },
  { id: "123A", name: 'Cocco al vapore', price: 3.00, imageLink: 'src/assets/menu/123A.jpg', description:"", category:"Dolci" },
  { id: "123B", name: 'Cocco al vapore con gelato', price: 4.00, imageLink: 'src/assets/menu/123B.jpg', description:"", category:"Dolci" },
  { id: "124", name: 'Cocco fritto con gelato', price: 4.00, imageLink: 'src/assets/menu/124.jpg', description:"", category:"Dolci" },
  { id: "125", name: 'Nutella fritta', price: 3.00, imageLink: 'src/assets/menu/125.jpg', description:"", category:"Dolci" },
  { id: "125A", name: 'Nutella fritta con gelato', price: 4.00, imageLink: 'src/assets/menu/125A.jpg', description:"", category:"Dolci" },
  { id: "125B", name: 'Nutella al vapore', price: 3.00, imageLink: 'src/assets/menu/125B.jpg', description:"", category:"Dolci" },
  { id: "125C", name: 'Nutella al vapore con gelato', price: 4.00, imageLink: 'src/assets/menu/125C.jpg', description:"", category:"Dolci" },
  { id: "126", name: 'Frutta cinese', price: 3.00, imageLink: 'src/assets/menu/126.jpg', description:"", category:"Dolci" },
  { id: "127", name: 'Frutta cinese con gelato', price: 4.00, imageLink: 'src/assets/menu/127.jpg', description:"", category:"Dolci" },
  { id: "128", name: 'Gelato fritto alla crema', price: 3.00, imageLink: 'src/assets/menu/128.jpg', description:"", category:"Dolci" },
  { id: "128A", name: 'Gelato fritto al cioccolato', price: 3.00, imageLink: 'src/assets/menu/128A.jpg', description:"", category:"Dolci" },
  { id: "129", name: 'Gelato assortito', price: 3.00, imageLink: 'src/assets/menu/129.jpg', description:"", category:"Dolci" },
  { id: "130", name: 'Tartufo bianco', price: 3.50, imageLink: 'src/assets/menu/130.jpg', description:"", category:"Dolci" },
  { id: "130A", name: 'Tartufo nero', price: 3.50, imageLink: 'src/assets/menu/130A.jpg', description:"", category:"Dolci" },
  { id: "130B", name: 'Tartufo affogato al caffè', price: 4.50, imageLink: 'src/assets/menu/130B.jpg', description:"", category:"Dolci" },
  { id: "130C", name: 'Tartufo affogato col whiskey', price: 4.50, imageLink: 'src/assets/menu/130C.jpg', description:"", category:"Dolci" },
  { id: "130D", name: 'Tiramisù', price: 3.50, imageLink: 'src/assets/menu/130D.jpg', description:"", category:"Dolci" },
  { id: "131", name: 'Gelato ripieno al limone', price: 4.50, imageLink: 'src/assets/menu/131.jpg', description:"", category:"Dolci" },
  { id: "131A", name: 'Gelato ripieno al cocco', price: 4.50, imageLink: 'src/assets/menu/131A.jpg', description:"", category:"Dolci" },
  { id: "132", name: 'Torta della casa semifreddo', price: 3.80, imageLink: 'src/assets/menu/132.jpg', description:"", category:"Dolci" },
  { id: "133", name: 'Latte fritto', price: 3.00, imageLink: 'src/assets/menu/133.jpg', description:"", category:"Dolci" },
  { id: "133A", name: 'Latte fritto con gelato', price: 4.00, imageLink: 'src/assets/menu/133A.jpg', description:"", category:"Dolci" },
  { id: "133B", name: 'Latte caramellato', price: 3.50, imageLink: 'src/assets/menu/133B.jpg', description:"", category:"Dolci" },
  { id: "134", name: 'Ananas fresco', price: 3.50, imageLink: 'src/assets/menu/134.jpg', description:"", category:"Dolci" },
  { id: "135", name: 'Fragole con panna', price: 3.50, imageLink: 'src/assets/menu/135.jpg', description:"", category:"Dolci" },
  { id: "137", name: 'Sushi dessert', price: 4.00, imageLink: 'src/assets/menu/137.jpg', description:"", category:"Dolci" },
  { id: "139", name: 'Mattonella pinoli (vari gusti a scelta)', price: 4.00, imageLink: 'src/assets/menu/139.jpg', description:"", category:"Dolci" },
  { id: "140", name: 'Sgroppino', price: 3.50, imageLink: 'src/assets/menu/140.jpg', description:"", category:"Dolci" },
  { id: "141", name: 'Panna cotta fresca (vari gusti a scelta)', price: 3.50, imageLink: 'src/assets/menu/141.jpg', description:"", category:"Dolci" },
  { id: "pinot_grigio", name: 'Pinot grigio', price: 7.90, imageLink: 'src/assets/menu/pinot_grigio.jpg', description:"", category:"Bevande" },
  { id: "chardonnay", name: 'Chardonnay', price: 7.90, imageLink: 'src/assets/menu/chardonnay.jpg', description:"", category:"Bevande" },
  { id: "verdicchio", name: 'Verdicchio', price: 8.90, imageLink: 'src/assets/menu/verdicchio.jpg', description:"", category:"Bevande" },
  { id: "vernaccia_di_san_gimignano", name: 'Vernaccia di san gimignano', price: 8.90, imageLink: 'src/assets/menu/vernaccia_di_san_gimignano.jpg', description:"", category:"Bevande" },
  { id: "mateus_rose", name: 'Mateus rose', price: 7.90, imageLink: 'src/assets/menu/mateus_rose.jpg', description:"", category:"Bevande" },
  { id: "lancers_rose", name: 'Lancers rose', price: 7.90, imageLink: 'src/assets/menu/lancers_rose.jpg', description:"", category:"Bevande" },
  { id: "santa_cristina", name: 'Santa cristina', price: 12.90, imageLink: 'src/assets/menu/santa_cristina.jpg', description:"", category:"Bevande" },
  { id: "chianti_rosso", name: 'Chianti rosso', price: 7.90, imageLink: 'src/assets/menu/chianti_rosso.jpg', description:"", category:"Bevande" },
  { id: "vino_della_casa_1l", name: 'Vino della casa 1l (Bianco/Rosso)', price: 6.00, imageLink: 'src/assets/menu/vino_della_casa_1l.jpg', description:"", category:"Bevande" },
  { id: "vino_della_casa_0.5l", name: 'Vino della casa 0.5l (Bianco/Rosso)', price: 3.50, imageLink: 'src/assets/menu/vino_della_casa_0.5l.jpg', description:"", category:"Bevande" },
  { id: "vino_della_casa_0.25L", name: 'Vino della casa 0.25L (Bianco/Rosso)', price: 2.00, imageLink: 'src/assets/menu/vino_della_casa_0.25L.jpg', description:"", category:"Bevande" },
  { id: "birra_moretti_66cl", name: 'Birra Moretti 66cl', price: 3.50, imageLink: 'src/assets/menu/birra_moretti_66cl.jpg', description:"", category:"Bevande" },
  { id: "birra_cinese_media", name: 'Birra cinese media', price: 4.00, imageLink: 'src/assets/menu/birra_cinese_media.jpg', description:"", category:"Bevande" },
  { id: "birra_tennents", name: 'Birra Tennent’s', price: 3.50, imageLink: 'src/assets/menu/birra_tennents.jpg', description:"", category:"Bevande" },
  { id: "birra_becks_33cl", name: 'Birra Becks 33cl', price: 2.50, imageLink: 'src/assets/menu/birra_becks_33cl.jpg', description:"", category:"Bevande" },
  { id: "coca_cola_33cl", name: 'Coca cola 33 cl /o Coca cola zero 33cl', price: 2.00, imageLink: 'src/assets/menu/coca_cola_33cl.jpg', description:"", category:"Bevande" },
  { id: "fanta_33cl", name: 'Fanta 33cl', price: 2.00, imageLink: 'src/assets/menu/fanta_33cl.jpg', description:"", category:"Bevande" },
  { id: "sprite_33cl", name: 'Sprite 33cl', price: 2.00, imageLink: 'src/assets/menu/sprite_33cl.jpg', description:"", category:"Bevande" },
  { id: "coca_cola_grande", name: 'Coca cola grande', price: 4.50, imageLink: 'src/assets/menu/coca_cola_grande.jpg', description:"", category:"Bevande" },
  { id: "the_freddo_limone_pesca_33cl", name: 'The freddo limone / pesca 33cl', price: 2.00, imageLink: 'src/assets/menu/the_freddo_limone_pesca_33cl.jpg', description:"", category:"Bevande" },
  { id: "the_caldo_gelsomino_verde", name: 'The caldo gelsomino / verde', price: 2.00, imageLink: 'src/assets/menu/the_caldo_gelsomino_verde.jpg', description:"", category:"Bevande" },
  { id: "acqua_minerale_1l", name: 'Acqua minerale 1l', price: 2.00, imageLink: 'src/assets/menu/acqua_minerale_1l.jpg', description:"", category:"Bevande" },
  { id: "acqua_minerale_0.5l", name: 'Acqua minerale 0.5l', price: 1.00, imageLink: 'src/assets/menu/acqua_minerale_0.5l.jpg', description:"", category:"Bevande" },
  { id: "liquore_di_fragola", name: 'Liquore di fragola / mela verde / Baileys', price: 2.10, imageLink: 'src/assets/menu/liquore_di_fragola.jpg', description:"", category:"Bevande" },
  { id: "limoncello_amaro_sambuca", name: 'Limoncello / amaro / sambuca', price: 2.10, imageLink: 'src/assets/menu/limoncello_amaro_sambuca.jpg', description:"", category:"Bevande" },
  { id: "grappa_italiana_whiskey", name: 'Grappa italiana, whiskey', price: 2.10, imageLink: 'src/assets/menu/grappa_italiana_whiskey.jpg', description:"", category:"Bevande" },
  { id: "ponce_livornese", name: 'Ponce Livornese', price: 3.50, imageLink: 'src/assets/menu/ponce_livornese.jpg', description:"", category:"Bevande" },
  { id: "liquore_cinese", name: 'Liquore cinese (bambù, riso, rosa, ginseng, prugna)', price: 1.50, imageLink: 'src/assets/menu/liquore_cinese.jpg', description:"", category:"Bevande" },
  { id: "amaro_cinese_alle_cinque_erbe", name: 'Amaro cinese alle cinque erbe', price: 1.50, imageLink: 'src/assets/menu/amaro_cinese_alle_cinque_erbe.jpg', description:"", category:"Bevande" },
  { id: "sake", name: 'Sake', price: 2.00, imageLink: 'src/assets/menu/sake.jpg', description:"", category:"Bevande" },
  { id: "caffe", name: 'Caffè', price: 1.20, imageLink: 'src/assets/menu/caffe.jpg', description:"", category:"Bevande" },
  { id: "caffe_macchiato", name: 'Caffè macchiato', price: 1.40, imageLink: 'src/assets/menu/caffe_macchiato.jpg', description:"", category:"Bevande" },
  { id: "caffe_corretto", name: 'Caffè corretto', price: 1.60, imageLink: 'src/assets/menu/caffe_corretto.jpg', description:"", category:"Bevande" },
  { id: "caffe_d_orzo", name: 'Caffè d’orzo', price: 1.60, imageLink: 'src/assets/menu/caffe_d_orzo.jpg', description:"", category:"Bevande" },
  { id: "caffe_decaffeinato", name: 'Caffè decaffeinato', price: 1.60, imageLink: 'src/assets/menu/caffe_decaffeinato.jpg', description:"", category:"Bevande" },
  { id: "caffe_ginseng", name: 'Caffè GinSeng', price: 1.60, imageLink: 'src/assets/menu/caffe_ginseng.jpg', description:"", category:"Bevande" },
  { id: "cappuccino", name: 'Cappuccino', price: 1.80, imageLink: 'src/assets/menu/cappuccino.jpg', description:"", category:"Bevande" },
]
export default MenuIt;